"use strict";this.default_datachannel=this.default_datachannel||{};(function(_){var window=this;
try{
_.ba=_.ba||{};_.l=this;_.ca="closure_uid_"+(1E9*Math.random()>>>0);_.m=Date.now||function(){return+new Date};
}catch(e){_._DumpException(e)}
try{
var da,ea,fa;_.n=function(a){return void 0!==a};da=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};ea=function(a,b,c){return a.call.apply(a.bind,arguments)};
fa=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};_.q=function(a,b){function c(){}c.prototype=b.prototype;a.B=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.qc=function(a,c,f){for(var g=Array(arguments.length-2),k=2;k<arguments.length;k++)g[k-2]=arguments[k];return b.prototype[c].apply(a,g)}};
_.ga=function(a,b){var c=a.split("."),d=_.l;c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&_.n(b)?d[e]=b:d[e]?d=d[e]:d=d[e]={}};_.ha=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}};_.r=function(a,b,c){_.r=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ea:da;return _.r.apply(null,arguments)};
_.ia=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};_.ja=function(a){return"function"==fa(a)};_.ka=function(a){return"number"==typeof a};_.t=function(a){return"string"==typeof a};_.la=function(a){var b=fa(a);return"array"==b||"object"==b&&"number"==typeof a.length};_.ma=function(a){return"array"==fa(a)};_.na=function(){};_.oa=function(a,b){for(var c=a.split("."),d=b||_.l,e;e=c.shift();)if(null!=d[e])d=d[e];else return null;return d}; _.pa=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,_.pa);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))};_.q(_.pa,Error);_.pa.prototype.name="CustomError";
var qa=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},ra=function(a,b){return a<b?-1:a>b?1:0};_.sa=Array.prototype.indexOf?function(a,b,c){return Array.prototype.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(_.t(a))return _.t(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};_.ta=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.t(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)};
_.ua=Array.prototype.filter?function(a,b,c){return Array.prototype.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,g=_.t(a)?a.split(""):a,k=0;k<d;k++)if(k in g){var p=g[k];b.call(c,p,k,a)&&(e[f++]=p)}return e};_.va=Array.prototype.map?function(a,b,c){return Array.prototype.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=_.t(a)?a.split(""):a,g=0;g<d;g++)g in f&&(e[g]=b.call(c,f[g],g,a));return e};
_.wa=Array.prototype.some?function(a,b,c){return Array.prototype.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.t(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return!0;return!1};_.xa=function(a,b){var c=(0,_.sa)(a,b),d;(d=0<=c)&&Array.prototype.splice.call(a,c,1);return d};
_.ya=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;var Aa;_.za=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)};Aa=function(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b};_.Ba=function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b};var Da;_.u=function(){};_.v=function(a,b,c,d){a.a=null;b||(b=c?[c]:[]);a.A=c?String(c):void 0;a.c=0===c?-1:0;a.H=b;a:{if(a.H.length&&(b=a.H.length-1,(c=a.H[b])&&"object"==typeof c&&!_.ma(c))){a.l=b-a.c;a.b=c;break a}a.l=Number.MAX_VALUE}if(d)for(b=0;b<d.length;b++)c=d[b],c<a.l?(c+=a.c,a.H[c]=a.H[c]||_.Ca):a.b[c]=a.b[c]||_.Ca};_.Ca=[];_.w=function(a,b){if(b<a.l){var c=b+a.c,d=a.H[c];return d===_.Ca?a.H[c]=[]:d}d=a.b[b];return d===_.Ca?a.b[b]=[]:d};_.u.prototype.toString=function(){return this.H.toString()}; _.x=function(a,b){Da[a]=b;b.messageId=a};Da={};
_.Ea="StopIteration"in _.l?_.l.StopIteration:{message:"StopIteration",stack:""};_.Ga=function(){};_.Ga.prototype.next=function(){throw _.Ea;};_.Ga.prototype.$=function(){return this};a:{var Ia=_.l.navigator;if(Ia){var Ja=Ia.userAgent;if(Ja){_.Ha=Ja;break a}}_.Ha=""}_.y=function(a){return-1!=_.Ha.indexOf(a)};_.Ka=function(){return _.y("Opera")||_.y("OPR")};_.z=function(a,b){this.b={};this.a=[];this.l=this.c=0;var c=arguments.length;if(1<c){if(c%2)throw Error("f");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a){a instanceof _.z?(c=a.M(),d=a.G()):(c=_.Ba(a),d=Aa(a));for(var e=0;e<c.length;e++)this.set(c[e],d[e])}};_.h=_.z.prototype;_.h.ea=function(){return this.c};_.h.G=function(){La(this);for(var a=[],b=0;b<this.a.length;b++)a.push(this.b[this.a[b]]);return a};_.h.M=function(){La(this);return this.a.concat()};
_.h.aa=function(){return 0==this.c};_.h.clear=function(){this.b={};this.l=this.c=this.a.length=0};_.h.remove=function(a){return _.Ma(this.b,a)?(delete this.b[a],this.c--,this.l++,this.a.length>2*this.c&&La(this),!0):!1};var La=function(a){if(a.c!=a.a.length){for(var b=0,c=0;b<a.a.length;){var d=a.a[b];_.Ma(a.b,d)&&(a.a[c++]=d);b++}a.a.length=c}if(a.c!=a.a.length){for(var e={},c=b=0;b<a.a.length;)d=a.a[b],_.Ma(e,d)||(a.a[c++]=d,e[d]=1),b++;a.a.length=c}};_.h=_.z.prototype;
_.h.get=function(a,b){return _.Ma(this.b,a)?this.b[a]:b};_.h.set=function(a,b){_.Ma(this.b,a)||(this.c++,this.a.push(a),this.l++);this.b[a]=b};_.h.forEach=function(a,b){for(var c=this.M(),d=0;d<c.length;d++){var e=c[d],f=this.get(e);a.call(b,f,e,this)}};_.h.clone=function(){return new _.z(this)};_.h.$=function(a){La(this);var b=0,c=this.l,d=this,e=new _.Ga;e.next=function(){if(c!=d.l)throw Error("g");if(b>=d.a.length)throw _.Ea;var e=d.a[b++];return a?e:d.b[e]};return e}; _.Ma=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
_.Na=function(a){if(a.G&&"function"==typeof a.G)return a.G();if(_.t(a))return a.split("");if(_.la(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return Aa(a)};var Ta,Va,Wa,Ya,$a,ab;_.Pa=_.Ka();_.B=_.y("Trident")||_.y("MSIE");_.Qa=_.y("Edge");_.Ra=_.y("Gecko")&&!(-1!=_.Ha.toLowerCase().indexOf("webkit")&&!_.y("Edge"))&&!(_.y("Trident")||_.y("MSIE"))&&!_.y("Edge");_.Sa=-1!=_.Ha.toLowerCase().indexOf("webkit")&&!_.y("Edge");Ta=_.l.navigator||null;_.Ua=Ta&&Ta.platform||"";Va=function(){var a=_.Ha;if(_.Ra)return/rv\:([^\);]+)(\)|;)/.exec(a);if(_.Qa)return/Edge\/([\d\.]+)/.exec(a);if(_.B)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(_.Sa)return/WebKit\/(\S+)/.exec(a)};
Wa=function(){var a=_.l.document;return a?a.documentMode:void 0};_.Xa=function(){if(_.Pa&&_.l.opera){var a;var b=_.l.opera.version;try{a=b()}catch(c){a=b}return a}a="";(b=Va())&&(a=b?b[1]:"");return _.B&&(b=Wa(),b>(0,window.parseFloat)(a))?String(b):a}();Ya={};
_.Za=function(a){var b;if(!(b=Ya[a])){b=0;for(var c=qa(String(_.Xa)).split("."),d=qa(String(a)).split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var g=c[f]||"",k=d[f]||"",p=RegExp("(\\d*)(\\D*)","g"),A=RegExp("(\\d*)(\\D*)","g");do{var E=p.exec(g)||["","",""],Y=A.exec(k)||["","",""];if(0==E[0].length&&0==Y[0].length)break;b=ra(0==E[1].length?0:(0,window.parseInt)(E[1],10),0==Y[1].length?0:(0,window.parseInt)(Y[1],10))||ra(0==E[2].length,0==Y[2].length)||ra(E[2],Y[2])}while(0==b)}b=Ya[a]= 0<=b}return b};$a=_.l.document;ab=$a&&_.B?Wa()||("CSS1Compat"==$a.compatMode?(0,window.parseInt)(_.Xa,10):5):void 0;
_.C=function(){this.L=this.L;this.l=this.l};_.C.prototype.L=!1;_.C.prototype.O=function(){this.L||(this.L=!0,this.v())};_.F=function(a,b){_.bb(a,_.ha(_.D,b))};_.bb=function(a,b){a.L?b.call(void 0):(a.l||(a.l=[]),a.l.push(_.n(void 0)?(0,_.r)(b,void 0):b))};_.C.prototype.v=function(){if(this.l)for(;this.l.length;)this.l.shift()()};_.D=function(a){a&&"function"==typeof a.O&&a.O()};
_.cb=!_.B||9<=ab;!_.Ra&&!_.B||_.B&&9<=ab||_.Ra&&_.Za("1.9.1");_.B&&_.Za("9");var db=function(a){db[" "](a);return a};db[" "]=_.na;_.eb=function(a,b){try{return db(a[b]),!0}catch(c){}return!1};var fb=!_.B||9<=ab,gb=_.B&&!_.Za("9");!_.Sa||_.Za("528");_.Ra&&_.Za("1.9b")||_.B&&_.Za("8")||_.Pa&&_.Za("9.5")||_.Sa&&_.Za("528");_.Ra&&!_.Za("8")||_.B&&_.Za("9");_.hb=function(a,b){this.type=a;this.a=this.target=b;this.hb=!0};_.hb.prototype.b=function(){this.hb=!1};var ib=function(a,b){_.hb.call(this,a?a.type:"");this.a=this.target=null;this.clientY=this.clientX=0;this.c=this.state=null;a&&this.U(a,b)};_.q(ib,_.hb);
ib.prototype.U=function(a,b){this.type=a.type;var c=a.changedTouches?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.a=b;var d=a.relatedTarget;d&&_.Ra&&_.eb(d,"nodeName");null===c?(this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:a.pageY):(this.clientX=void 0!==c.clientX?c.clientX:c.pageX,this.clientY=void 0!==c.clientY?c.clientY:c.pageY);this.state=a.state;this.c=a;a.defaultPrevented&&this.b()}; ib.prototype.b=function(){ib.B.b.call(this);var a=this.c;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,gb)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};
var jb,lb;jb="closure_listenable_"+(1E6*Math.random()|0);_.kb=function(a){return!(!a||!a[jb])};lb=0;var mb=function(a,b,c,d,e){this.listener=a;this.proxy=null;this.src=b;this.type=c;this.oa=!!d;this.qa=e;this.key=++lb;this.removed=this.na=!1},nb=function(a){a.removed=!0;a.listener=null;a.proxy=null;a.src=null;a.qa=null};var ob;ob=function(a){this.src=a;this.a={};this.b=0};_.qb=function(a,b,c,d,e,f){var g=b.toString();b=a.a[g];b||(b=a.a[g]=[],a.b++);var k=pb(b,c,e,f);-1<k?(a=b[k],d||(a.na=!1)):(a=new mb(c,a.src,g,!!e,f),a.na=d,b.push(a));return a};ob.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.a))return!1;var e=this.a[a];b=pb(e,b,c,d);return-1<b?(nb(e[b]),Array.prototype.splice.call(e,b,1),0==e.length&&(delete this.a[a],this.b--),!0):!1};
var rb=function(a,b){var c=b.type;c in a.a&&_.xa(a.a[c],b)&&(nb(b),0==a.a[c].length&&(delete a.a[c],a.b--))};ob.prototype.removeAll=function(a){a=a&&a.toString();var b=0,c;for(c in this.a)if(!a||c==a){for(var d=this.a[c],e=0;e<d.length;e++)++b,nb(d[e]);delete this.a[c];this.b--}return b};var sb=function(a,b,c,d,e){a=a.a[b.toString()];b=-1;a&&(b=pb(a,c,d,e));return-1<b?a[b]:null},pb=function(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.removed&&f.listener==b&&f.oa==!!c&&f.qa==d)return e}return-1};
var tb,ub,vb,Ab,Db,Eb,Bb,Gb,Fb,Cb,zb,Hb;tb="closure_lm_"+(1E6*Math.random()|0);ub={};vb=0;_.wb=function(a,b,c,d,e){if(_.ma(b)){for(var f=0;f<b.length;f++)_.wb(a,b[f],c,d,e);return null}c=_.xb(c);return _.kb(a)?a.listen(b,c,d,e):_.yb(a,b,c,!1,d,e)};
_.yb=function(a,b,c,d,e,f){if(!b)throw Error("j");var g=!!e,k=zb(a);k||(a[tb]=k=new ob(a));c=_.qb(k,b,c,d,e,f);if(c.proxy)return c;d=Ab();c.proxy=d;d.src=a;d.listener=c;if(a.addEventListener)a.addEventListener(b.toString(),d,g);else if(a.attachEvent)a.attachEvent(Bb(b.toString()),d);else throw Error("k");vb++;return c};Ab=function(){var a=Cb,b=fb?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b};
Db=function(a,b,c,d,e){if(_.ma(b))for(var f=0;f<b.length;f++)Db(a,b[f],c,d,e);else c=_.xb(c),_.kb(a)?a.Ea(b,c,d,e):a&&(a=zb(a))&&(b=sb(a,b,c,!!d,e))&&Eb(b)};Eb=function(a){if(!_.ka(a)&&a&&!a.removed){var b=a.src;if(_.kb(b))rb(b.S,a);else{var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.oa):b.detachEvent&&b.detachEvent(Bb(c),d);vb--;(c=zb(b))?(rb(c,a),0==c.b&&(c.src=null,b[tb]=null)):nb(a)}}};Bb=function(a){return a in ub?ub[a]:ub[a]="on"+a};
Gb=function(a,b,c,d){var e=!0;if(a=zb(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.oa==c&&!f.removed&&(f=Fb(f,d),e=e&&!1!==f)}return e};Fb=function(a,b){var c=a.listener,d=a.qa||a.src;a.na&&Eb(a);return c.call(d,b)};
Cb=function(a,b){if(a.removed)return!0;if(!fb){var c=b||_.oa("window.event"),d=new ib(c,this),e=!0;if(!(0>c.keyCode||void 0!=c.returnValue)){a:{var f=!1;if(0==c.keyCode)try{c.keyCode=-1;break a}catch(p){f=!0}if(f||void 0==c.returnValue)c.returnValue=!0}c=[];for(f=d.a;f;f=f.parentNode)c.push(f);for(var f=a.type,g=c.length-1;0<=g;g--){d.a=c[g];var k=Gb(c[g],f,!0,d),e=e&&k}for(g=0;g<c.length;g++)d.a=c[g],k=Gb(c[g],f,!1,d),e=e&&k}return e}return Fb(a,new ib(b,this))}; zb=function(a){a=a[tb];return a instanceof ob?a:null};Hb="__closure_events_fn_"+(1E9*Math.random()>>>0);_.xb=function(a){if(_.ja(a))return a;a[Hb]||(a[Hb]=function(b){return a.handleEvent(b)});return a[Hb]};
_.Ib=function(a){_.v(this,a,"h_cc",null)};_.q(_.Ib,_.u);_.x("h_cc",_.Ib);_.Ib.prototype.T=function(){return _.w(this,19)};_.G=function(a){this.a=a};_.G.prototype.toString=function(){return this.a};_.H=function(a){_.C.call(this);this.I=a;this.f={}};_.q(_.H,_.C);var Jb=[];_.H.prototype.listen=function(a,b,c,d){return _.Kb(this,a,b,c,d)};_.Kb=function(a,b,c,d,e,f){_.ma(c)||(c&&(Jb[0]=c.toString()),c=Jb);for(var g=0;g<c.length;g++){var k=_.wb(b,c[g],d||a.handleEvent,e||!1,f||a.I||a);if(!k)break;a.f[k.key]=k}return a};
_.H.prototype.Ea=function(a,b,c,d,e){if(_.ma(b))for(var f=0;f<b.length;f++)this.Ea(a,b[f],c,d,e);else c=c||this.handleEvent,e=e||this.I||this,c=_.xb(c),d=!!d,b=_.kb(a)?sb(a.S,String(b),c,d,e):a?(a=zb(a))?sb(a,b,c,d,e):null:null,b&&(Eb(b),delete this.f[b.key]);return this};_.H.prototype.removeAll=function(){_.za(this.f,function(a,b){this.f.hasOwnProperty(b)&&Eb(a)},this);this.f={}};_.H.prototype.v=function(){_.H.B.v.call(this);this.removeAll()}; _.H.prototype.handleEvent=function(){throw Error("l");};
var Lb=function(a,b,c){this.l=c;this.c=a;this.f=b;this.b=0;this.a=null};Lb.prototype.get=function(){var a;0<this.b?(this.b--,a=this.a,this.a=a.next,a.next=null):a=this.c();return a};var Mb=function(a,b){a.f(b);a.b<a.l&&(a.b++,b.next=a.a,a.a=b)};var Nb,Ob,Pb;Nb=function(a){_.l.setTimeout(function(){throw a;},0)};_.Qb=function(a,b){var c=a;b&&(c=(0,_.r)(a,b));!_.ja(_.l.setImmediate)||_.l.Window&&_.l.Window.prototype&&!_.y("Edge")&&_.l.Window.prototype.setImmediate==_.l.setImmediate?(Ob||(Ob=Pb()),Ob(c)):_.l.setImmediate(c)};
Pb=function(){var a=_.l.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&!_.y("Presto")&&(a=function(){var a=window.document.createElement("IFRAME");a.style.display="none";a.src="";window.document.documentElement.appendChild(a);var b=a.contentWindow,a=b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d="file:"==b.location.protocol?"*":b.location.protocol+"//"+b.location.host,a=(0,_.r)(function(a){if(("*"==
d||a.origin==d)&&a.data==c)this.port1.onmessage()},this);b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});if("undefined"!==typeof a&&!_.y("Trident")&&!_.y("MSIE")){var b=new a,c={},d=c;b.port1.onmessage=function(){if(_.n(c.next)){c=c.next;var a=c.Ya;c.Ya=null;a()}};return function(a){d.next={Ya:a};d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof window.document&&"onreadystatechange"in window.document.createElement("SCRIPT")?function(a){var b= window.document.createElement("SCRIPT");b.onreadystatechange=function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};window.document.documentElement.appendChild(b)}:function(a){_.l.setTimeout(a,0)}};
var Rb=function(){this.b=this.a=null},Tb=new Lb(function(){return new Sb},function(a){a.reset()},100);Rb.prototype.remove=function(){var a=null;this.a&&(a=this.a,this.a=this.a.next,this.a||(this.b=null),a.next=null);return a};var Sb=function(){this.next=this.b=this.a=null};Sb.prototype.set=function(a,b){this.a=a;this.b=b;this.next=null};Sb.prototype.reset=function(){this.next=this.b=this.a=null};
var Yb=function(a,b){Ub||Vb();Wb||(Ub(),Wb=!0);var c=Xb,d=Tb.get();d.set(a,b);c.b?c.b.next=d:c.a=d;c.b=d},Ub,Vb=function(){if(_.l.Promise&&_.l.Promise.resolve){var a=_.l.Promise.resolve(void 0);Ub=function(){a.then(Zb)}}else Ub=function(){_.Qb(Zb)}},Wb=!1,Xb=new Rb,Zb=function(){for(var a=null;a=Xb.remove();){try{a.a.call(a.b)}catch(b){Nb(b)}Mb(Tb,a)}Wb=!1};
_.I=function(){_.C.call(this);this.S=new ob(this);this.K=this;this.C=null};_.q(_.I,_.C);_.I.prototype[jb]=!0;_.h=_.I.prototype;_.h.addEventListener=function(a,b,c,d){_.wb(this,a,b,c,d)};_.h.removeEventListener=function(a,b,c,d){Db(this,a,b,c,d)};_.h.v=function(){_.I.B.v.call(this);this.S&&this.S.removeAll(void 0);this.C=null};_.h.listen=function(a,b,c,d){return _.qb(this.S,String(a),b,!1,c,d)};_.h.Ea=function(a,b,c,d){return this.S.remove(String(a),b,c,d)}; _.h.Z=function(a,b,c){a=this.S.a[String(a)];if(!a)return!0;a=a.concat();for(var d=!0,e=0;e<a.length;++e){var f=a[e];if(f&&!f.removed&&f.oa==b){var g=f.listener,k=f.qa||f.src;f.na&&rb(this.S,f);d=!1!==g.call(k,c)&&d}}return d&&0!=c.hb};
var $b=function(a){a.prototype.then=a.prototype.then;a.prototype.$goog_Thenable=!0},ac=function(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};var cc=function(a,b){this.a=0;this.h=void 0;this.c=this.b=this.l=null;this.f=this.g=!1;if(a!=_.na)try{var c=this;a.call(b,function(a){bc(c,2,a)},function(a){bc(c,3,a)})}catch(d){bc(this,3,d)}},dc=function(){this.next=this.c=this.b=this.l=this.a=null;this.f=!1},ec,fc;dc.prototype.reset=function(){this.c=this.b=this.l=this.a=null;this.f=!1};ec=new Lb(function(){return new dc},function(a){a.reset()},100);fc=function(a,b,c){var d=ec.get();d.l=a;d.b=b;d.c=c;return d};
_.hc=function(){var a,b=new cc(function(b){a=b});return new gc(b,a)};cc.prototype.then=function(a,b,c){return ic(this,_.ja(a)?a:null,_.ja(b)?b:null,c)};$b(cc);
var kc=function(a,b){a.b||2!=a.a&&3!=a.a||jc(a);a.c?a.c.next=b:a.b=b;a.c=b},ic=function(a,b,c,d){var e=fc(null,null,null);e.a=new cc(function(a,g){e.l=b?function(c){try{var e=b.call(d,c);a(e)}catch(A){g(A)}}:a;e.b=c?function(b){try{var e=c.call(d,b);!_.n(e)&&"undefined"!=typeof lc&&b instanceof lc?g(b):a(e)}catch(A){g(A)}}:g});e.a.l=a;kc(a,e);return e.a};cc.prototype.u=function(a){this.a=0;bc(this,2,a)};cc.prototype.w=function(a){this.a=0;bc(this,3,a)};
var bc=function(a,b,c){if(0==a.a){a==c&&(b=3,c=new TypeError("Promise cannot resolve to itself"));a.a=1;var d;a:{var e=c,f=a.u,g=a.w;if(e instanceof cc)kc(e,fc(f||_.na,g||null,a)),d=!0;else if(ac(e))e.then(f,g,a),d=!0;else{if(_.ia(e))try{var k=e.then;if(_.ja(k)){mc(e,k,f,g,a);d=!0;break a}}catch(p){g.call(a,p);d=!0;break a}d=!1}}d||(a.h=c,a.a=b,a.l=null,jc(a),3!=b||"undefined"!=typeof lc&&c instanceof lc||nc(a,c))}},mc=function(a,b,c,d,e){var f=!1,g=function(a){f||(f=!0,c.call(e,a))},k=function(a){f||
(f=!0,d.call(e,a))};try{b.call(a,g,k)}catch(p){k(p)}},jc=function(a){a.g||(a.g=!0,Yb(a.j,a))},oc=function(a){var b=null;a.b&&(b=a.b,a.b=b.next,b.next=null);a.b||(a.c=null);return b};cc.prototype.j=function(){for(var a=null;a=oc(this);){var b=this.a,c=this.h;if(3==b&&a.b&&!a.f)for(var d=void 0,d=this;d&&d.f;d=d.l)d.f=!1;if(a.a)a.a.l=null,pc(a,b,c);else try{a.f?a.l.call(a.c):pc(a,b,c)}catch(e){qc.call(null,e)}Mb(ec,a)}this.g=!1}; var pc=function(a,b,c){2==b?a.l.call(a.c,c):a.b&&a.b.call(a.c,c)},nc=function(a,b){a.f=!0;Yb(function(){a.f&&qc.call(null,b)})},qc=Nb,lc=function(a){_.pa.call(this,a)};_.q(lc,_.pa);lc.prototype.name="cancel";var gc=function(a,b){this.b=a;this.a=b};
_.rc=function(a,b){for(var c=[],d=0;d<arguments.length;d++)c.push(arguments[d]||"");return c.join("_;_")};_.sc=function(){return 0<=window.navigator.userAgent.indexOf("CrOS")};_.J=function(a,b){this.f=a||"e";this.l=null!=a&&"p"==a?"e":"p";this.a=this.g=null;this.j=b||"u";this.c=this.h=null;this.b=[]};_.J.prototype.message=function(){var a={};a.i=this.c;a.m=this.b;a.r=this.j;a.o=this.h;a.s=this.a;a.st=this.l;a.d=this.g;a.dt=this.f;return a};_.J.prototype.message=_.J.prototype.message;
_.tc=function(a,b){for(var c in b)switch(c){case "r":a.j=b[c];break;case "i":a.c=b[c];break;case "m":a.b=b[c];break;case "o":a.h=b[c];break;case "s":a.a=b[c];break;case "d":a.g=b[c];break;case "st":a.l=b[c];break;case "dt":a.f=b[c]}return a};_.uc=function(a,b,c){null!=b&&(a.a=b,null!=c&&(a.l=c))};_.vc=function(a,b){null!=b&&(a.c=b)};_.wc=function(a,b){"object"==typeof b?a.b=b:a.b=[b]};_.J.prototype.target=function(){return this.g};
_.xc=function(a,b,c,d,e){_.C.call(this);this.b=a;this.ma=b;this.a=typeof b;this.Ba=c?c:!1;this.Y=!0;this.Aa=d?d:!1;this.wa=e?e:!1};_.q(_.xc,_.C);_.h=_.xc.prototype;_.h.v=function(){_.xc.B.v.call(this);this.b="";this.ma=null;this.a=""};_.h.id=function(){return this.b};_.h.type=function(){return this.a};_.h.F=function(){return this.ma};_.h.setEnabled=function(a){this.Y=a};
_.zc=function(a){_.C.call(this);this.a=new _.z;this.b=["https://hangouts.google.com","","https://autopush.hangouts.sandbox.google.com?jsmode=du"];a&&_.yc(this,a)};_.q(_.zc,_.C);_.Ac=!_.sc();_.zc.prototype.v=function(){_.zc.B.v.call(this);for(var a=this.a.M(),b=0;b<a.length;++b)_.D(this.a.get(a[b]));delete this.a};_.zc.prototype.getItem=function(a){return _.Ma(this.a.b,a)?this.a.get(a):null};_.zc.prototype.setItem=function(a){this.a.set(a.id(),a)}; _.yc=function(a,b){for(var c in b){var d=b[c],e=null;_.Ma(a.a.b,c)?(e=a.a.get(c),e.ma=d.value,d.changed&&(e.wa=d.changed)):(e=new _.xc(c,d.value,d.multiple,d.inverse,d.changed),e.setEnabled(!d.disabled));a.a.set(c,e)}};
_.Cc=function(){this.c=new _.z;this.a=null;this.b=!1;this.a=new Bc;this.b=!0;this.U()};_.Cc.fa=function(){return _.Cc.a?_.Cc.a:_.Cc.a=new _.Cc};_.h=_.Cc.prototype;_.h.U=function(a){var b=a||_.na;this.b?b():window.chrome.storage.local.get((0,_.r)(function(a){if(!this.b){for(var d in a)this.c.set(d,a[d]);this.b=!0}b()},this))};_.h.get=function(a){return this.a.get(a)};_.h.set=function(a,b){var c=_.hc();this.a.set(a,b);c.a(void 0);return c.b};_.h.remove=function(a){this.a.remove(a)};_.h.clear=function(){this.a.clear()};
var Bc=function(){this.a=window.localStorage};Bc.prototype.clear=function(){this.a.clear()};Bc.prototype.get=function(a){a=this.a.getItem(a);if(a){var b=JSON.parse(a);a=b.data;if("jspb"==b.type){b=Da[a[0]];if(!b)throw Error("d`"+a[0]);a=new b(a)}}else a=null;return a};Bc.prototype.set=function(a,b){var c=null;b instanceof _.u&&(b=b.H,c="jspb");var d={};d.data=b;d.timestamp=(0,_.m)();c&&(d.type=c);c=JSON.stringify(d);try{this.a.setItem(a,c)}catch(e){}};Bc.prototype.remove=function(a){try{this.a.removeItem(a)}catch(b){}};
/*
 Portions of this code are from MochiKit, received by
 The Closure Authors under the MIT license. All other code is Copyright
 2005-2009 The Closure Authors. All Rights Reserved.
*/
var Dc=function(a,b){this.l=[];this.D=b||null;this.a=this.b=!1;this.c=void 0;this.u=this.w=this.g=!1;this.f=0;this.h=null;this.A=0};Dc.prototype.j=function(a,b){this.g=!1;this.b=!0;this.c=b;this.a=!a;Ec(this)};Dc.prototype.C=function(a){if(this.b){if(!this.u)throw new Fc;this.u=!1}this.b=!0;this.c=a;this.a=!1;Ec(this)};var Gc=function(a,b,c){a.l.push([b,c,void 0]);a.b&&Ec(a)};
Dc.prototype.then=function(a,b,c){var d,e,f=new cc(function(a,b){d=a;e=b});Gc(this,d,function(a){e(a)});return f.then(a,b,c)};$b(Dc);
var Hc=function(a){return(0,_.wa)(a.l,function(a){return _.ja(a[1])})},Ec=function(a){if(a.f&&a.b&&Hc(a)){var b=a.f,c=Ic[b];c&&(_.l.clearTimeout(c.a),delete Ic[b]);a.f=0}a.h&&(a.h.A--,delete a.h);for(var b=a.c,d=c=!1;a.l.length&&!a.g;){var e=a.l.shift(),f=e[0],g=e[1],e=e[2];if(f=a.a?g:f)try{var k=f.call(e||a.D,b);_.n(k)&&(a.a=a.a&&(k==b||k instanceof Error),a.c=b=k);if(ac(b)||"function"===typeof _.l.Promise&&b instanceof _.l.Promise)d=!0,a.g=!0}catch(p){b=p,a.a=!0,Hc(a)||(c=!0)}}a.c=b;d&&(k=(0,_.r)(a.j,
a,!0),d=(0,_.r)(a.j,a,!1),b instanceof Dc?(Gc(b,k,d),b.w=!0):b.then(k,d));c&&(b=new Jc(b),Ic[b.a]=b,a.f=b.a)},Fc=function(){_.pa.call(this)};_.q(Fc,_.pa);Fc.prototype.message="Deferred has already fired";Fc.prototype.name="AlreadyCalledError";var Jc=function(a){this.a=_.l.setTimeout((0,_.r)(this.c,this),0);this.b=a};Jc.prototype.c=function(){delete Ic[this.a];throw this.b;};var Ic={};

}catch(e){_._DumpException(e)}
try{
var Mc;_.Kc=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);else if(_.la(a)||_.t(a))(0,_.ta)(a,b,void 0);else{var c;if(a.M&&"function"==typeof a.M)c=a.M();else if(a.G&&"function"==typeof a.G)c=void 0;else if(_.la(a)||_.t(a)){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=_.Ba(a);for(var d=_.Na(a),e=d.length,f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}};_.Lc=function(a){a&&a.parentNode&&a.parentNode.removeChild(a)}; Mc=function(a,b){for(var c=_.t(a)?a.split(""):a,d=a.length-1;0<=d;--d)d in c&&b.call(void 0,c[d],d,a)};
var Nc=function(a,b){this.c=a;this.b=b;this.constructor.Xa||(this.constructor.Xa={});this.constructor.Xa[this.toString()]=this};Nc.prototype.toString=function(){this.a||(this.a=this.c.a+":"+this.b);return this.a};var Oc=function(a,b){Nc.call(this,a,b)};_.q(Oc,Nc);var Pc=function(a){this.a=a};new Pc("lib");_.Rc=function(a){_.C.call(this);this.b={};this.u={};this.w={};this.f={};this.A={};this.D={};this.C=a?a.g():new _.I;this.K=!a;this.h=null;a?(this.h=a,this.w=a.w,this.f=a.f,this.u=a.u,this.A=a.A):(0,_.m)();a=Qc(this);this!=a&&(a.j?a.j.push(this):a.j=[this])};_.q(_.Rc,_.C);var Qc=function(a){for(;a.h;)a=a.h;return a};_.Rc.prototype.get=function(a){var b=this.c(a);if(null==b)throw new Sc(a);return b};
_.Rc.prototype.c=function(a){for(var b=this;b;b=b.h){if(b.L)throw Error("n");if(b.b[a])return b.b[a][0];if(b.D[a])break}if(b=this.w[a]){b=b(this);if(null==b)throw Error("o`"+a);this.a(a,b);return b}return null};_.Rc.prototype.a=function(a,b,c){if(this.L)c||_.D(b);else{this.b[a]=[b,!c];b=Tc(this,this,a);for(c=0;c<b.length;c++)b[c].C(null);delete this.u[a]}};_.Rc.prototype.I=function(){var a=_.Uc;if(!this.b[a])throw Error("p`"+a);var b=this.b[a];delete this.b[a];b[1]&&_.D(b[0])};
var Tc=function(a,b,c){var d=[],e=a.f[c];e&&(Mc(e,function(a){var c;a:{for(c=a.tb;c;){if(c==b){c=!0;break a}c=c.h}c=!1}c&&(d.push(a.d),_.xa(e,a))}),0==e.length&&delete a.f[c]);return d},Vc=function(a,b){a.f&&_.Kc(a.f,function(a,d,e){Mc(a,function(d){d.tb==b&&_.xa(a,d)});0==a.length&&delete e[d]})};
_.Rc.prototype.v=function(){if(Qc(this)==this){var a=this.j;if(a)for(;a.length;)a[0].O()}else for(var a=Qc(this).j,b=0;b<a.length;b++)if(a[b]==this){a.splice(b,1);break}for(var c in this.b)a=this.b[c],a[1]&&"undefined"!=typeof a[0].O&&a[0].O();this.b=null;this.K&&this.C.O();Vc(this,this);this.f=null;_.D(this.J);this.D=this.J=null;_.Rc.B.v.call(this)};_.Rc.prototype.g=function(){return this.C};var Sc=function(a){_.pa.call(this);this.id=a;this.message='Service for "'+a+'" is not registered'}; _.q(Sc,_.pa);var Wc=new Pc("fva");new Oc(Wc,1);

}catch(e){_._DumpException(e)}
try{
var Xc,Yc,Zc,fd,gd,hd,M,ld,md,pd,qd,rd,sd,td,ud,vd,xd,yd,zd,Ed;Xc=function(a,b,c,d,e){if(_.ma(b)){for(var f=0;f<b.length;f++)Xc(a,b[f],c,d,e);return null}c=_.xb(c);return _.kb(a)?_.qb(a.S,String(b),c,!0,d,e):_.yb(a,b,c,!0,d,e)};Yc="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");Zc=function(a,b,c,d,e,f){if(_.ma(c))for(var g=0;g<c.length;g++)Zc(a,b,c[g],d,e,f);else{b=Xc(b,c,d||a.handleEvent,e,f||a.I||a);if(!b)return a;a.f[b.key]=b}return a};
_.K=function(a,b,c){b<a.l?a.H[b+a.c]=c:a.b[b]=c};_.$c=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Yc.length;f++)c=Yc[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};_.ad=function(a){return a.b[0]};_.bd=function(a,b,c){null!=b&&(a.g=b,null!=c&&(a.f=c))};
_.L=function(a,b){var c,d=a.C;if(d)for(c=[];d;d=d.C)c.push(d);var d=a.K,e=b,f=e.type||e;if(_.t(e))e=new _.hb(e,d);else if(e instanceof _.hb)e.target=e.target||d;else{var g=e,e=new _.hb(f,d);_.$c(e,g)}var g=!0,k;if(c)for(var p=c.length-1;0<=p;p--)k=e.a=c[p],g=k.Z(f,!0,e)&&g;k=e.a=d;g=k.Z(f,!0,e)&&g;g=k.Z(f,!1,e)&&g;if(c)for(p=0;p<c.length;p++)k=e.a=c[p],g=k.Z(f,!1,e)&&g};_.cd=function(a,b,c,d){return Zc(a,b,c,d,void 0)};_.dd=function(a,b,c){a.a||(a.a={});var d=c?c.H:c;a.a[b]=c;_.K(a,b,d)};
_.ed=function(a,b,c){a.a||(a.a={});if(!a.a[c]){var d=_.w(a,c);d&&(a.a[c]=new b(d))}return a.a[c]};fd=function(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)};gd=function(a,b){return a?b?(0,window.decodeURI)(a.replace(/%25/g,"%2525")):(0,window.decodeURIComponent)(a):""};
hd=function(a,b){if(a)for(var c=a.split("&"),d=0;d<c.length;d++){var e=c[d].indexOf("="),f=null,g=null;0<=e?(f=c[d].substring(0,e),g=c[d].substring(e+1)):f=c[d];b(f,g?(0,window.decodeURIComponent)(g.replace(/\+/g," ")):"")}};_.id=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#(.*))?$/;_.jd=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};
_.kd=function(a){return Array.prototype.concat.apply(Array.prototype,arguments)};M=function(a,b,c){this.b=this.a=null;this.c=a||null;this.l=!!c};ld=function(a){a.a||(a.a=new _.z,a.b=0,a.c&&hd(a.c,function(b,c){var d=(0,window.decodeURIComponent)(b.replace(/\+/g," "));ld(a);a.c=null;var d=md(a,d),e=a.a.get(d);e||a.a.set(d,e=[]);e.push(c);a.b++}))};M.prototype.ea=function(){ld(this);return this.b};
M.prototype.remove=function(a){ld(this);a=md(this,a);return _.Ma(this.a.b,a)?(this.c=null,this.b-=this.a.get(a).length,this.a.remove(a)):!1};M.prototype.clear=function(){this.a=this.c=null;this.b=0};M.prototype.aa=function(){ld(this);return 0==this.b};var nd=function(a,b){ld(a);b=md(a,b);return _.Ma(a.a.b,b)};M.prototype.M=function(){ld(this);for(var a=this.a.G(),b=this.a.M(),c=[],d=0;d<b.length;d++)for(var e=a[d],f=0;f<e.length;f++)c.push(b[d]);return c};
M.prototype.G=function(a){ld(this);var b=[];if(_.t(a))nd(this,a)&&(b=_.kd(b,this.a.get(md(this,a))));else{a=this.a.G();for(var c=0;c<a.length;c++)b=_.kd(b,a[c])}return b};M.prototype.set=function(a,b){ld(this);this.c=null;a=md(this,a);nd(this,a)&&(this.b-=this.a.get(a).length);this.a.set(a,[b]);this.b++;return this};M.prototype.get=function(a,b){var c=a?this.G(a):[];return 0<c.length?String(c[0]):b};_.od=function(a,b,c){a.remove(b);0<c.length&&(a.c=null,a.a.set(md(a,b),_.jd(c)),a.b+=c.length)};
M.prototype.toString=function(){if(this.c)return this.c;if(!this.a)return"";for(var a=[],b=this.a.M(),c=0;c<b.length;c++)for(var d=b[c],e=(0,window.encodeURIComponent)(String(d)),d=this.G(d),f=0;f<d.length;f++){var g=e;""!==d[f]&&(g+="="+(0,window.encodeURIComponent)(String(d[f])));a.push(g)}return this.c=a.join("&")};M.prototype.clone=function(){var a=new M;a.c=this.c;this.a&&(a.a=this.a.clone(),a.b=this.b);return a};md=function(a,b){var c=String(b);a.l&&(c=c.toLowerCase());return c};
pd=function(a,b){b&&!a.l&&(ld(a),a.c=null,a.a.forEach(function(a,b){var e=b.toLowerCase();b!=e&&(this.remove(b),_.od(this,e,a))},a));a.l=b};qd=/#/g;rd=/[\#\?@]/g;sd=/[\#\?]/g;td=/[\#\?:]/g;ud=/[#\/\?@]/g;vd=function(a,b,c){return _.t(a)?(a=(0,window.encodeURI)(a).replace(b,fd),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null};
_.wd=function(a,b){this.c=this.j=this.f="";this.l=null;this.g=this.a="";this.h=!1;var c;"undefined"!=typeof _.wd&&a instanceof _.wd?(this.h=_.n(b)?b:a.h,xd(this,a.f),this.j=a.j,this.c=a.c,yd(this,a.l),this.a=a.a,zd(this,a.b.clone()),this.g=a.g):a&&(c=String(a).match(_.id))?(this.h=!!b,xd(this,c[1]||"",!0),this.j=gd(c[2]||""),this.c=gd(c[3]||"",!0),yd(this,c[4]),this.a=gd(c[5]||"",!0),zd(this,c[6]||"",!0),this.g=gd(c[7]||"")):(this.h=!!b,this.b=new M(null,0,this.h))};
_.wd.prototype.toString=function(){var a=[],b=this.f;b&&a.push(vd(b,ud,!0),":");var c=this.c;if(c||"file"==b)a.push("//"),(b=this.j)&&a.push(vd(b,ud,!0),"@"),a.push((0,window.encodeURIComponent)(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.l,null!=c&&a.push(":",String(c));if(c=this.a)this.c&&"/"!=c.charAt(0)&&a.push("/"),a.push(vd(c,"/"==c.charAt(0)?sd:td,!0));(c=this.b.toString())&&a.push("?",c);(c=this.g)&&a.push("#",vd(c,qd));return a.join("")};_.wd.prototype.clone=function(){return new _.wd(this)};
xd=function(a,b,c){a.f=c?gd(b,!0):b;a.f&&(a.f=a.f.replace(/:$/,""))};yd=function(a,b){if(b){b=Number(b);if((0,window.isNaN)(b)||0>b)throw Error("h`"+b);a.l=b}else a.l=null};zd=function(a,b,c){b instanceof M?(a.b=b,pd(a.b,a.h)):(c||(b=vd(b,rd)),a.b=new M(b,0,a.h))};_.N=function(a,b,c){a.b.set(b,c)};_.Ad=function(a){return a instanceof _.wd?a.clone():new _.wd(a,void 0)};
_.O=function(a,b,c){if(_.ja(a))c&&(a=(0,_.r)(a,c));else if(a&&"function"==typeof a.handleEvent)a=(0,_.r)(a.handleEvent,a);else throw Error("m");return 2147483647<b?-1:_.l.setTimeout(a,b||0)};
_.Bd=function(a,b){a instanceof _.wd||(a=_.Ad(a));b instanceof _.wd||(b=_.Ad(b));var c=a,d=b,e=c.clone(),f=!!d.f;f?xd(e,d.f):f=!!d.j;f?e.j=d.j:f=!!d.c;f?e.c=d.c:f=null!=d.l;var g=d.a;if(f)yd(e,d.l);else if(f=!!d.a)if("/"!=g.charAt(0)&&(c.c&&!c.a?g="/"+g:(c=e.a.lastIndexOf("/"),-1!=c&&(g=e.a.substr(0,c+1)+g))),c=g,".."==c||"."==c)g="";else if(-1!=c.indexOf("./")||-1!=c.indexOf("/.")){for(var g=0==c.lastIndexOf("/",0),c=c.split("/"),k=[],p=0;p<c.length;){var A=c[p++];"."==A?g&&p==c.length&&k.push(""):
".."==A?((1<k.length||1==k.length&&""!=k[0])&&k.pop(),g&&p==c.length&&k.push("")):(k.push(A),g=!0)}g=k.join("/")}else g=c;f?e.a=g:f=""!==d.b.toString();f?zd(e,gd(d.b.toString())):f=!!d.g;f&&(e.g=d.g);return e};_.Cd=function(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||Boolean(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a}; _.Dd=function(){return _.y("iPhone")&&!_.y("iPod")&&!_.y("iPad")};Ed=function(){return(_.y("Chrome")||_.y("CriOS"))&&!_.Ka()&&!_.y("Edge")};_.Fd=function(a){_.l.clearTimeout(a)};
_.Gd=_.y("Firefox");_.Hd=_.Dd()||_.y("iPod");_.Id=_.y("iPad");_.Jd=_.y("Android")&&!(Ed()||_.y("Firefox")||_.Ka()||_.y("Silk"));_.Kd=Ed();_.Ld=_.y("Safari")&&!(Ed()||_.y("Coast")||_.Ka()||_.y("Edge")||_.y("Silk")||_.y("Android"))&&!(_.Dd()||_.y("iPad")||_.y("iPod"));
var Md=function(){};Md.prototype.a=null;var Od;Od=function(){};_.q(Od,Md);_.Nd=new Od;_.Pd=function(a){_.v(this,a,"h_icr",null)};_.q(_.Pd,_.u);_.x("h_icr",_.Pd);
}catch(e){_._DumpException(e)}
try{
_.Qd=function(){return window.chrome.runtime.getURL("feedbackdialog.html")};
}catch(e){_._DumpException(e)}
try{
var Rd=function(a){try{return 2<(a.a?a.a.readyState:0)?a.a.status:-1}catch(b){return-1}},Sd=function(a){a.a&&a.I&&(a.a.ontimeout=null);_.ka(a.g)&&(_.Fd(a.g),a.g=null)},Td=/^https?$/i,Ud={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},Vd=function(a){var b=Rd(a),c;a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:c=!0;break a;default:c=!1}if(!c){if(b=0===b)a=String(a.A).match(_.id)[1]||null,!a&&_.l.self&&_.l.self.location&&
(a=_.l.self.location.protocol,a=a.substr(0,a.length-1)),b=!Td.test(a?a.toLowerCase():"");c=b}return c},Wd=function(a,b){if(a.a){Sd(a);var c=a.a,d=a.h[0]?_.na:null;a.a=null;a.h=null;b||_.L(a,"ready");try{c.onreadystatechange=d}catch(e){}}},Xd=function(a){a.u||(a.u=!0,_.L(a,"complete"),_.L(a,"error"))},Yd=function(a){return"content-type"==a.toLowerCase()},Zd=function(a){if(!a.b&&"undefined"==typeof window.XMLHttpRequest&&"undefined"!=typeof window.ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0",
"MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new window.ActiveXObject(d),a.b=d}catch(e){}}throw Error("q");}return a.b},$d=function(a,b){b.push('"',a.replace(_.ya,function(a){var b=Ud[a];b||(b="\\u"+(a.charCodeAt(0)|65536).toString(16).substr(1),Ud[a]=b);return b}),'"')},ae=function(a){if(a.b&&"undefined"!=typeof _.ba&&(!a.h[1]||4!=(a.a?a.a.readyState:0)||2!=Rd(a)))if(a.f&&4==(a.a?a.a.readyState:0))_.O(a.fb,0,a);else if(_.L(a,"readystatechange"),4==(a.a?a.a.readyState:
0)){a.b=!1;try{Vd(a)?(_.L(a,"complete"),_.L(a,"success")):Xd(a)}finally{Wd(a)}}},be=function(a){a.b=!1;a.a&&(a.c=!0,a.a.abort(),a.c=!1);Xd(a);Wd(a)},ce=function(a){return _.B&&_.Za(9)&&_.ka(a.timeout)&&_.n(a.ontimeout)},de=[],ee=["POST","PUT"],fe=function(a){return(a=Zd(a))?new window.ActiveXObject(a):new window.XMLHttpRequest},ge=function(a){var b;(b=a.a)||(b={},Zd(a)&&(b[0]=!0,b[1]=!0),b=a.a=b);return b},he=function(a){var b;a:{b=Yd;for(var c=a.length,d=_.t(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&
b.call(void 0,d[e],e,a)){b=e;break a}b=-1}return 0>b?null:_.t(a)?a.charAt(b):a[b]},ie=function(a){return null!==a&&"withCredentials"in a},je=function(a,b,c){if(null==b)c.push("null");else{if("object"==typeof b){if(_.ma(b)){var d=b;b=d.length;c.push("[");for(var e="",f=0;f<b;f++)c.push(e),je(a,d[f],c),e=",";c.push("]");return}if(b instanceof String||b instanceof Number||b instanceof Boolean)b=b.valueOf();else{c.push("{");e="";for(d in b)Object.prototype.hasOwnProperty.call(b,d)&&(f=b[d],"function"!=
typeof f&&(c.push(e),$d(d,c),c.push(":"),je(a,f,c),e=","));c.push("}");return}}switch(typeof b){case "string":$d(b,c);break;case "number":c.push((0,window.isFinite)(b)&&!(0,window.isNaN)(b)?String(b):"null");break;case "boolean":c.push(String(b));break;case "function":c.push("null");break;default:throw Error("c`"+typeof b);}}},ke=function(){},le=function(a){_.I.call(this);this.N=new _.z;this.j=a||null;this.b=!1;this.h=this.a=null;this.A="";this.c=this.w=this.f=this.u=!1;this.D=0;this.g=null;this.J=
"";this.I=this.P=!1};_.q(le,_.I);_.h=le.prototype;_.h.Bb=function(){this.O();_.xa(de,this)};
_.h.send=function(a,b,c,d){if(this.a)throw Error("r`"+this.A+"`"+a);b=b?b.toUpperCase():"GET";this.A=a;this.u=!1;this.b=!0;this.a=this.j?fe(this.j):fe(_.Nd);this.h=this.j?ge(this.j):ge(_.Nd);this.a.onreadystatechange=(0,_.r)(this.fb,this);try{this.w=!0,this.a.open(b,String(a),!0),this.w=!1}catch(f){be(this);return}a=c||"";var e=this.N.clone();d&&_.Kc(d,function(a,b){e.set(b,a)});d=he(e.M());c=_.l.FormData&&a instanceof _.l.FormData;!(0<=(0,_.sa)(ee,b))||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");
e.forEach(function(a,b){this.a.setRequestHeader(b,a)},this);this.J&&(this.a.responseType=this.J);ie(this.a)&&(this.a.withCredentials=this.P);try{Sd(this),0<this.D&&((this.I=ce(this.a))?(this.a.timeout=this.D,this.a.ontimeout=(0,_.r)(this.jb,this)):this.g=_.O(this.jb,this.D,this)),this.f=!0,this.a.send(a),this.f=!1}catch(f){be(this)}};
_.h.jb=function(){"undefined"!=typeof _.ba&&this.a&&(_.L(this,"timeout"),this.a&&this.b&&(this.b=!1,this.c=!0,this.a.abort(),this.c=!1,_.L(this,"complete"),_.L(this,"abort"),Wd(this)))};_.h.v=function(){this.a&&(this.b&&(this.b=!1,this.c=!0,this.a.abort(),this.c=!1),Wd(this,!0));le.B.v.call(this)};_.h.fb=function(){this.L||(this.w||this.f||this.c?ae(this):this.Wb())};_.h.Wb=function(){ae(this)};
var me=function(a){var b=[];je(new ke,a,b);return b.join("")},ne=function(a,b){return a.b.get(b)},oe=function(){return Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^(0,_.m)()).toString(36)},pe=function(a){_.v(this,a,0,null)};_.q(pe,_.u);var qe=function(a){_.v(this,a,0,null)};_.q(qe,_.u);var re=function(a){_.v(this,a,0,null)};_.q(re,_.u);var se=function(a){_.v(this,a,0,null)};_.q(se,_.u);
var te=function(a){return null!=_.w(a,8)?_.w(a,8):"0"},ue=/[?&]($|#)/,ve=/#|$/,we=function(a,b,c,d){for(var e=c.length;0<=(b=a.indexOf(c,b))&&b<d;){var f=a.charCodeAt(b-1);if(38==f||63==f)if(f=a.charCodeAt(b+e),!f||61==f||38==f||35==f)return b;b+=e+1}return-1},xe=function(a){if(a&&"number"==typeof a.length){if(_.ia(a))return"function"==typeof a.item||"string"==typeof a.item;if(_.ja(a))return"function"==typeof a.item}return!1},ye={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",
frameborder:"frameBorder",height:"height",maxlength:"maxLength",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"},ze=/[\x00&<>"']/,Ae=/\x00/g,Be=/'/g,Ce=/"/g,De=/>/g,Ee=/</g,Fe=/&/g,Ge=function(a,b,c){function d(c){c&&b.appendChild(_.t(c)?a.createTextNode(c):c)}for(var e=2;e<c.length;e++){var f=c[e];!_.la(f)||_.ia(f)&&0<f.nodeType?d(f):(0,_.ta)(xe(f)?_.jd(f):f,d)}},He=function(a,b){_.za(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==
d?a.htmlFor=b:ye.hasOwnProperty(d)?a.setAttribute(ye[d],b):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,b):a[d]=b})},Ie=function(a){if(!ze.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(Fe,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(Ee,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(De,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(Ce,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(Be,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(Ae,"&#0;"));return a},Je=function(a,b,c){for(var d=
a.search(ve),e=0,f,g=[];0<=(f=we(a,e,b,d));)g.push(a.substring(e,f)),e=Math.min(a.indexOf("&",f)+1||d,d);g.push(a.substr(e));a=[g.join("").replace(ue,"$1"),"&",b];null!=c&&a.push("=",(0,window.encodeURIComponent)(String(c)));a[1]&&(c=a[0],b=c.indexOf("#"),0<=b&&(a.push(c.substr(b)),a[0]=c=c.substr(0,b)),b=c.indexOf("?"),0>b?a[1]="?":b==c.length-1&&(a[1]=void 0));return a.join("")},Ke=function(a){for(var b;b=a.firstChild;)a.removeChild(b)},Le=function(a,b){var c,d,e,f;c=window.document;c=b||c;if(c.querySelectorAll&&
c.querySelector&&a)return c.querySelectorAll(""+(a?"."+a:""));if(a&&c.getElementsByClassName){var g=c.getElementsByClassName(a);return g}g=c.getElementsByTagName("*");if(a){f={};for(d=e=0;c=g[d];d++){var k=c.className,p;if(p="function"==typeof k.split)p=0<=(0,_.sa)(k.split(/\s+/),a);p&&(f[e++]=c)}f.length=e;return f}return g},Me=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Arab|Hebr|Thaa|Nkoo|Tfng))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i,Ne=function(a,b,c){var d=arguments,e=window.document,f=d[0],
g=d[1];if(!_.cb&&g&&(g.name||g.type)){f=["<",f];g.name&&f.push(' name="',Ie(g.name),'"');if(g.type){f.push(' type="',Ie(g.type),'"');var k={};_.$c(k,g);delete k.type;g=k}f.push(">");f=f.join("")}f=e.createElement(f);g&&(_.t(g)?f.className=g:_.ma(g)?f.className=g.join(" "):He(f,g));2<d.length&&Ge(e,f,d);return f},Oe=function(a,b){var c=b||window.document,d=null;c.getElementsByClassName?d=c.getElementsByClassName(a)[0]:c.querySelectorAll&&c.querySelector?d=c.querySelector("."+a):d=Le(a,b)[0];return d||
null},Pe=function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(_.la(d)){var e=a.length||0,f=d.length||0;a.length=e+f;for(var g=0;g<f;g++)a[e+g]=d[g]}else a.push(d)}},Qe=function(a){var b=_.t(void 0)?"undefined".replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08"):"\\s";return a.replace(new RegExp("(^"+(b?"|["+b+"]+":"")+")([a-z])","g"),function(a,b,e){return b+e.toUpperCase()})},Re=function(a){return String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()})};
var Se=function(a){this.a=a;_.B||(delete this.a.lpu,delete this.a.ppu)},Te=["cn","tp"],Ue=function(a,b){var c=null,d;if(_.ja(window.document.postMessage)||_.ja(window.postMessage)||_.B&&window.postMessage)d=1;else if(_.Ra)d=2;else{if(c=_.B){c=!1;try{d=window.opener,window.opener={},c=_.eb(window,"opener"),window.opener=d}catch(e){}}d=c?6:4}c=d;d={};d.cn=Math.floor(2147483648*Math.random()).toString(36);d.tp=c;d.ifrid=b;d.pu=a;return new Se(d)};_.ga("GTalk_IFrameChannelConfig.build",Ue);
var Ve=function(){if(Oe("talk_loading_msg")){var a=Oe("talk_loading_msg_error");a&&_.Lc(a)}},We=function(a){var b=Oe("talk_loading_msg");if(b){Ve();var c=window.document.createElement("DIV");He(c,{"class":"talk_loading_msg_error",style:"margin: 12px 8px; font-size: 10px"});var d=window.document.createElement("DIV");a="Errors: "+a.join(", ");if("textContent"in d)d.textContent=a;else if(3==d.nodeType)d.data=a;else if(d.firstChild&&3==d.firstChild.nodeType){for(;d.lastChild!=d.firstChild;)d.removeChild(d.lastChild); d.firstChild.data=a}else Ke(d),d.appendChild((9==d.nodeType?d:d.ownerDocument||d.document).createTextNode(String(a)));c.appendChild(d);b.appendChild(c)}};
var Xe=function(){},$e=function(a){var b=a.da,c=function(a){c.B.constructor.call(this,a);var b=this.R.length;this.a=[];for(var d=0;d<b;++d)this.R[d].rc||(this.a[d]=new this.R[d](a))};_.q(c,b);for(var d=[];a;){if(b=a.da){b.R&&Pe(d,b.R);var e=b.prototype,f;for(f in e)if(e.hasOwnProperty(f)&&_.ja(e[f])&&e[f]!==b){var g=!!e[f].xb,k=Ye(f,e,d,g);(g=Ze(f,e,k,g))&&(c.prototype[f]=g)}}a=a.B&&a.B.constructor}c.prototype.R=d;return c},Ye=function(a,b,c,d){for(var e=[],f=0;f<c.length&&(c[f].prototype[a]===b[a]||
(e.push(f),!d));++f);return e},Ze=function(a,b,c,d){var e;c.length?d?e=function(b){var d=this.a[c[0]];return d?d[a].apply(this.a[c[0]],arguments):this.R[c[0]].prototype[a].apply(this,arguments)}:b[a].zb?e=function(b){var d;a:{d=Array.prototype.slice.call(arguments,0);for(var e=0;e<c.length;++e){var p=this.a[c[e]];if(p=p?p[a].apply(p,d):this.R[c[e]].prototype[a].apply(this,d)){d=p;break a}}d=!1}return d}:b[a].yb?e=function(b){var d;a:{d=Array.prototype.slice.call(arguments,0);for(var e=0;e<c.length;++e){var p=
this.a[c[e]],p=p?p[a].apply(p,d):this.R[c[e]].prototype[a].apply(this,d);if(null!=p){d=p;break a}}d=void 0}return d}:b[a].Mb?e=function(b){for(var d=Array.prototype.slice.call(arguments,0),e=0;e<c.length;++e){var p=this.a[c[e]];p?p[a].apply(p,d):this.R[c[e]].prototype[a].apply(this,d)}}:e=function(b){for(var d=Array.prototype.slice.call(arguments,0),e=[],p=0;p<c.length;++p){var A=this.a[c[p]];e.push(A?A[a].apply(A,d):this.R[c[p]].prototype[a].apply(this,d))}return e}:d||b[a].zb||b[a].yb||b[a].Mb? e=null:e=af;return e},af=function(){return[]};Xe.prototype.f=function(a){if(this.a)for(var b=0;b<this.a.length;++b)if(this.a[b]instanceof a)return this.a[b];return null};var bf=function(a){(a?a:function(){}).xb=!0};
var cf=function(){};_.q(cf,Xe);cf.prototype.b=function(a){return a};bf(cf.prototype.b);cf.prototype.c=function(){return!0};bf(cf.prototype.c);var df=function(a){_.v(this,a,0,null)};_.q(df,_.u);var ef=function(a,b){var c=new df;_.K(c,1,b);_.K(c,2,a);return c},ff=ef("?",0),gf=ef("q",1),hf=ef("<",2),jf=ef(">",3),kf=ef("~",4),lf=ef("s",5),mf={f:ff,u:gf,h:hf,j:jf,g:kf,w:lf};var nf=function(a){_.v(this,a,"ci:dc",null)};_.q(nf,_.u);_.x("ci:dc",nf);var of=function(a){_.v(this,a,"ci:ec",null)};_.q(of,_.u);_.x("ci:ec",of);var pf=function(a){return null!=_.w(a,2)?_.w(a,2):!1};var qf=function(a){return this.za.f(a)};var rf=function(a){this.a=a},sf=/\s*;\s*/;_.h=rf.prototype;_.h.set=function(a,b,c,d,e,f){if(/[;=\s]/.test(a))throw Error("s`"+a);if(/[;\r\n]/.test(b))throw Error("t`"+b);_.n(c)||(c=-1);e=e?";domain="+e:"";d=d?";path="+d:"";f=f?";secure":"";c=0>c?"":0==c?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date((0,_.m)()+1E3*c)).toUTCString();this.a.cookie=a+"="+b+e+d+c+f};
_.h.get=function(a,b){for(var c=a+"=",d=(this.a.cookie||"").split(sf),e=0,f;f=d[e];e++){if(0==f.lastIndexOf(c,0))return f.substr(c.length);if(f==a)return""}return b};_.h.remove=function(a,b,c){var d=_.n(this.get(a));this.set(a,"",0,b,c);return d};_.h.M=function(){return tf(this).keys};_.h.G=function(){return tf(this).values};_.h.aa=function(){return!this.a.cookie};_.h.ea=function(){return this.a.cookie?(this.a.cookie||"").split(sf).length:0};
_.h.clear=function(){for(var a=tf(this).keys,b=a.length-1;0<=b;b--)this.remove(a[b])};var tf=function(a){a=(a.a.cookie||"").split(sf);for(var b=[],c=[],d,e,f=0;e=a[f];f++)d=e.indexOf("="),-1==d?(b.push(""),c.push(e)):(b.push(e.substring(0,d)),c.push(e.substring(d+1)));return{keys:b,values:c}};
var uf=function(a,b,c){if(!this.za){for(var d=this.constructor;d&&!d.da;)d=d.B&&d.B.constructor;d.da.$a||(d.da.$a=$e(d));this.za=new d.da.$a(this);this.f||(this.f=qf)}var e=this.za.b(a.clientBaseUrl||"https://talkgadget.google.com/talkgadget/");if(0==e.lastIndexOf("https://talkgadget.google.com/talkgadget/",0)){var d=(new rf(window.document)).get("WCSDBG",""),d=d.split(";")[0],d=d.split("|")[0],f=["plus.google.com"],g=/^[-_a-zA-Z0-9\.]+\.talkgadget\.google\.com$/;0<d.length&&!(0<=(0,_.sa)(f,d))&&
g.test(d)&&(e=_.Ad(e),e=_.Ad("https://"+d+e.a).toString())}this.X=e;this.c=c||new of;a.notificationsOnly&&_.K(this.c,1,!0);this.b="0";null!=a.authUser?this.b=a.authUser:(c=ne(new _.wd(window.location.href),"authuser"),null!=c&&(this.b=c));this.l=a.clientUrl||"notifierclient";c=ne(_.Ad(this.l),"authuser");null!=c&&(this.b=c);this.u=a.propertyName||"Google Talk";this.C=a.cssUrl;this.locale=a.locale;this.h=a.debug;this.Fa=a.userJid;this.Sa=a.uiVersion;this.Jb=null!=a.rosterExpanded?a.rosterExpanded:
!0;this.Ha=a.hostLogMinValue;this.Pa=a.hideChat;this.Eb=a.refresh;this.P=a.hideProfileCard;this.Ga=a.hideStatusMsgs;this.W=a.hideRosterOptions;this.V=a.hideRecentConversations;this.N=a.hideOTR;this.vb=a.hostServerMessageCallback||!1;this.Ja=a.isCentralRoster;this.Db=a.isFullFrame||!1;this.Ib=a.rosterClass||"talk_roster";this.Oa=a.rosterId||"talk_roster";this.a="gtn-roster-iframe-id";a.rosterFrameId&&a.rosterFrameId.match(/[\w-]/)&&(this.a=a.rosterFrameId);a.rosterIframeIdB&&a.rosterIframeIdB.match(/[\w-]/);
this.g=a.parentToken;this.Hb=b||!1;_.n(a.isRtl)||Me.test(this.locale);this.j=a.position||"l";if(!a.keyboardShortcuts){b=[];for(var k in mf)b.push(mf[k].H)}this.I=a.entityId;this.Ta=a.useQuasarPanels||!1;this.Qa=a.silent||!1;this.wb=a.ignoreCentralRoster||!1;this.Fb=a.lazy||!1;this.mb=a.handleProfileLinks||!1;this.Ia=a.hostSettings;this.w=a.screen;this.D=a.docsConfig;this.Ka=a.jsmode;this.Na=a.moleWidth;this.Ma=a.moleHeight;this.La=a.minimizedMoleHeight||36;this.Kb=a.derp;this.Ra=window.location.protocol+
"//"+window.location.host;this.K=a.optOutAllowed;this.J=a.legacyTalkSignedIn;this.Ua=a.useSpareMole;this.A=a.conversationId};cf.B||_.q(cf,Xe);uf.da=cf;
var vf=function(a){switch(a){case 1:return"homepage";case 4:return"Google Translator Toolkit";case 5:return"Google Sites";case 6:return"customersupport";case 9:return"present";case 15:return"hangout";case 18:return"gmail";case 20:return"docs";case 24:return"docs_hangout";case 22:return"hangout_lite";case 23:return"aChromeExtension";case 25:return"bigtop";case 27:return"ChromeApp";case 36:return"StartPage"}};
var wf=function(a,b,c,d,e){_.C.call(this);this.a=a;this.b=d||window.document;this.c=new _.H(this);_.F(this,this.c);var f=_.Ha;d=new _.wd(a.X+a.l);pf(a.c)||(_.N(d,"ts","0"),_.N(d,"re",a.Jb),_.N(d,"ref",a.Eb));_.N(d,"client","sm");_.N(d,"prop",a.u);_.N(d,"nav","true");_.N(d,"fid",a.a);a.h&&_.N(d,"debug",a.h);_.N(d,"os",_.Ua);_.N(d,"stime",c);a.Pa&&_.N(d,"hc",a.Pa);for(c=0;c<Te.length;++c);b=me(b.a);_.N(d,"xpc",b);_.N(d,"ec",me(a.c.H));a.w&&_.N(d,"screen",a.w);-1!=f.indexOf("MSIE")&&_.N(d,"ua",f);a.g&&
_.N(d,"pvt",a.g);a.vb&&_.N(d,"hsmc","true");_.n(a.Ha)&&_.N(d,"logl",a.Ha);b=window.location.href;0>b.indexOf("?rel=1")&&(b=b.split("?"),b[1]=1==b.length?"rel=1":["rel=1&",b[1]].join(""),_.N(d,"href",b.join("?")));b=new _.wd(window.location.href);"false"==ne(b,"uacheck")&&_.N(d,"uacheck",!1);(f=a.Ka)&&_.N(d,"jsmode",f);(f=ne(b,"cssmode"))&&_.N(d,"cssmode",f);(f=ne(b,"convid"))&&_.N(d,"convid",f);if(f=b.b.G("convp"))_.ma(f)||(f=[String(f)]),_.od(d.b,"convp",f);(f=ne(b,"smexp"))&&_.N(d,"smexp",f);f=
b.b.G("mods");a.Fb&&f.push("lazy");e&&(f=_.kd(f,e));0<f.length&&_.N(d,"mods",f.join(","));if(!a.X||0>a.X.indexOf("/u/"))(e=ne(b,"authuser"))?_.N(d,"authuser",e):null!=a.b&&_.N(d,"authuser",a.b);e=ne(b,"eid");/^[\s\xa0]*$/.test(null==e?"":String(e))||_.N(d,"eid",e);e=this.a.I;/^[\s\xa0]*$/.test(null==e?"":String(e))||_.N(d,"eid",this.a.I);null!=this.a.j&&_.N(d,"pos",this.a.j);_.n(a.Sa)&&_.N(d,"uiv",this.a.Sa);a.C&&_.N(d,"css",a.C);e=a.locale||ne(b,"hl");null!=e&&_.N(d,"hl",e);_.n(a.Fa)&&_.N(d,"uj",
a.Fa);null!=a.P&&_.N(d,"hpc",a.P);null!=a.Ga&&_.N(d,"hsm",a.Ga);null!=a.W&&_.N(d,"hro",a.W);null!=a.V&&_.N(d,"hrc",a.V);null!=a.N&&_.N(d,"hotr",a.N);null!=a.Ja&&_.N(d,"pop",a.Ja);a.Hb&&_.N(d,"pal","1");null!=a.Ta&&_.N(d,"uqp",a.Ta);null!=a.K&&_.N(d,"gooa",a.K);null!=a.J&&_.N(d,"gltsi",a.J);null!=a.Ua&&_.N(d,"gusm",a.Ua);null!=a.Qa&&_.N(d,"sl",a.Qa);a.wb&&_.N(d,"icr","1");a.mb&&_.N(d,"hpl","1");a.Ia&&_.N(d,"hs",a.Ia);a.D&&_.N(d,"dc",me(a.D.H));null!=a.Na&&_.N(d,"molew",a.Na);null!=a.Ma&&_.N(d,"moleh",
a.Ma);null!=a.La&&_.N(d,"mmoleh",a.La);a.Kb&&_.N(d,"derp","1");null!=a.Ra&&_.N(d,"two",a.Ra);null!=a.A&&_.N(d,"convid",a.A);_.N(d,"host","1");_.N(d,"zx",oe());this.f=d.toString()};_.q(wf,_.C);
var xf=function(a,b,c,d){var e=a.b.getElementById(b);e||(e=a.b.createElement("div"),e.id=b,e.className=a.a.Ib,a.b.body.appendChild(e));a=(0,_.r)(function(){var a="";this.a.Db||(a="height:400px");var b=this.b.createElement("iframe");He(b,{id:this.a.a,name:this.a.a,"class":"talk_iframe",frameborder:"0",style:a});Oe("talk_loading_msg",e)||Ke(e);e.appendChild(b);var k=this.b.getElementById(this.a.a);_.cd(this.c,k,["load","error"],function(a){k.contentWindow.postMessage("AllowFrame: Chat","*");d(a)}); k.src=this.f.toString();c()},a);window.setTimeout(a,0)};
var yf=function(a){_.hb.call(this,a[0]);this.sa=a};_.q(yf,_.hb);var zf=function(a){_.v(this,a,"h_ccf",null)};_.q(zf,_.u);_.x("h_ccf",zf);var Af=function(a){_.v(this,a,"h_rtp",null)};_.q(Af,_.u);_.x("h_rtp",Af);var Cf=function(a,b,c){var d=Bf[c];if(!d){var e=Re(c),d=e;void 0===a.style[e]&&(e=(_.Sa?"Webkit":_.Ra?"Moz":_.B?"ms":_.Pa?"O":null)+Qe(e),void 0!==a.style[e]&&(d=e));Bf[c]=d}(c=d)&&(a.style[c]=b)},Bf={},Df=function(a){"number"==typeof a&&(a=Math.round(a)+"px");return a};
var P=function(a,b){_.C.call(this);this.P=(0,_.m)();this.N=a;this.document=b||window.document;this.a=new uf(a,!0,a.endpointConfig);this.j=[];this.D=new _.I;this.h=null};_.q(P,_.C);P.prototype.v=function(){P.B.v.call(this);_.Fd(this.h);this.b&&this.A&&this.b.parentNode.removeEventListener("DOMAttrModified",this.A,!0)};P.prototype.f=function(a,b){this.c?this.c[a]&&this.c[a].apply(this.c,Array.prototype.slice.call(arguments,1)):this.j.push(arguments)};
P.prototype.u=function(){var a=(this.document.parentWindow||this.document.defaultView).GTalkNotifier;if(a){var b=this.N,c={},d;for(d in b)c[d]=b[d];c.endpointConfig=this.a.c.H;this.c=new a(c,!0);for(a=0;a<this.j.length;a++)this.f.apply(this,this.j[a]);this.j=[];a=(0,_.r)(this.onMessage,this);this.f("_addClientMessageCallback",a);this.f("_addHostBundleMessageCallback",a)}};P.prototype.onMessage=function(a){switch(a[0]){case "h_ccf":var b=new zf(a);_.w(b,1)}_.L(this.D,new yf(a))};
var Ef=function(a,b){a.f("_h",b.H)};P.prototype.sendMessage=function(a){Ef(this,a)};P.prototype.g=function(){return this.D};P.prototype.V=function(a,b){if(b.target==a&&("style"==b.attrName||"class"==b.attrName)){var c=new Af;Ef(this,c)}};
P.prototype.W=function(){if(Oe("talk_loading_msg",this.document.getElementById(this.a.Oa))){var a=this.document.getElementById(this.a.a),b=0,c;"undefined"!=typeof _.Ff&&b instanceof _.Ff?(c=b.height,b=b.width):c=0;a.style.width=Df(b);a.style.height=Df(c);if(_.t("overflow"))Cf(a,"hidden","overflow");else for(var d in"overflow")Cf(a,"overflow"[d],d);a.style.display=""}};
var Gf=function(a){var b=a.a.X+"host-js",b=Je(b,"prop",a.a.u),c=a.a.Ka;c&&(b=Je(b,"jsmode",c));pf(a.a.c)&&(b=Je(b,"b","1"));var b=Je(b,"zx",oe()),d=(0,_.r)(a.u,a),e=Ne("script",{type:"text/javascript",src:b}),f=!1;e.onload=e.onreadystatechange=function(){f||e.readyState&&"loaded"!=e.readyState&&"complete"!=e.readyState||(f=!0,d())};e.onerror=(0,_.r)(a.I,a,e);a.h&&(_.Fd(a.h),a.h=null);a.h=_.O((0,_.r)(function(){null!=this.c||this.J(e)},a),25E3);a.document.body.appendChild(e)};P.prototype.I=function(){}; P.prototype.J=function(){};
var Hf=function(a){if(a.classList)return a.classList;a=a.className;return _.t(a)&&a.match(/\S+/g)||[]},If=function(a){a.classList?a=a.classList.contains("talk_network_warning"):(a=Hf(a),a=0<=(0,_.sa)(a,"talk_network_warning"));return a},Jf=function(a){a.classList?a.classList.remove("talk_network_warning"):If(a)&&(a.className=(0,_.ua)(Hf(a),function(a){return"talk_network_warning"!=a}).join(" "))};
var Kf=function(a,b,c,d){this.c=a;this.l=b;this.a=this.b=a;this.f=c||0;this.g=d||2};Kf.prototype.reset=function(){this.a=this.b=this.c};Kf.prototype.F=function(){return this.b};var Lf=function(a){a.a=Math.min(a.l,a.a*a.g);a.b=Math.min(a.l,a.a+(a.f?Math.round(a.f*(Math.random()-.5)*2*a.a):0))};
var Mf=function(a,b,c){var d={},e;e=null!=_.w(a,1)?_.w(a,1):"hangouts.google.com";var f="";0>e.indexOf("://")&&(f="https://",0<=e.indexOf(":")&&23!=_.w(a,2)&&27!=_.w(a,2)&&(f="http://"));-1!=e.indexOf("talkgadget.")?(d.clientBaseUrl=f+e+"/talkgadget/_/",d.clientUrl="chat"):(d.clientBaseUrl=f+e+"/webchat/u/"+te(a)+"/",d.clientUrl="load");d.authUser=te(a);d.propertyName=vf(_.w(a,2));d.locale=_.w(a,4);d.hideProfileCard=!0;d.parentToken=_.w(a,3);e=null!=_.w(a,6)?_.w(a,6):!1;d.isRtl=e;e=null!=_.w(a,7)?
_.w(a,7):!1;d.lazy=e;d.entityId=_.w(a,9);d.hostSettings=_.w(a,5);d.jsmode=_.w(a,11);e=null!=_.w(a,13)?_.w(a,13):!1;d.isFullFrame=e;e=null!=_.w(a,12)?_.w(a,12):"talk_roster";d.rosterId=e;e=null!=_.w(a,15)?_.w(a,15):"gtn-roster-iframe-id-b";d.rosterIframeIdB=e;e=null!=_.w(a,16)?_.w(a,16):!1;d.derp=!!e;e=_.ed(a,pe,14);null!=e&&(f=null!=_.w(e,1)?_.w(e,1):!1,d.isCentralRoster=f,e=null!=_.w(e,2)?_.w(e,2):!1,d.useQuasarPanels=e);e=_.ed(a,se,10);null!=e&&(d.moleManagerLeftMargin=_.w(e,1),d.moleManagerMiddleMargin=
_.w(e,2),d.moleManagerRightMargin=_.w(e,3),d.moleManagerNoMoleAreaMargin=_.w(e,4),d.moleManagerBoundingElementId=_.w(e,5),d.moleWidth=_.w(e,6),d.moleHeight=_.w(e,7),d.minimizedMoleHeight=_.w(e,8));e=_.ed(a,re,18);null!=e&&(f=null!=_.w(e,1)?_.w(e,1):!0,d.optOutAllowed=f,f=_.ed(e,qe,3),null!=f&&(f=null!=_.w(f,1)?_.w(f,1):!0,d.legacyTalkSignedIn=f),e=_.w(e,4),null!=e&&(d.useSpareMole=e));d.uiVersion=2;d.hideStatusMsgs=!0;d.hideRecentConversations=!0;e=new of;_.K(e,2,!0);_.K(e,1,!0);_.K(e,3,!1);d.endpointConfig=
e;e=null!=_.w(a,17)?_.w(a,17):!1;d.ignoreAutomatedRoster=e;d.conversationId=a.T();d.hostCallback=c;P.call(this,d,b);this.C=new Kf(5E3,3E5);this.K=null};_.q(Mf,P);var Nf=function(a,b){var c=1+.5*Math.random();a.K=_.O(function(){null==this.c&&(_.Cd(this.document.body,b)&&this.document.body.removeChild(b),Gf(this))},a.C.F()*c,a);Lf(a.C)};Mf.prototype.J=function(a){We(["301"]);Nf(this,a)};
Mf.prototype.I=function(a){var b=Oe("talk_loading_msg",this.document.body);b&&(b.classList?b.classList.add("talk_network_warning"):If(b)||(b.className+=0<b.className.length?" talk_network_warning":"talk_network_warning"));We(["302"]);Nf(this,a)};Mf.prototype.u=function(){Mf.B.u.call(this);var a=Oe("talk_loading_msg",this.document.body);a&&Jf(a);Ve()};Mf.prototype.v=function(){Mf.B.v.call(this);_.Fd(this.K)};
var Of=function(a){_.I.call(this);this.c=a?a:null;this.a=null;this.f=!1;this.b=[];this.g=(0,_.r)(this.nb,this);this.h=(0,_.r)(this.Va,this);this.j=null};_.q(Of,_.I);var Pf=function(a){_.hb.call(this,"message");this.message=a};_.q(Pf,_.hb);_.h=Of.prototype;_.h.v=function(){Of.B.v.call(this);_.Fd(this.j);this.Va(!0);for(var a=0;a<this.b.length;++a)_.D(this.b[a]);delete this.b;delete this.g;delete this.h};
_.h.sendMessage=function(a){if(null==a||null==a.message)return!1;_.uc(a,this.c,"p");this.a&&this.f?this.a.postMessage(a.message()):this.b.push(a);return!0};_.h.connect=function(){if(null==this.c)return!1;try{if(this.a=window.chrome.runtime.connect({name:this.c}),null==this.a)return!1}catch(b){return!1}this.f=!0;this.a.onMessage.addListener(this.g);this.a.onDisconnect.addListener(this.h);for(var a=this.b.shift();null!=a;)_.uc(a,this.c,"p"),this.a.postMessage(a.message()),a=this.b.shift();return!0};
_.h.nb=function(a){_.L(this,new Pf(_.tc(new _.J,a)))};_.h.Va=function(a){this.a&&(this.a.onMessage.removeListener(this.g),this.a.onDisconnect.removeListener(this.h),this.a.disconnect(),delete this.a);this.f=!1;a||(this.j=_.O(this.bc,5E3,this))};_.h.bc=function(){this.connect()?_.L(this,{type:"reconnected"}):_.L(this,{type:"disconnected"})};
var Rf=function(a){_.v(this,a,"h_exts",Qf)};_.q(Rf,_.u);var Qf=[2];_.x("h_exts",Rf);var Sf=function(){_.C.call(this);this.b=" "};_.q(Sf,_.C);var Tf=function(a,b,c){a.a=c;b=_.Bd(b,"/webchat/extension-start");a=(0,_.r)(a.c,a);c=new le;de.push(c);a&&c.listen("complete",a);_.qb(c.S,"ready",c.Bb,!0,void 0,void 0);c.send(b,void 0,void 0,void 0)};Sf.prototype.c=function(a){if(!this.L){this.b="";if(Vd(a.target))try{var b;var c=a.target;try{b=c.a?c.a.responseText:""}catch(f){b=""}var d=JSON.parse(b),e=new Rf(d);this.b=_.w(e,1)||""}catch(f){}this.a&&(this.a(),this.a=null)}};
var Uf=function(a){_.v(this,a,"h_cp",null)};_.q(Uf,_.u);_.x("h_cp",Uf);var Vf=function(a){_.v(this,a,"rbc_d",null)};_.q(Vf,_.u);_.x("rbc_d",Vf);Vf.prototype.setTitle=function(a){_.K(this,1,a)};var Xf=function(a){_.v(this,a,"h_cd",Wf)};_.q(Xf,_.u);var Wf=[1,4,5];_.x("h_cd",Xf);Xf.prototype.T=function(){return _.w(this,2)};var Yf=function(a){_.v(this,a,"h_hn",null)};_.q(Yf,_.u);_.x("h_hn",Yf);var Zf=function(a){_.v(this,a,"h_hs",null)};_.q(Zf,_.u);_.x("h_hs",Zf);var ag=function(a){_.v(this,a,"h_jm",$f)};_.q(ag,_.u);var $f=[2];_.x("h_jm",ag);var bg=function(a){_.v(this,a,"h_oc",null)};_.q(bg,_.u);_.x("h_oc",bg);var cg=function(a){_.v(this,a,"h_opc",null)};_.q(cg,_.u);_.x("h_opc",cg);var dg=function(a){_.v(this,a,"h_ogc",null)};_.q(dg,_.u);_.x("h_ogc",dg);var eg=function(a){_.v(this,a,"h_sc",null)};_.q(eg,_.u);_.x("h_sc",eg);var gg=function(a){_.v(this,a,"h_ssc",fg)};_.q(gg,_.u);var fg=[5];_.x("h_ssc",gg);var ig=function(a){_.v(this,a,"h_sm",hg)};_.q(ig,_.u);var hg=[1,3];_.x("h_sm",ig);var jg=function(a){_.v(this,a,"h_po",null)};_.q(jg,_.u);_.x("h_po",jg);var kg=function(a){_.I.call(this);this.a=a};_.q(kg,_.I);var lg=new _.G("O9EQob");var mg=function(a){_.v(this,a,"h_cs",null)};_.q(mg,_.u);_.x("h_cs",mg);mg.prototype.getState=function(){return _.w(this,1)};var og=function(a){_.I.call(this);this.f=a;this.b=ng.LOADING;this.a=!1;this.c=new _.H(this);_.F(this,this.c);this.c.listen(this.f.g(),"h_cs",this.g)};_.q(og,_.I);var ng={LOADING:0,lb:1,oc:2,pc:3,ERROR:4,LOADED:5,kb:6},pg=new _.G("HwdKC");og.prototype.getState=function(){return this.b};og.prototype.h=function(){return this.a};og.prototype.g=function(a){a=new mg(a.sa);var b=a.getState();null!=b&&this.b!=b&&(this.b=b,_.L(this,"e"));a=_.w(a,2);null!=a&&this.a!=a&&(this.a=a,_.L(this,"d"))};
var qg=function(a){_.v(this,a,"capii_c_cel",null)};_.q(qg,_.u);_.x("capii_c_cel",qg);var rg=function(a){_.v(this,a,"capi:rfc",null)};_.q(rg,_.u);_.x("capi:rfc",rg);var sg=function(a){_.v(this,a,"capii_c_ucmc",null)};_.q(sg,_.u);_.x("capii_c_ucmc",sg);var tg=function(a){_.v(this,a,"capii_c_rc",null)};_.q(tg,_.u);_.x("capii_c_rc",tg);tg.prototype.T=function(){return _.w(this,1)};
var ug=new _.G("nED8Yb"),vg=new _.G("xclgJb");var wg=function(a){_.I.call(this);this.c=a.get(ug);this.a=this.g=0;this.f=this.b=!1;a=new _.H(this);_.F(this,a);a.listen(this.c.g(),"capii_c_ucmc",this.h);this.c.sendMessage(new sg)};_.q(wg,_.I);wg.prototype.h=function(a){a=new sg(a.sa);this.b||(this.b=!0,this.f&&(_.K(a,5,!0),this.f=!1));var b=this.g!=_.w(a,1);this.g=Number(_.w(a,1));var c=this.a!=_.w(a,2);this.a=Number(_.w(a,2));_.w(a,5)?_.L(this,"f"):(b&&_.L(this,"h"),c&&_.L(this,"g"))};
var xg=function(a){_.v(this,a,"h_rha",null)};_.q(xg,_.u);_.x("h_rha",xg);var yg=function(a){_.v(this,a,"h_ssf",null)};_.q(yg,_.u);_.x("h_ssf",yg);var zg=function(a,b){_.C.call(this);this.a=new _.H(this);_.F(this,this.a);this.a.listen(a.g(),"h_ssf",function(a){a=new yg(a.sa);a=_.w(a,1);var c;if(null!=a&&JSON&&JSON.parse)try{c=JSON.parse(a)}catch(f){}b(c)});var c=new xg;_.K(c,1,1);Ef(a,c)};_.q(zg,_.C);
var Ag=function(a){_.v(this,a,"h_ext",null)};_.q(Ag,_.u);_.x("h_ext",Ag);var Bg=function(a){_.v(this,a,"h_sru",null)};_.q(Bg,_.u);_.x("h_sru",Bg);var Eg=function(){_.H.call(this);this.b=new _.Rc;_.F(this,this.b);this.u=this.h=this.j=this.a=null;this.C=_.rc("quasar",""+(new Date).getTime());this.c=[];this.g=new Of(this.C);_.F(this,this.g);this.w=null;this.g.connect();_.Kb(this,this.g,"message",this.P,!0,this);this.A=new Sf;_.F(this,this.A);this.listen(window,"unload",this.O);this.listen(window,"load",this.J);Cg(this,(0,_.r)(function(){Dg(this,["onHostReady"],"extensionLibrary")},this))},Fg;_.q(Eg,_.H);var Cg=function(a,b){null==a.c?b():a.c.push(b)};
Eg.prototype.J=function(){var a=new _.zc(_.Cc.fa().get("settings"));this.w=_.ad(a);_.D(a);Tf(this.A,this.w,(0,_.r)(function(){if(!this.L){var a=new of;_.K(a,2,!0);var a=new _.Ib,c=this.A.b;if(c){_.K(a,3,c);var c=_.Ad(this.w),d=c.c;null!=c.l&&(d+=":"+c.l);_.K(a,1,d);_.K(a,2,23);d=window.chrome.i18n.getMessage("@@ui_locale");_.K(a,4,d);_.K(a,13,!0);_.K(a,17,!0);c=ne(c,"jsmode");null!=c&&_.K(a,11,c);c=new pe;_.K(c,2,!0);_.K(c,1,!0);_.dd(a,14,c);a=new Mf(a,void 0,(0,_.r)(this.N,this));_.t(void 0)&&(a.a.g=
void 0);c=a.a;var e=a.a.X,d=a.a.b;if(-1!=e.indexOf("talkgadget.")){var f=_.Ad(e),g=f.a;if(0<=g.indexOf("/u/"))d=e;else{e=g.lastIndexOf("_/");if(0>e||e!=g.length-2)g+="_/";f.a="/u/"+d+g;d=f.toString()}}else d=e;c.X=d;a.a.l=a.a.l.replace("notifierclient","chat");a.w||(c=Ue(a.a.X,a.a.a),a.w=new wf(a.a,c,a.P,a.document,void 0),_.F(a,a.w));xf(a.w,a.a.Oa,(0,_.r)(a.W,a),(0,_.r)(a.f,a,"_rosterIframeLoaded"));_.Gd&&(a.b=a.document.createElement("IFRAME"),a.b.id="gth-talk-plugin-frame-id",a.b.name="gth-talk-plugin-frame-id",
a.b.src=a.a.X+"blank",a.b.style.cssText="width: 0px; height: 0px; position: absolute; top: 0px; left: 0px; visibility:hidden;",a.document.documentElement.appendChild(a.b),a.A=(0,_.r)(a.V,a,a.b.parentNode),a.b.parentNode.addEventListener("DOMAttrModified",a.A,!0));Gf(a);this.a=a;this.b.a(ug,this.a);this.j=new og(this.a);this.b.a(pg,this.j);this.listen(this.j,"e",this.K);this.h=new kg(this.a);this.b.a(lg,this.h);this.u=new wg(this.b);this.b.a(vg,this.u);this.listen(this.u,"g",this.D);this.D();a=new zg(this.a,
(0,_.r)(this.V,this));_.F(this,a);this.listen(this.a.g(),"h_sru",this.W)}else Dg(this,["changeDesktop",3],"desktopManager")}for(;this.c.length;)this.c.shift()();this.c=null},this))};Eg.prototype.N=function(a,b){if("extensionMessage"==a)if("__reload__"==b)window.chrome.runtime.reload();else{var c=new _.J,d={};try{d=JSON.parse(b)||{}}catch(e){}_.tc(c,d);this.g.sendMessage(c)}};
Eg.prototype.K=function(){var a;switch(this.j.getState()){case ng.LOADING:a=2;break;case ng.lb:a=4;break;case ng.kb:a=3;break;default:return}Dg(this,["changeDesktop",a],"desktopManager")};
Eg.prototype.P=function(a){Cg(this,(0,_.r)(function(){var b=a.message;switch(b.c){case "onSendHostMessage":var c=new Ag;_.K(c,1,b.b.toString());this.a&&this.a.sendMessage(c);break;case "onOpenConversation":var c=this.h,b=b.b[0],d=new bg;_.K(d,1,b);Ef(c.a,d);d=new Xf;_.K(d,1,[b]);b=new cg;_.dd(b,1,d);Ef(c.a,b);break;case "h_icr":c=b.b[0],this.h&&(b=this.h,d=new _.Pd,_.K(d,1,c),Ef(b.a,d))}},this))};
var Dg=function(a,b,c){var d=new _.J;_.uc(d,a.C,"p");_.bd(d,"","e");_.wc(d,b);null!=c&&(d.h=c);_.vc(d,""+(0,_.m)());a.g.sendMessage(d)};Eg.prototype.V=function(){var a=_.Qd();window.open(a)};Eg.prototype.W=function(a){a=new Bg(a.sa);Dg(this,["setRosterUrl",_.w(a,2)],"dataChannelManager")};Eg.prototype.D=function(){Dg(this,["setUnreadIndicator",!!this.u.a],"desktopManager")};
if(!_.n(Fg)||null==Fg||Fg.L)Fg=new Eg;
}catch(e){_._DumpException(e)}
}).call(this,this.default_datachannel);
// Google Inc.
