"use strict";this.default_extension=this.default_extension||{};(function(_){var window=this;
try{
_.ba=_.ba||{};_.l=this;_.ca="closure_uid_"+(1E9*Math.random()>>>0);_.m=Date.now||function(){return+new Date};
}catch(e){_._DumpException(e)}
try{
var da,ea,fa;_.n=function(a){return void 0!==a};da=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};ea=function(a,b,c){return a.call.apply(a.bind,arguments)};
fa=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};_.q=function(a,b){function c(){}c.prototype=b.prototype;a.B=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.qc=function(a,c,f){for(var g=Array(arguments.length-2),k=2;k<arguments.length;k++)g[k-2]=arguments[k];return b.prototype[c].apply(a,g)}};
_.ga=function(a,b){var c=a.split("."),d=_.l;c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&_.n(b)?d[e]=b:d[e]?d=d[e]:d=d[e]={}};_.ha=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}};_.r=function(a,b,c){_.r=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ea:da;return _.r.apply(null,arguments)};
_.ia=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};_.ja=function(a){return"function"==fa(a)};_.ka=function(a){return"number"==typeof a};_.t=function(a){return"string"==typeof a};_.la=function(a){var b=fa(a);return"array"==b||"object"==b&&"number"==typeof a.length};_.ma=function(a){return"array"==fa(a)};_.na=function(){};_.oa=function(a,b){for(var c=a.split("."),d=b||_.l,e;e=c.shift();)if(null!=d[e])d=d[e];else return null;return d}; _.pa=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,_.pa);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))};_.q(_.pa,Error);_.pa.prototype.name="CustomError";
var qa=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},ra=function(a,b){return a<b?-1:a>b?1:0};_.sa=Array.prototype.indexOf?function(a,b,c){return Array.prototype.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(_.t(a))return _.t(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};_.ta=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.t(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)};
_.ua=Array.prototype.filter?function(a,b,c){return Array.prototype.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,g=_.t(a)?a.split(""):a,k=0;k<d;k++)if(k in g){var p=g[k];b.call(c,p,k,a)&&(e[f++]=p)}return e};_.va=Array.prototype.map?function(a,b,c){return Array.prototype.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=_.t(a)?a.split(""):a,g=0;g<d;g++)g in f&&(e[g]=b.call(c,f[g],g,a));return e};
_.wa=Array.prototype.some?function(a,b,c){return Array.prototype.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.t(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return!0;return!1};_.xa=function(a,b){var c=(0,_.sa)(a,b),d;(d=0<=c)&&Array.prototype.splice.call(a,c,1);return d};
_.ya=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;var Aa;_.za=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)};Aa=function(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b};_.Ba=function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b};var Da;_.u=function(){};_.v=function(a,b,c,d){a.a=null;b||(b=c?[c]:[]);a.A=c?String(c):void 0;a.c=0===c?-1:0;a.H=b;a:{if(a.H.length&&(b=a.H.length-1,(c=a.H[b])&&"object"==typeof c&&!_.ma(c))){a.l=b-a.c;a.b=c;break a}a.l=Number.MAX_VALUE}if(d)for(b=0;b<d.length;b++)c=d[b],c<a.l?(c+=a.c,a.H[c]=a.H[c]||_.Ca):a.b[c]=a.b[c]||_.Ca};_.Ca=[];_.w=function(a,b){if(b<a.l){var c=b+a.c,d=a.H[c];return d===_.Ca?a.H[c]=[]:d}d=a.b[b];return d===_.Ca?a.b[b]=[]:d};_.u.prototype.toString=function(){return this.H.toString()}; _.x=function(a,b){Da[a]=b;b.messageId=a};Da={};
_.Ea="StopIteration"in _.l?_.l.StopIteration:{message:"StopIteration",stack:""};_.Ga=function(){};_.Ga.prototype.next=function(){throw _.Ea;};_.Ga.prototype.$=function(){return this};a:{var Ia=_.l.navigator;if(Ia){var Ja=Ia.userAgent;if(Ja){_.Ha=Ja;break a}}_.Ha=""}_.y=function(a){return-1!=_.Ha.indexOf(a)};_.Ka=function(){return _.y("Opera")||_.y("OPR")};_.z=function(a,b){this.b={};this.a=[];this.l=this.c=0;var c=arguments.length;if(1<c){if(c%2)throw Error("f");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a){a instanceof _.z?(c=a.M(),d=a.G()):(c=_.Ba(a),d=Aa(a));for(var e=0;e<c.length;e++)this.set(c[e],d[e])}};_.h=_.z.prototype;_.h.ea=function(){return this.c};_.h.G=function(){La(this);for(var a=[],b=0;b<this.a.length;b++)a.push(this.b[this.a[b]]);return a};_.h.M=function(){La(this);return this.a.concat()};
_.h.aa=function(){return 0==this.c};_.h.clear=function(){this.b={};this.l=this.c=this.a.length=0};_.h.remove=function(a){return _.Ma(this.b,a)?(delete this.b[a],this.c--,this.l++,this.a.length>2*this.c&&La(this),!0):!1};var La=function(a){if(a.c!=a.a.length){for(var b=0,c=0;b<a.a.length;){var d=a.a[b];_.Ma(a.b,d)&&(a.a[c++]=d);b++}a.a.length=c}if(a.c!=a.a.length){for(var e={},c=b=0;b<a.a.length;)d=a.a[b],_.Ma(e,d)||(a.a[c++]=d,e[d]=1),b++;a.a.length=c}};_.h=_.z.prototype;
_.h.get=function(a,b){return _.Ma(this.b,a)?this.b[a]:b};_.h.set=function(a,b){_.Ma(this.b,a)||(this.c++,this.a.push(a),this.l++);this.b[a]=b};_.h.forEach=function(a,b){for(var c=this.M(),d=0;d<c.length;d++){var e=c[d],f=this.get(e);a.call(b,f,e,this)}};_.h.clone=function(){return new _.z(this)};_.h.$=function(a){La(this);var b=0,c=this.l,d=this,e=new _.Ga;e.next=function(){if(c!=d.l)throw Error("g");if(b>=d.a.length)throw _.Ea;var e=d.a[b++];return a?e:d.b[e]};return e}; _.Ma=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
_.Na=function(a){if(a.G&&"function"==typeof a.G)return a.G();if(_.t(a))return a.split("");if(_.la(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return Aa(a)};var Ta,Va,Wa,Ya,$a,ab;_.Pa=_.Ka();_.B=_.y("Trident")||_.y("MSIE");_.Qa=_.y("Edge");_.Ra=_.y("Gecko")&&!(-1!=_.Ha.toLowerCase().indexOf("webkit")&&!_.y("Edge"))&&!(_.y("Trident")||_.y("MSIE"))&&!_.y("Edge");_.Sa=-1!=_.Ha.toLowerCase().indexOf("webkit")&&!_.y("Edge");Ta=_.l.navigator||null;_.Ua=Ta&&Ta.platform||"";Va=function(){var a=_.Ha;if(_.Ra)return/rv\:([^\);]+)(\)|;)/.exec(a);if(_.Qa)return/Edge\/([\d\.]+)/.exec(a);if(_.B)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(_.Sa)return/WebKit\/(\S+)/.exec(a)};
Wa=function(){var a=_.l.document;return a?a.documentMode:void 0};_.Xa=function(){if(_.Pa&&_.l.opera){var a;var b=_.l.opera.version;try{a=b()}catch(c){a=b}return a}a="";(b=Va())&&(a=b?b[1]:"");return _.B&&(b=Wa(),b>(0,window.parseFloat)(a))?String(b):a}();Ya={};
_.Za=function(a){var b;if(!(b=Ya[a])){b=0;for(var c=qa(String(_.Xa)).split("."),d=qa(String(a)).split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var g=c[f]||"",k=d[f]||"",p=RegExp("(\\d*)(\\D*)","g"),A=RegExp("(\\d*)(\\D*)","g");do{var E=p.exec(g)||["","",""],Y=A.exec(k)||["","",""];if(0==E[0].length&&0==Y[0].length)break;b=ra(0==E[1].length?0:(0,window.parseInt)(E[1],10),0==Y[1].length?0:(0,window.parseInt)(Y[1],10))||ra(0==E[2].length,0==Y[2].length)||ra(E[2],Y[2])}while(0==b)}b=Ya[a]= 0<=b}return b};$a=_.l.document;ab=$a&&_.B?Wa()||("CSS1Compat"==$a.compatMode?(0,window.parseInt)(_.Xa,10):5):void 0;
_.C=function(){this.L=this.L;this.l=this.l};_.C.prototype.L=!1;_.C.prototype.O=function(){this.L||(this.L=!0,this.v())};_.F=function(a,b){_.bb(a,_.ha(_.D,b))};_.bb=function(a,b){a.L?b.call(void 0):(a.l||(a.l=[]),a.l.push(_.n(void 0)?(0,_.r)(b,void 0):b))};_.C.prototype.v=function(){if(this.l)for(;this.l.length;)this.l.shift()()};_.D=function(a){a&&"function"==typeof a.O&&a.O()};
_.cb=!_.B||9<=ab;!_.Ra&&!_.B||_.B&&9<=ab||_.Ra&&_.Za("1.9.1");_.B&&_.Za("9");var db=function(a){db[" "](a);return a};db[" "]=_.na;_.eb=function(a,b){try{return db(a[b]),!0}catch(c){}return!1};var fb=!_.B||9<=ab,gb=_.B&&!_.Za("9");!_.Sa||_.Za("528");_.Ra&&_.Za("1.9b")||_.B&&_.Za("8")||_.Pa&&_.Za("9.5")||_.Sa&&_.Za("528");_.Ra&&!_.Za("8")||_.B&&_.Za("9");_.hb=function(a,b){this.type=a;this.a=this.target=b;this.hb=!0};_.hb.prototype.b=function(){this.hb=!1};var ib=function(a,b){_.hb.call(this,a?a.type:"");this.a=this.target=null;this.clientY=this.clientX=0;this.c=this.state=null;a&&this.U(a,b)};_.q(ib,_.hb);
ib.prototype.U=function(a,b){this.type=a.type;var c=a.changedTouches?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.a=b;var d=a.relatedTarget;d&&_.Ra&&_.eb(d,"nodeName");null===c?(this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:a.pageY):(this.clientX=void 0!==c.clientX?c.clientX:c.pageX,this.clientY=void 0!==c.clientY?c.clientY:c.pageY);this.state=a.state;this.c=a;a.defaultPrevented&&this.b()}; ib.prototype.b=function(){ib.B.b.call(this);var a=this.c;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,gb)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};
var jb,lb;jb="closure_listenable_"+(1E6*Math.random()|0);_.kb=function(a){return!(!a||!a[jb])};lb=0;var mb=function(a,b,c,d,e){this.listener=a;this.proxy=null;this.src=b;this.type=c;this.oa=!!d;this.qa=e;this.key=++lb;this.removed=this.na=!1},nb=function(a){a.removed=!0;a.listener=null;a.proxy=null;a.src=null;a.qa=null};var ob;ob=function(a){this.src=a;this.a={};this.b=0};_.qb=function(a,b,c,d,e,f){var g=b.toString();b=a.a[g];b||(b=a.a[g]=[],a.b++);var k=pb(b,c,e,f);-1<k?(a=b[k],d||(a.na=!1)):(a=new mb(c,a.src,g,!!e,f),a.na=d,b.push(a));return a};ob.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.a))return!1;var e=this.a[a];b=pb(e,b,c,d);return-1<b?(nb(e[b]),Array.prototype.splice.call(e,b,1),0==e.length&&(delete this.a[a],this.b--),!0):!1};
var rb=function(a,b){var c=b.type;c in a.a&&_.xa(a.a[c],b)&&(nb(b),0==a.a[c].length&&(delete a.a[c],a.b--))};ob.prototype.removeAll=function(a){a=a&&a.toString();var b=0,c;for(c in this.a)if(!a||c==a){for(var d=this.a[c],e=0;e<d.length;e++)++b,nb(d[e]);delete this.a[c];this.b--}return b};var sb=function(a,b,c,d,e){a=a.a[b.toString()];b=-1;a&&(b=pb(a,c,d,e));return-1<b?a[b]:null},pb=function(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.removed&&f.listener==b&&f.oa==!!c&&f.qa==d)return e}return-1};
var tb,ub,vb,Ab,Db,Eb,Bb,Gb,Fb,Cb,zb,Hb;tb="closure_lm_"+(1E6*Math.random()|0);ub={};vb=0;_.wb=function(a,b,c,d,e){if(_.ma(b)){for(var f=0;f<b.length;f++)_.wb(a,b[f],c,d,e);return null}c=_.xb(c);return _.kb(a)?a.listen(b,c,d,e):_.yb(a,b,c,!1,d,e)};
_.yb=function(a,b,c,d,e,f){if(!b)throw Error("j");var g=!!e,k=zb(a);k||(a[tb]=k=new ob(a));c=_.qb(k,b,c,d,e,f);if(c.proxy)return c;d=Ab();c.proxy=d;d.src=a;d.listener=c;if(a.addEventListener)a.addEventListener(b.toString(),d,g);else if(a.attachEvent)a.attachEvent(Bb(b.toString()),d);else throw Error("k");vb++;return c};Ab=function(){var a=Cb,b=fb?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b};
Db=function(a,b,c,d,e){if(_.ma(b))for(var f=0;f<b.length;f++)Db(a,b[f],c,d,e);else c=_.xb(c),_.kb(a)?a.Ea(b,c,d,e):a&&(a=zb(a))&&(b=sb(a,b,c,!!d,e))&&Eb(b)};Eb=function(a){if(!_.ka(a)&&a&&!a.removed){var b=a.src;if(_.kb(b))rb(b.S,a);else{var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.oa):b.detachEvent&&b.detachEvent(Bb(c),d);vb--;(c=zb(b))?(rb(c,a),0==c.b&&(c.src=null,b[tb]=null)):nb(a)}}};Bb=function(a){return a in ub?ub[a]:ub[a]="on"+a};
Gb=function(a,b,c,d){var e=!0;if(a=zb(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.oa==c&&!f.removed&&(f=Fb(f,d),e=e&&!1!==f)}return e};Fb=function(a,b){var c=a.listener,d=a.qa||a.src;a.na&&Eb(a);return c.call(d,b)};
Cb=function(a,b){if(a.removed)return!0;if(!fb){var c=b||_.oa("window.event"),d=new ib(c,this),e=!0;if(!(0>c.keyCode||void 0!=c.returnValue)){a:{var f=!1;if(0==c.keyCode)try{c.keyCode=-1;break a}catch(p){f=!0}if(f||void 0==c.returnValue)c.returnValue=!0}c=[];for(f=d.a;f;f=f.parentNode)c.push(f);for(var f=a.type,g=c.length-1;0<=g;g--){d.a=c[g];var k=Gb(c[g],f,!0,d),e=e&&k}for(g=0;g<c.length;g++)d.a=c[g],k=Gb(c[g],f,!1,d),e=e&&k}return e}return Fb(a,new ib(b,this))}; zb=function(a){a=a[tb];return a instanceof ob?a:null};Hb="__closure_events_fn_"+(1E9*Math.random()>>>0);_.xb=function(a){if(_.ja(a))return a;a[Hb]||(a[Hb]=function(b){return a.handleEvent(b)});return a[Hb]};
_.Ib=function(a){_.v(this,a,"h_cc",null)};_.q(_.Ib,_.u);_.x("h_cc",_.Ib);_.Ib.prototype.T=function(){return _.w(this,19)};_.G=function(a){this.a=a};_.G.prototype.toString=function(){return this.a};_.H=function(a){_.C.call(this);this.I=a;this.f={}};_.q(_.H,_.C);var Jb=[];_.H.prototype.listen=function(a,b,c,d){return _.Kb(this,a,b,c,d)};_.Kb=function(a,b,c,d,e,f){_.ma(c)||(c&&(Jb[0]=c.toString()),c=Jb);for(var g=0;g<c.length;g++){var k=_.wb(b,c[g],d||a.handleEvent,e||!1,f||a.I||a);if(!k)break;a.f[k.key]=k}return a};
_.H.prototype.Ea=function(a,b,c,d,e){if(_.ma(b))for(var f=0;f<b.length;f++)this.Ea(a,b[f],c,d,e);else c=c||this.handleEvent,e=e||this.I||this,c=_.xb(c),d=!!d,b=_.kb(a)?sb(a.S,String(b),c,d,e):a?(a=zb(a))?sb(a,b,c,d,e):null:null,b&&(Eb(b),delete this.f[b.key]);return this};_.H.prototype.removeAll=function(){_.za(this.f,function(a,b){this.f.hasOwnProperty(b)&&Eb(a)},this);this.f={}};_.H.prototype.v=function(){_.H.B.v.call(this);this.removeAll()}; _.H.prototype.handleEvent=function(){throw Error("l");};
var Lb=function(a,b,c){this.l=c;this.c=a;this.f=b;this.b=0;this.a=null};Lb.prototype.get=function(){var a;0<this.b?(this.b--,a=this.a,this.a=a.next,a.next=null):a=this.c();return a};var Mb=function(a,b){a.f(b);a.b<a.l&&(a.b++,b.next=a.a,a.a=b)};var Nb,Ob,Pb;Nb=function(a){_.l.setTimeout(function(){throw a;},0)};_.Qb=function(a,b){var c=a;b&&(c=(0,_.r)(a,b));!_.ja(_.l.setImmediate)||_.l.Window&&_.l.Window.prototype&&!_.y("Edge")&&_.l.Window.prototype.setImmediate==_.l.setImmediate?(Ob||(Ob=Pb()),Ob(c)):_.l.setImmediate(c)};
Pb=function(){var a=_.l.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&!_.y("Presto")&&(a=function(){var a=window.document.createElement("IFRAME");a.style.display="none";a.src="";window.document.documentElement.appendChild(a);var b=a.contentWindow,a=b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d="file:"==b.location.protocol?"*":b.location.protocol+"//"+b.location.host,a=(0,_.r)(function(a){if(("*"==
d||a.origin==d)&&a.data==c)this.port1.onmessage()},this);b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});if("undefined"!==typeof a&&!_.y("Trident")&&!_.y("MSIE")){var b=new a,c={},d=c;b.port1.onmessage=function(){if(_.n(c.next)){c=c.next;var a=c.Ya;c.Ya=null;a()}};return function(a){d.next={Ya:a};d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof window.document&&"onreadystatechange"in window.document.createElement("SCRIPT")?function(a){var b= window.document.createElement("SCRIPT");b.onreadystatechange=function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};window.document.documentElement.appendChild(b)}:function(a){_.l.setTimeout(a,0)}};
var Rb=function(){this.b=this.a=null},Tb=new Lb(function(){return new Sb},function(a){a.reset()},100);Rb.prototype.remove=function(){var a=null;this.a&&(a=this.a,this.a=this.a.next,this.a||(this.b=null),a.next=null);return a};var Sb=function(){this.next=this.b=this.a=null};Sb.prototype.set=function(a,b){this.a=a;this.b=b;this.next=null};Sb.prototype.reset=function(){this.next=this.b=this.a=null};
var Yb=function(a,b){Ub||Vb();Wb||(Ub(),Wb=!0);var c=Xb,d=Tb.get();d.set(a,b);c.b?c.b.next=d:c.a=d;c.b=d},Ub,Vb=function(){if(_.l.Promise&&_.l.Promise.resolve){var a=_.l.Promise.resolve(void 0);Ub=function(){a.then(Zb)}}else Ub=function(){_.Qb(Zb)}},Wb=!1,Xb=new Rb,Zb=function(){for(var a=null;a=Xb.remove();){try{a.a.call(a.b)}catch(b){Nb(b)}Mb(Tb,a)}Wb=!1};
_.I=function(){_.C.call(this);this.S=new ob(this);this.K=this;this.C=null};_.q(_.I,_.C);_.I.prototype[jb]=!0;_.h=_.I.prototype;_.h.addEventListener=function(a,b,c,d){_.wb(this,a,b,c,d)};_.h.removeEventListener=function(a,b,c,d){Db(this,a,b,c,d)};_.h.v=function(){_.I.B.v.call(this);this.S&&this.S.removeAll(void 0);this.C=null};_.h.listen=function(a,b,c,d){return _.qb(this.S,String(a),b,!1,c,d)};_.h.Ea=function(a,b,c,d){return this.S.remove(String(a),b,c,d)}; _.h.Z=function(a,b,c){a=this.S.a[String(a)];if(!a)return!0;a=a.concat();for(var d=!0,e=0;e<a.length;++e){var f=a[e];if(f&&!f.removed&&f.oa==b){var g=f.listener,k=f.qa||f.src;f.na&&rb(this.S,f);d=!1!==g.call(k,c)&&d}}return d&&0!=c.hb};
var $b=function(a){a.prototype.then=a.prototype.then;a.prototype.$goog_Thenable=!0},ac=function(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};var cc=function(a,b){this.a=0;this.h=void 0;this.c=this.b=this.l=null;this.f=this.g=!1;if(a!=_.na)try{var c=this;a.call(b,function(a){bc(c,2,a)},function(a){bc(c,3,a)})}catch(d){bc(this,3,d)}},dc=function(){this.next=this.c=this.b=this.l=this.a=null;this.f=!1},ec,fc;dc.prototype.reset=function(){this.c=this.b=this.l=this.a=null;this.f=!1};ec=new Lb(function(){return new dc},function(a){a.reset()},100);fc=function(a,b,c){var d=ec.get();d.l=a;d.b=b;d.c=c;return d};
_.hc=function(){var a,b=new cc(function(b){a=b});return new gc(b,a)};cc.prototype.then=function(a,b,c){return ic(this,_.ja(a)?a:null,_.ja(b)?b:null,c)};$b(cc);
var kc=function(a,b){a.b||2!=a.a&&3!=a.a||jc(a);a.c?a.c.next=b:a.b=b;a.c=b},ic=function(a,b,c,d){var e=fc(null,null,null);e.a=new cc(function(a,g){e.l=b?function(c){try{var e=b.call(d,c);a(e)}catch(A){g(A)}}:a;e.b=c?function(b){try{var e=c.call(d,b);!_.n(e)&&"undefined"!=typeof lc&&b instanceof lc?g(b):a(e)}catch(A){g(A)}}:g});e.a.l=a;kc(a,e);return e.a};cc.prototype.u=function(a){this.a=0;bc(this,2,a)};cc.prototype.w=function(a){this.a=0;bc(this,3,a)};
var bc=function(a,b,c){if(0==a.a){a==c&&(b=3,c=new TypeError("Promise cannot resolve to itself"));a.a=1;var d;a:{var e=c,f=a.u,g=a.w;if(e instanceof cc)kc(e,fc(f||_.na,g||null,a)),d=!0;else if(ac(e))e.then(f,g,a),d=!0;else{if(_.ia(e))try{var k=e.then;if(_.ja(k)){mc(e,k,f,g,a);d=!0;break a}}catch(p){g.call(a,p);d=!0;break a}d=!1}}d||(a.h=c,a.a=b,a.l=null,jc(a),3!=b||"undefined"!=typeof lc&&c instanceof lc||nc(a,c))}},mc=function(a,b,c,d,e){var f=!1,g=function(a){f||(f=!0,c.call(e,a))},k=function(a){f||
(f=!0,d.call(e,a))};try{b.call(a,g,k)}catch(p){k(p)}},jc=function(a){a.g||(a.g=!0,Yb(a.j,a))},oc=function(a){var b=null;a.b&&(b=a.b,a.b=b.next,b.next=null);a.b||(a.c=null);return b};cc.prototype.j=function(){for(var a=null;a=oc(this);){var b=this.a,c=this.h;if(3==b&&a.b&&!a.f)for(var d=void 0,d=this;d&&d.f;d=d.l)d.f=!1;if(a.a)a.a.l=null,pc(a,b,c);else try{a.f?a.l.call(a.c):pc(a,b,c)}catch(e){qc.call(null,e)}Mb(ec,a)}this.g=!1}; var pc=function(a,b,c){2==b?a.l.call(a.c,c):a.b&&a.b.call(a.c,c)},nc=function(a,b){a.f=!0;Yb(function(){a.f&&qc.call(null,b)})},qc=Nb,lc=function(a){_.pa.call(this,a)};_.q(lc,_.pa);lc.prototype.name="cancel";var gc=function(a,b){this.b=a;this.a=b};
_.rc=function(a,b){for(var c=[],d=0;d<arguments.length;d++)c.push(arguments[d]||"");return c.join("_;_")};_.sc=function(){return 0<=window.navigator.userAgent.indexOf("CrOS")};_.J=function(a,b){this.f=a||"e";this.l=null!=a&&"p"==a?"e":"p";this.a=this.g=null;this.j=b||"u";this.c=this.h=null;this.b=[]};_.J.prototype.message=function(){var a={};a.i=this.c;a.m=this.b;a.r=this.j;a.o=this.h;a.s=this.a;a.st=this.l;a.d=this.g;a.dt=this.f;return a};_.J.prototype.message=_.J.prototype.message;
_.tc=function(a,b){for(var c in b)switch(c){case "r":a.j=b[c];break;case "i":a.c=b[c];break;case "m":a.b=b[c];break;case "o":a.h=b[c];break;case "s":a.a=b[c];break;case "d":a.g=b[c];break;case "st":a.l=b[c];break;case "dt":a.f=b[c]}return a};_.uc=function(a,b,c){null!=b&&(a.a=b,null!=c&&(a.l=c))};_.vc=function(a,b){null!=b&&(a.c=b)};_.wc=function(a,b){"object"==typeof b?a.b=b:a.b=[b]};_.J.prototype.target=function(){return this.g};
_.xc=function(a,b,c,d,e){_.C.call(this);this.b=a;this.ma=b;this.a=typeof b;this.Ba=c?c:!1;this.Y=!0;this.Aa=d?d:!1;this.wa=e?e:!1};_.q(_.xc,_.C);_.h=_.xc.prototype;_.h.v=function(){_.xc.B.v.call(this);this.b="";this.ma=null;this.a=""};_.h.id=function(){return this.b};_.h.type=function(){return this.a};_.h.F=function(){return this.ma};_.h.setEnabled=function(a){this.Y=a};
_.zc=function(a){_.C.call(this);this.a=new _.z;this.b=["https://hangouts.google.com","","https://autopush.hangouts.sandbox.google.com?jsmode=du"];a&&_.yc(this,a)};_.q(_.zc,_.C);_.Ac=!_.sc();_.zc.prototype.v=function(){_.zc.B.v.call(this);for(var a=this.a.M(),b=0;b<a.length;++b)_.D(this.a.get(a[b]));delete this.a};_.zc.prototype.getItem=function(a){return _.Ma(this.a.b,a)?this.a.get(a):null};_.zc.prototype.setItem=function(a){this.a.set(a.id(),a)}; _.yc=function(a,b){for(var c in b){var d=b[c],e=null;_.Ma(a.a.b,c)?(e=a.a.get(c),e.ma=d.value,d.changed&&(e.wa=d.changed)):(e=new _.xc(c,d.value,d.multiple,d.inverse,d.changed),e.setEnabled(!d.disabled));a.a.set(c,e)}};
_.Cc=function(){this.c=new _.z;this.a=null;this.b=!1;this.a=new Bc;this.b=!0;this.U()};_.Cc.fa=function(){return _.Cc.a?_.Cc.a:_.Cc.a=new _.Cc};_.h=_.Cc.prototype;_.h.U=function(a){var b=a||_.na;this.b?b():window.chrome.storage.local.get((0,_.r)(function(a){if(!this.b){for(var d in a)this.c.set(d,a[d]);this.b=!0}b()},this))};_.h.get=function(a){return this.a.get(a)};_.h.set=function(a,b){var c=_.hc();this.a.set(a,b);c.a(void 0);return c.b};_.h.remove=function(a){this.a.remove(a)};_.h.clear=function(){this.a.clear()};
var Bc=function(){this.a=window.localStorage};Bc.prototype.clear=function(){this.a.clear()};Bc.prototype.get=function(a){a=this.a.getItem(a);if(a){var b=JSON.parse(a);a=b.data;if("jspb"==b.type){b=Da[a[0]];if(!b)throw Error("d`"+a[0]);a=new b(a)}}else a=null;return a};Bc.prototype.set=function(a,b){var c=null;b instanceof _.u&&(b=b.H,c="jspb");var d={};d.data=b;d.timestamp=(0,_.m)();c&&(d.type=c);c=JSON.stringify(d);try{this.a.setItem(a,c)}catch(e){}};Bc.prototype.remove=function(a){try{this.a.removeItem(a)}catch(b){}};
/*
 Portions of this code are from MochiKit, received by
 The Closure Authors under the MIT license. All other code is Copyright
 2005-2009 The Closure Authors. All Rights Reserved.
*/
var Dc=function(a,b){this.l=[];this.D=b||null;this.a=this.b=!1;this.c=void 0;this.u=this.w=this.g=!1;this.f=0;this.h=null;this.A=0};Dc.prototype.j=function(a,b){this.g=!1;this.b=!0;this.c=b;this.a=!a;Ec(this)};Dc.prototype.C=function(a){if(this.b){if(!this.u)throw new Fc;this.u=!1}this.b=!0;this.c=a;this.a=!1;Ec(this)};var Gc=function(a,b,c){a.l.push([b,c,void 0]);a.b&&Ec(a)};
Dc.prototype.then=function(a,b,c){var d,e,f=new cc(function(a,b){d=a;e=b});Gc(this,d,function(a){e(a)});return f.then(a,b,c)};$b(Dc);
var Hc=function(a){return(0,_.wa)(a.l,function(a){return _.ja(a[1])})},Ec=function(a){if(a.f&&a.b&&Hc(a)){var b=a.f,c=Ic[b];c&&(_.l.clearTimeout(c.a),delete Ic[b]);a.f=0}a.h&&(a.h.A--,delete a.h);for(var b=a.c,d=c=!1;a.l.length&&!a.g;){var e=a.l.shift(),f=e[0],g=e[1],e=e[2];if(f=a.a?g:f)try{var k=f.call(e||a.D,b);_.n(k)&&(a.a=a.a&&(k==b||k instanceof Error),a.c=b=k);if(ac(b)||"function"===typeof _.l.Promise&&b instanceof _.l.Promise)d=!0,a.g=!0}catch(p){b=p,a.a=!0,Hc(a)||(c=!0)}}a.c=b;d&&(k=(0,_.r)(a.j,
a,!0),d=(0,_.r)(a.j,a,!1),b instanceof Dc?(Gc(b,k,d),b.w=!0):b.then(k,d));c&&(b=new Jc(b),Ic[b.a]=b,a.f=b.a)},Fc=function(){_.pa.call(this)};_.q(Fc,_.pa);Fc.prototype.message="Deferred has already fired";Fc.prototype.name="AlreadyCalledError";var Jc=function(a){this.a=_.l.setTimeout((0,_.r)(this.c,this),0);this.b=a};Jc.prototype.c=function(){delete Ic[this.a];throw this.b;};var Ic={};

}catch(e){_._DumpException(e)}
try{
var Mc;_.Kc=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);else if(_.la(a)||_.t(a))(0,_.ta)(a,b,void 0);else{var c;if(a.M&&"function"==typeof a.M)c=a.M();else if(a.G&&"function"==typeof a.G)c=void 0;else if(_.la(a)||_.t(a)){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=_.Ba(a);for(var d=_.Na(a),e=d.length,f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}};_.Lc=function(a){a&&a.parentNode&&a.parentNode.removeChild(a)}; Mc=function(a,b){for(var c=_.t(a)?a.split(""):a,d=a.length-1;0<=d;--d)d in c&&b.call(void 0,c[d],d,a)};
var Nc=function(a,b){this.c=a;this.b=b;this.constructor.Xa||(this.constructor.Xa={});this.constructor.Xa[this.toString()]=this};Nc.prototype.toString=function(){this.a||(this.a=this.c.a+":"+this.b);return this.a};var Oc=function(a,b){Nc.call(this,a,b)};_.q(Oc,Nc);var Pc=function(a){this.a=a};new Pc("lib");_.Rc=function(a){_.C.call(this);this.b={};this.u={};this.w={};this.f={};this.A={};this.D={};this.C=a?a.g():new _.I;this.K=!a;this.h=null;a?(this.h=a,this.w=a.w,this.f=a.f,this.u=a.u,this.A=a.A):(0,_.m)();a=Qc(this);this!=a&&(a.j?a.j.push(this):a.j=[this])};_.q(_.Rc,_.C);var Qc=function(a){for(;a.h;)a=a.h;return a};_.Rc.prototype.get=function(a){var b=this.c(a);if(null==b)throw new Sc(a);return b};
_.Rc.prototype.c=function(a){for(var b=this;b;b=b.h){if(b.L)throw Error("n");if(b.b[a])return b.b[a][0];if(b.D[a])break}if(b=this.w[a]){b=b(this);if(null==b)throw Error("o`"+a);this.a(a,b);return b}return null};_.Rc.prototype.a=function(a,b,c){if(this.L)c||_.D(b);else{this.b[a]=[b,!c];b=Tc(this,this,a);for(c=0;c<b.length;c++)b[c].C(null);delete this.u[a]}};_.Rc.prototype.I=function(){var a=_.Uc;if(!this.b[a])throw Error("p`"+a);var b=this.b[a];delete this.b[a];b[1]&&_.D(b[0])};
var Tc=function(a,b,c){var d=[],e=a.f[c];e&&(Mc(e,function(a){var c;a:{for(c=a.tb;c;){if(c==b){c=!0;break a}c=c.h}c=!1}c&&(d.push(a.d),_.xa(e,a))}),0==e.length&&delete a.f[c]);return d},Vc=function(a,b){a.f&&_.Kc(a.f,function(a,d,e){Mc(a,function(d){d.tb==b&&_.xa(a,d)});0==a.length&&delete e[d]})};
_.Rc.prototype.v=function(){if(Qc(this)==this){var a=this.j;if(a)for(;a.length;)a[0].O()}else for(var a=Qc(this).j,b=0;b<a.length;b++)if(a[b]==this){a.splice(b,1);break}for(var c in this.b)a=this.b[c],a[1]&&"undefined"!=typeof a[0].O&&a[0].O();this.b=null;this.K&&this.C.O();Vc(this,this);this.f=null;_.D(this.J);this.D=this.J=null;_.Rc.B.v.call(this)};_.Rc.prototype.g=function(){return this.C};var Sc=function(a){_.pa.call(this);this.id=a;this.message='Service for "'+a+'" is not registered'}; _.q(Sc,_.pa);var Wc=new Pc("fva");new Oc(Wc,1);

}catch(e){_._DumpException(e)}
try{
var Xc,Yc,Zc,fd,gd,hd,M,ld,md,pd,qd,rd,sd,td,ud,vd,xd,yd,zd,Ed;Xc=function(a,b,c,d,e){if(_.ma(b)){for(var f=0;f<b.length;f++)Xc(a,b[f],c,d,e);return null}c=_.xb(c);return _.kb(a)?_.qb(a.S,String(b),c,!0,d,e):_.yb(a,b,c,!0,d,e)};Yc="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");Zc=function(a,b,c,d,e,f){if(_.ma(c))for(var g=0;g<c.length;g++)Zc(a,b,c[g],d,e,f);else{b=Xc(b,c,d||a.handleEvent,e,f||a.I||a);if(!b)return a;a.f[b.key]=b}return a};
_.K=function(a,b,c){b<a.l?a.H[b+a.c]=c:a.b[b]=c};_.$c=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Yc.length;f++)c=Yc[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};_.ad=function(a){return a.b[0]};_.bd=function(a,b,c){null!=b&&(a.g=b,null!=c&&(a.f=c))};
_.L=function(a,b){var c,d=a.C;if(d)for(c=[];d;d=d.C)c.push(d);var d=a.K,e=b,f=e.type||e;if(_.t(e))e=new _.hb(e,d);else if(e instanceof _.hb)e.target=e.target||d;else{var g=e,e=new _.hb(f,d);_.$c(e,g)}var g=!0,k;if(c)for(var p=c.length-1;0<=p;p--)k=e.a=c[p],g=k.Z(f,!0,e)&&g;k=e.a=d;g=k.Z(f,!0,e)&&g;g=k.Z(f,!1,e)&&g;if(c)for(p=0;p<c.length;p++)k=e.a=c[p],g=k.Z(f,!1,e)&&g};_.cd=function(a,b,c,d){return Zc(a,b,c,d,void 0)};_.dd=function(a,b,c){a.a||(a.a={});var d=c?c.H:c;a.a[b]=c;_.K(a,b,d)};
_.ed=function(a,b,c){a.a||(a.a={});if(!a.a[c]){var d=_.w(a,c);d&&(a.a[c]=new b(d))}return a.a[c]};fd=function(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)};gd=function(a,b){return a?b?(0,window.decodeURI)(a.replace(/%25/g,"%2525")):(0,window.decodeURIComponent)(a):""};
hd=function(a,b){if(a)for(var c=a.split("&"),d=0;d<c.length;d++){var e=c[d].indexOf("="),f=null,g=null;0<=e?(f=c[d].substring(0,e),g=c[d].substring(e+1)):f=c[d];b(f,g?(0,window.decodeURIComponent)(g.replace(/\+/g," ")):"")}};_.id=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#(.*))?$/;_.jd=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};
_.kd=function(a){return Array.prototype.concat.apply(Array.prototype,arguments)};M=function(a,b,c){this.b=this.a=null;this.c=a||null;this.l=!!c};ld=function(a){a.a||(a.a=new _.z,a.b=0,a.c&&hd(a.c,function(b,c){var d=(0,window.decodeURIComponent)(b.replace(/\+/g," "));ld(a);a.c=null;var d=md(a,d),e=a.a.get(d);e||a.a.set(d,e=[]);e.push(c);a.b++}))};M.prototype.ea=function(){ld(this);return this.b};
M.prototype.remove=function(a){ld(this);a=md(this,a);return _.Ma(this.a.b,a)?(this.c=null,this.b-=this.a.get(a).length,this.a.remove(a)):!1};M.prototype.clear=function(){this.a=this.c=null;this.b=0};M.prototype.aa=function(){ld(this);return 0==this.b};var nd=function(a,b){ld(a);b=md(a,b);return _.Ma(a.a.b,b)};M.prototype.M=function(){ld(this);for(var a=this.a.G(),b=this.a.M(),c=[],d=0;d<b.length;d++)for(var e=a[d],f=0;f<e.length;f++)c.push(b[d]);return c};
M.prototype.G=function(a){ld(this);var b=[];if(_.t(a))nd(this,a)&&(b=_.kd(b,this.a.get(md(this,a))));else{a=this.a.G();for(var c=0;c<a.length;c++)b=_.kd(b,a[c])}return b};M.prototype.set=function(a,b){ld(this);this.c=null;a=md(this,a);nd(this,a)&&(this.b-=this.a.get(a).length);this.a.set(a,[b]);this.b++;return this};M.prototype.get=function(a,b){var c=a?this.G(a):[];return 0<c.length?String(c[0]):b};_.od=function(a,b,c){a.remove(b);0<c.length&&(a.c=null,a.a.set(md(a,b),_.jd(c)),a.b+=c.length)};
M.prototype.toString=function(){if(this.c)return this.c;if(!this.a)return"";for(var a=[],b=this.a.M(),c=0;c<b.length;c++)for(var d=b[c],e=(0,window.encodeURIComponent)(String(d)),d=this.G(d),f=0;f<d.length;f++){var g=e;""!==d[f]&&(g+="="+(0,window.encodeURIComponent)(String(d[f])));a.push(g)}return this.c=a.join("&")};M.prototype.clone=function(){var a=new M;a.c=this.c;this.a&&(a.a=this.a.clone(),a.b=this.b);return a};md=function(a,b){var c=String(b);a.l&&(c=c.toLowerCase());return c};
pd=function(a,b){b&&!a.l&&(ld(a),a.c=null,a.a.forEach(function(a,b){var e=b.toLowerCase();b!=e&&(this.remove(b),_.od(this,e,a))},a));a.l=b};qd=/#/g;rd=/[\#\?@]/g;sd=/[\#\?]/g;td=/[\#\?:]/g;ud=/[#\/\?@]/g;vd=function(a,b,c){return _.t(a)?(a=(0,window.encodeURI)(a).replace(b,fd),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null};
_.wd=function(a,b){this.c=this.j=this.f="";this.l=null;this.g=this.a="";this.h=!1;var c;"undefined"!=typeof _.wd&&a instanceof _.wd?(this.h=_.n(b)?b:a.h,xd(this,a.f),this.j=a.j,this.c=a.c,yd(this,a.l),this.a=a.a,zd(this,a.b.clone()),this.g=a.g):a&&(c=String(a).match(_.id))?(this.h=!!b,xd(this,c[1]||"",!0),this.j=gd(c[2]||""),this.c=gd(c[3]||"",!0),yd(this,c[4]),this.a=gd(c[5]||"",!0),zd(this,c[6]||"",!0),this.g=gd(c[7]||"")):(this.h=!!b,this.b=new M(null,0,this.h))};
_.wd.prototype.toString=function(){var a=[],b=this.f;b&&a.push(vd(b,ud,!0),":");var c=this.c;if(c||"file"==b)a.push("//"),(b=this.j)&&a.push(vd(b,ud,!0),"@"),a.push((0,window.encodeURIComponent)(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.l,null!=c&&a.push(":",String(c));if(c=this.a)this.c&&"/"!=c.charAt(0)&&a.push("/"),a.push(vd(c,"/"==c.charAt(0)?sd:td,!0));(c=this.b.toString())&&a.push("?",c);(c=this.g)&&a.push("#",vd(c,qd));return a.join("")};_.wd.prototype.clone=function(){return new _.wd(this)};
xd=function(a,b,c){a.f=c?gd(b,!0):b;a.f&&(a.f=a.f.replace(/:$/,""))};yd=function(a,b){if(b){b=Number(b);if((0,window.isNaN)(b)||0>b)throw Error("h`"+b);a.l=b}else a.l=null};zd=function(a,b,c){b instanceof M?(a.b=b,pd(a.b,a.h)):(c||(b=vd(b,rd)),a.b=new M(b,0,a.h))};_.N=function(a,b,c){a.b.set(b,c)};_.Ad=function(a){return a instanceof _.wd?a.clone():new _.wd(a,void 0)};
_.O=function(a,b,c){if(_.ja(a))c&&(a=(0,_.r)(a,c));else if(a&&"function"==typeof a.handleEvent)a=(0,_.r)(a.handleEvent,a);else throw Error("m");return 2147483647<b?-1:_.l.setTimeout(a,b||0)};
_.Bd=function(a,b){a instanceof _.wd||(a=_.Ad(a));b instanceof _.wd||(b=_.Ad(b));var c=a,d=b,e=c.clone(),f=!!d.f;f?xd(e,d.f):f=!!d.j;f?e.j=d.j:f=!!d.c;f?e.c=d.c:f=null!=d.l;var g=d.a;if(f)yd(e,d.l);else if(f=!!d.a)if("/"!=g.charAt(0)&&(c.c&&!c.a?g="/"+g:(c=e.a.lastIndexOf("/"),-1!=c&&(g=e.a.substr(0,c+1)+g))),c=g,".."==c||"."==c)g="";else if(-1!=c.indexOf("./")||-1!=c.indexOf("/.")){for(var g=0==c.lastIndexOf("/",0),c=c.split("/"),k=[],p=0;p<c.length;){var A=c[p++];"."==A?g&&p==c.length&&k.push(""):
".."==A?((1<k.length||1==k.length&&""!=k[0])&&k.pop(),g&&p==c.length&&k.push("")):(k.push(A),g=!0)}g=k.join("/")}else g=c;f?e.a=g:f=""!==d.b.toString();f?zd(e,gd(d.b.toString())):f=!!d.g;f&&(e.g=d.g);return e};_.Cd=function(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||Boolean(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a}; _.Dd=function(){return _.y("iPhone")&&!_.y("iPod")&&!_.y("iPad")};Ed=function(){return(_.y("Chrome")||_.y("CriOS"))&&!_.Ka()&&!_.y("Edge")};_.Fd=function(a){_.l.clearTimeout(a)};
_.Gd=_.y("Firefox");_.Hd=_.Dd()||_.y("iPod");_.Id=_.y("iPad");_.Jd=_.y("Android")&&!(Ed()||_.y("Firefox")||_.Ka()||_.y("Silk"));_.Kd=Ed();_.Ld=_.y("Safari")&&!(Ed()||_.y("Coast")||_.Ka()||_.y("Edge")||_.y("Silk")||_.y("Android"))&&!(_.Dd()||_.y("iPad")||_.y("iPod"));
var Md=function(){};Md.prototype.a=null;var Od;Od=function(){};_.q(Od,Md);_.Nd=new Od;_.Pd=function(a){_.v(this,a,"h_icr",null)};_.q(_.Pd,_.u);_.x("h_icr",_.Pd);
}catch(e){_._DumpException(e)}
try{
_.Gg=function(a){for(var b=a.a.M(),c={},d=0;d<b.length;d++){var e=b[d],f=a.a.get(e);c[e]={value:f.F(),type:f.type(),multiple:f.Ba,disabled:!f.Y,inverse:f.Aa,changed:f.wa}}return c};_.Hg=function(a,b){return _.t(b)?a.getElementById(b):b};_.Q=function(a){return _.Hg(window.document,a)};_.Ig=new _.G("a");_.Jg=new _.G("b");_.Kg=new _.G("c");_.Lg=new _.G("d");_.Mg=new _.G("e");_.Ng=new _.G("f");_.Og=new _.G("g");_.Pg=new _.G("h");_.Uc=new _.G("i");_.Qg=new _.G("j");

}catch(e){_._DumpException(e)}
try{
var Rg,Sg,Tg,Vg,Wg,Xg,Yg,Zg,$g,ah,bh,ch,eh,fh,gh,mh,nh,ph;Rg=function(a){return(a=a.a.get("TopMost"))&&a.Y?a.F():!0};Sg=function(){return!0};Tg=0;_.Ug=function(a){a&&a!=window.chrome.windows.WINDOW_ID_NONE&&window.chrome.windows.update(a,{focused:!0})};Vg=function(a){window.chrome.windows.getAll({populate:!0},function(b){for(var c=0;c<b.length;++c){var d=b[c].tabs;if(null!=d)for(var e=0;e<d.length;++e)if(d[e].selected&&d[e].url==a){_.Ug(b[c].id);return}}})};
Wg=function(a,b){var c=a.length-b.length;return 0<=c&&a.indexOf(b,c)==c};Xg=function(){return null!=window.navigator.platform.match(/Mac.*/)};Yg=function(){return!_.sc()&&null!=window.navigator.platform.match(/Linux.*/)};Zg=function(a){var b=typeof a;return"object"==b&&a||"function"==b?"o"+(a[_.ca]||(a[_.ca]=++Tg)):b.substr(0,1)+a};
$g=function(a){if(a instanceof _.Ga)return a;if("function"==typeof a.$)return a.$(!1);if(_.la(a)){var b=0,c=new _.Ga;c.next=function(){for(;;){if(b>=a.length)throw _.Ea;if(b in a)return a[b++];b++}};return c}throw Error("e");};ah=function(a,b){return a>b?1:a<b?-1:0};bh=function(a,b){null!=a&&(window.open(a,"winid_"+(new Date).getTime(),b),_.O((0,_.r)(Vg,null,a),1E3))};ch=function(a){null!=a&&(a=window.chrome.runtime.getURL("images_4/"+a));return a};
_.dh=function(a,b,c,d){this.left=a;this.top=b;this.width=c;this.height=d};_.dh.prototype.clone=function(){return new _.dh(this.left,this.top,this.width,this.height)};_.dh.prototype.contains=function(a){return"undefined"!=typeof _.dh&&a instanceof _.dh?this.left<=a.left&&this.left+this.width>=a.left+a.width&&this.top<=a.top&&this.top+this.height>=a.top+a.height:a.x>=this.left&&a.x<=this.left+this.width&&a.y>=this.top&&a.y<=this.top+this.height};
_.dh.prototype.floor=function(){this.left=Math.floor(this.left);this.top=Math.floor(this.top);this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};_.dh.prototype.round=function(){this.left=Math.round(this.left);this.top=Math.round(this.top);this.width=Math.round(this.width);this.height=Math.round(this.height);return this};eh=[/^https?:\/\/.*.google.com(:[0-9]+)?\/talkgadget\/success/,/^https:\/\/accounts.google.com\/ServiceLogin/];fh=[1E4,12E4,144E5];gh=[200,2E3,3E5];
_.ih=function(a,b){_.I.call(this);this.c=a||1;this.b=b||_.l;this.g=(0,_.r)(this.j,this);this.h=(0,_.m)()};_.q(_.ih,_.I);_.ih.prototype.f=!1;_.ih.prototype.a=null;_.ih.prototype.setInterval=function(a){this.c=a;this.a&&this.f?(this.stop(),_.jh(this)):this.a&&this.stop()};
_.ih.prototype.j=function(){if(this.f){var a=(0,_.m)()-this.h;0<a&&a<.8*this.c?this.a=this.b.setTimeout(this.g,this.c-a):(this.a&&(this.b.clearTimeout(this.a),this.a=null),_.L(this,"tick"),this.f&&(this.a=this.b.setTimeout(this.g,this.c),this.h=(0,_.m)()))}};_.jh=function(a){a.f=!0;a.a||(a.a=a.b.setTimeout(a.g,a.c),a.h=(0,_.m)())};_.ih.prototype.stop=function(){this.f=!1;this.a&&(this.b.clearTimeout(this.a),this.a=null)};_.ih.prototype.v=function(){_.ih.B.v.call(this);this.stop();delete this.b};
var kh=function(a){this.a=a||_.l.document||window.document};kh.prototype.contains=_.Cd;_.Ff=function(a,b){this.width=a;this.height=b};_.h=_.Ff.prototype;_.h.clone=function(){return new _.Ff(this.width,this.height)};_.h.ub=function(){return this.width*this.height};_.h.aa=function(){return!this.ub()};_.h.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};_.h.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};
var lh=function(a){this.a=new _.z;if(a){a=_.Na(a);for(var b=a.length,c=0;c<b;c++){var d=a[c];this.a.set(Zg(d),d)}}};_.h=lh.prototype;_.h.ea=function(){return this.a.ea()};_.h.removeAll=function(a){a=_.Na(a);for(var b=a.length,c=0;c<b;c++)this.remove(a[c])};_.h.remove=function(a){return this.a.remove(Zg(a))};_.h.clear=function(){this.a.clear()};_.h.aa=function(){return this.a.aa()};_.h.contains=function(a){a=Zg(a);return _.Ma(this.a.b,a)};_.h.G=function(){return this.a.G()};_.h.clone=function(){return new lh(this)};
_.h.$=function(){return this.a.$(!1)};mh=function(a,b){if(_.la(a))try{(0,_.ta)(a,b,void 0)}catch(c){if(c!==_.Ea)throw c;}else{a=$g(a);try{for(;;)b.call(void 0,a.next(),void 0,a)}catch(c){if(c!==_.Ea)throw c;}}};nh=function(a,b,c){a.a||(a.a={});c=c||[];for(var d=[],e=0;e<c.length;e++)d[e]=c[e].H;a.a[b]=c;_.K(a,b,d)};_.oh=function(a,b,c){a.a||(a.a={});if(!a.a[c]){for(var d=_.w(a,c),e=[],f=0;f<d.length;f++)e[f]=new b(d[f]);a.a[c]=e}b=a.a[c];b==_.Ca&&(b=a.a[c]=[]);return b}; ph=function(a,b){a.sort(b||ah)};
var qh=function(){_.C.call(this)};_.q(qh,_.C);qh.prototype.U=function(){};new qh;var sh=function(a,b,c){_.I.call(this);this.a=b.createElement("IFRAME");b.body.appendChild(this.a);this.a.src=a;c&&(this.a.id=c,this.a.name=c);a=new _.H(this);_.F(this,a);_.cd(_.cd(a,this.a,"load",this.c),this.a,"error",rh).listen(b.defaultView,"focus",this.b).listen(b.body,"focus",this.b)};_.q(sh,_.I);sh.prototype.b=function(){_.Qb(this.a.focus,this.a)};sh.prototype.c=function(){this.b()};sh.prototype.v=function(){this.a.parentElement.removeChild(this.a);this.a=null;sh.B.v.call(this)};
var th={},uh=function(){delete th.ba},rh=function(){th.ba(1)};_.vh=function(a){this.c=a;this.a=new _.zc;this.b=a.get(_.Pg);this.a.setItem(new _.xc("StartOnBrowserLaunch",!0,!1,!1));_.Ac&&this.a.setItem(new _.xc("TopMost",!0));a=new _.xc("StopOnBrowserClose",!1,!1,!1);a.setEnabled(!1);this.a.setItem(a);a=new _.xc("TrayIcon",!0,!1,!1);a.setEnabled(null!=window.navigator.platform.match(/Win.*/)||Yg()||Xg());this.a.setItem(a);(a=this.b.get("settings"))&&_.yc(this.a,a);this.b.set("settings",_.Gg(this.a))};_.ga("ace.core.SettingsManager",_.vh);
var wh=window.chrome.runtime&&window.chrome.runtime.getURL&&window.chrome.runtime.getURL("settingsdialog.html")||"";_.vh.prototype.Lb=function(){this.b.set("settings",_.Gg(this.a));var a=_.S.f("setting");if(a&&0!=a.length)xh(a[0],"focus");else{var a=Math.floor((window.screen.height-200)/2),b=Math.floor((window.screen.width-520)/2),c=["width=520"];c.push("height=200");c.push("top="+a);c.push("left="+b);c.push("location=no");bh(wh,c.join(","))}};_.vh.prototype.launchSettingsDialog=_.vh.prototype.Lb;
_.vh.prototype.mc=function(){var a=new _.zc(_.Gg(this.a)),b=this.b.get("settings");_.yc(this.a,b);var c=new _.zc(b),b=c.getItem("StopOnBrowserClose"),a=a.getItem("TrayIcon"),c=c.getItem("TrayIcon");a.Y&&(c.F()||b.F()?(b=this.c.get(_.Jg),yh(b),zh(b)):c.F()||b.F()||Ah(this.c.get(_.Jg)))};_.vh.prototype.updateSettingsFromStorage=_.vh.prototype.mc;_.vh.prototype.Za=function(){var a=_.S.f("setting");if(a)for(var b=0;b<a.length;++b)xh(a[b],"close")};_.vh.prototype.closeUI=_.vh.prototype.Za; var xh=function(a,b){var c=new _.J;_.vc(c,b);_.wc(c,[]);_.S.b(a).sendMessage(c)};
var Gh=function(a,b){_.H.call(this);this.b=a;_.rc("viewer",""+(new Date).getTime());this.g=this.h=null;this.w=_.S;this.D=(0,_.m)();this.u=a.get(_.Jg);var c=a.get(_.Ng),d=window.chrome.i18n.getMessage("CHROME_EXT_SHORT_NAME"),e=ch("viewer-14.png"),f=ch("viewer-28.png"),d=Bh(c,"viewer","viewer","viewer.html?viewer",d,e,f),e=b?_.ed(b,_.Ch,2).ka():null,e=Dh(c,new _.Ff(260,460),!0,e);Eh(c,d.id,e);this.a=d;this.a.onClosed.addListener((0,_.r)(this.O,this));Fh(this.a,(0,_.r)(this.A,this))};_.q(Gh,_.H);
Gh.prototype.v=function(){this.b.c(_.Uc)==this&&this.b.I();this.removeAll();Gh.B.v.call(this)};var Hh=function(a){_.D(a.h);a.h=null;_.D(a.g);a.g=null;_.Hg(a.c.a,"retryInfo").style.display="none"};Gh.prototype.close=function(){_.D(this.a);this.b.c(_.Uc)==this&&this.b.I()};
Gh.prototype.A=function(){this.c=new kh(Ih(this.a).document);this.a.setTitle(window.chrome.i18n.getMessage("CHROME_EXT_SHORT_NAME"));_.Hg(this.c.a,"retryMessage").textContent=window.chrome.i18n.getMessage("CHROME_EXT_CANNOT_CONNECT");var a=_.Hg(this.c.a,"retryLink");a.textContent=window.chrome.i18n.getMessage("QUASAR_TRY_NOW");this.listen(a,"click",this.C);this.listen(this.w,"onStatusChange",this.j);this.j()};Gh.prototype.C=function(a){a.b();this.b.get(_.Ig).g()};
Gh.prototype.j=function(){switch(this.u.a){case 3:if(!this.h){Hh(this);var a=this.b.get(_.Og).a,a=_.ad(a),a=_.Bd(a,"/talkgadget/qsignin");_.N(a,"passive","1");_.N(a,"hl",window.chrome.i18n.getMessage("@@ui_locale"));this.h=new sh(a.toString(),this.c.a)}break;case 2:Hh(this);break;case 6:Hh(this);_.Hg(this.c.a,"retryInfo").style.display="block";break;default:Jh(this)}};var Jh=function(a){a.g||(Hh(a),Kh(a.b.get(_.Ig)).then(function(a){this.g=new sh(a,this.c.a,"popoutRoster")},void 0,a))};
var Lh=function(a,b){this.b=_.jd(a);this.a=0;this.c=b||!1};Lh.prototype.reset=function(){this.a=0};Lh.prototype.F=function(a){var b=this.b[this.a],b=(.5+1*Math.random())*b;a&&Mh(this);return b};var Mh=function(a){a.c&&a.a==a.b.length-1||a.a++};var Nh=function(a,b,c){_.C.call(this);this.b=a;this.f=b||0;this.c=c;this.ba=(0,_.r)(this.g,this)};_.q(Nh,_.C);Nh.prototype.a=0;Nh.prototype.v=function(){Nh.B.v.call(this);this.stop();delete this.b;delete this.c};var Oh=function(a,b){a.stop();a.a=_.O(a.ba,_.n(b)?b:a.f)};Nh.prototype.stop=function(){0!=this.a&&_.Fd(this.a);this.a=0};Nh.prototype.g=function(){this.a=0;this.b&&this.b.call(this.c)};
var Ph=function(a,b,c){_.C.call(this);this.c=null!=c?(0,_.r)(a,c):a;this.b=b;this.ba=(0,_.r)(this.Xb,this);this.a=[]};_.q(Ph,_.C);_.h=Ph.prototype;_.h.ua=!1;_.h.ga=null;_.h.ab=function(a){this.a=arguments;this.ga?this.ua=!0:Qh(this)};_.h.stop=function(){this.ga&&(_.Fd(this.ga),this.ga=null,this.ua=!1,this.a=[])};_.h.v=function(){Ph.B.v.call(this);this.stop()};_.h.Xb=function(){this.ga=null;this.ua&&(this.ua=!1,Qh(this))};var Qh=function(a){a.ga=_.O(a.ba,a.b);a.c.apply(null,a.a)};
_.T=function(a){_.H.call(this);this.h=a;this.b=a.get(_.Jg);this.P=a.c(_.Ng);this.N=_.hc();this.w=null;this.J=new Ph(this.g,6E4,this);_.F(this,this.J);a=(0,_.r)(this.Rb,this);th.ba=a;_.bb(this,uh);this.j=!1;this.A=new Lh(fh,!0);this.K=new Nh(this.ec,this.A.F(),this);_.F(this,this.K);this.u=new Nh(this.gb,4E4,this);_.F(this,this.u);this.listen(window,"online",this.Ub);this.a=new Lh(gh);this.c=new Nh(this.Cb,this.a.F(),this);_.F(this,this.c);window.chrome.cookies.onChanged.addListener((0,_.r)(this.V,
this));this.D=(0,_.r)(this.pb,this);this.C=(0,_.r)(this.ob,this);window.chrome.tabs.onUpdated.addListener(this.D);window.chrome.tabs.onCreated.addListener(this.C)};_.q(_.T,_.H);_.ga("ace.core.DataChannelManager",_.T);_.T.prototype.v=function(){window.chrome.tabs.onCreated.removeListener(this.C);window.chrome.tabs.onUpdated.removeListener(this.D);delete this.C;delete this.D;_.D(this.w);_.T.B.v.call(this)};
_.T.prototype.va=function(a,b){_.Rh(this);a:{var c=this.h,d=c.c(_.Uc);if(d){if(Sh(d.a)?!Th(d.a):1E3>(0,_.m)()-d.D){d.a.focus();break a}d.close()}d=new Gh(c,b);c.a(_.Uc,d,!0)}};_.T.prototype.showViewer=_.T.prototype.va;_.T.prototype.kc=function(a,b){this.N.a(b||"")};_.T.prototype.setRosterUrl=_.T.prototype.kc;var Kh=function(a){return a.N.b};_.T.prototype.Da=function(){this.b.ca(0,1);var a=this.h.c(_.Uc);a&&a.close();Uh(this);this.j=!1};_.T.prototype.terminateApplication=_.T.prototype.Da;
_.Rh=function(a){a.j||(a.listen(_.S,"onStatusChange",a.qb),a.g(),a.h.get(_.Og),a.j=!0)};_.T.prototype.g=function(){this.L||(this.b.ca(0,2),Uh(this),this.w=new sh(window.chrome.runtime.getURL("datachannel.html"),window.document,"centralRoster"))};var Uh=function(a){a.P.xa();a.h.get(_.Mg).pa();_.D(a.w);a.w=null;a.N=_.hc()},Wh=function(a,b){var c=_.ad(a.h.get(_.Og).a);window.chrome.cookies.getAll({url:c},(0,_.r)(function(a){a=a&&Vh("SID",a)&&Vh("SSID",a)&&Vh("SAPISID",a);b(a)},a))};
_.T.prototype.W=function(a){var b=this.b.a;if(a){if(3==b){if(a=0==this.c.a)a=this.a,a=a.a<a.b.length;a&&Oh(this.c,this.a.F())}}else 3!=b&&this.g()};_.T.prototype.V=function(a){"SSID"!=a.cookie.name&&"SAPISID"!=a.cookie.name||".google.com"!=a.cookie.domain||Wh(this,(0,_.r)(this.W,this))};var Vh=function(a,b){return(0,_.wa)(b,function(b){var d=b.expirationDate&&b.expirationDate<(0,_.m)()/1E3;return b.name==a&&".google.com"==b.domain&&!d})};_.h=_.T.prototype;
_.h.qb=function(){this.K.stop();this.u.stop();switch(this.b.a){case 2:Oh(this.u);break;case 6:Oh(this.K,this.A.F());break;case 4:case 9:case 8:case 5:this.A.reset(),this.c.stop()}};_.h.Ub=function(){4!=this.b.a&&this.J.ab()};_.h.ec=function(){Mh(this.A);this.g()};_.h.Rb=function(a){Uh(this);switch(a){case 1:this.gb();break;case 2:this.J.ab()}};_.h.gb=function(){this.L||(this.u.stop(),this.b.ca(0,6))};_.h.Cb=function(){Mh(this.a);Wh(this,(0,_.r)(function(a){a&&this.g()},this))}; _.h.pb=function(a,b){b.url&&Xh(this,b.url)};_.h.ob=function(a){a.url&&Xh(this,a.url)};var Xh=function(a,b){(0,_.wa)(eh,function(a){return a.test(b)})&&0!=a.a.a&&(a.a.reset(),0!=a.c.a&&Oh(a.c,a.a.F()))};
_.U=function(a){this.A=a;this.w=a.get(_.Og);this.b=a.get(_.Pg);this.a=1;this.f=this.j=null;this.g=this.c=!1;this.u=(0,_.r)(this.C,this);yh(this);zh(this);null!=this.b.a.get("UnreadIndicator")&&this.b.remove("UnreadIndicator");null!=this.b.a.get("app_status")&&this.b.remove("app_status");null!=this.b.a.get("user_id")&&this.b.remove("user_id");null!=this.b.a.get("client_state")&&this.b.remove("client_state")};_.q(_.U,_.C);_.ga("ace.core.DesktopManager",_.U);_.U.prototype.v=function(){Ah(this);_.U.B.v.call(this)};
_.U.prototype.ca=function(a,b){this.a!=b&&(this.a=b,zh(this),Yh(this),1==this.a&&(this.f=this.j=null,this.g=this.c=!1,Ah(this),this.w.Za(),this.A.get(_.Mg).pa()),_.S.h())};_.U.prototype.changeDesktop=_.U.prototype.ca;_.U.prototype.ic=function(a,b){this.c!=b&&(this.c=b,zh(this),Yh(this))};_.U.prototype.setMainUiShowing=_.U.prototype.ic;_.U.prototype.h=function(){return this.c};
var yh=function(a){var b=a.w.a,c;if(c=null!=window.navigator.platform.match(/Win.*/)||Yg()||Xg())c=b.a.get("StopOnBrowserClose"),(c=c&&c.Y?c.F():!1)||(c=(b=b.a.get("TrayIcon"))&&b.Y?b.F():!1);c&&window.chrome.systemIndicator&&(window.chrome.systemIndicator.enable(),window.chrome.systemIndicator.onClicked.addListener(a.u))},Ah=function(a){window.chrome.systemIndicator&&(window.chrome.systemIndicator.disable(),window.chrome.systemIndicator.onClicked.removeListener(a.u))},Yh=function(a){var b;switch(a.a){case 2:b=
window.chrome.i18n.getMessage("QUASAR_TIP_CONNECTING");break;case 3:b=window.chrome.i18n.getMessage("QUASAR_TIP_NOT_LOGIN");break;case 4:case 9:case 8:b=a.c?a.g?window.chrome.i18n.getMessage("CHROME_EXT_TIP_CONNECTED_MISSED_MESSAGES"):window.chrome.i18n.getMessage("QUASAR_TIP_CONNECTED"):window.chrome.i18n.getMessage("QUASAR_TIP_NOT_LOGIN");break;case 6:b=window.chrome.i18n.getMessage("QUASAR_TIP_NOT_LOAD");break;default:b=window.chrome.i18n.getMessage("QUASAR_TIP_DISCONNECTED")}a=a.f?"\n"+a.f:"";
(b=window.chrome.i18n.getMessage("CHROME_EXT_SHORT_NAME")+a+"\n"+b)&&window.chrome.browserAction.setTitle({title:b})};_.U.prototype.nc=function(a,b,c){1!=this.a&&(a=b||window.chrome.i18n.getMessage("QUASAR_MENUTEXT_UNKNOWN_USER"),a!=this.j&&(this.j=a),this.f=c)};_.U.prototype.updateUserName=_.U.prototype.nc;_.U.prototype.lc=function(a,b){this.g!=b&&(this.g=b,zh(this),Yh(this))};_.U.prototype.setUnreadIndicator=_.U.prototype.lc;
var zh=function(a){window.chrome.browserAction.setIcon(Zh(a,!0));window.chrome.systemIndicator&&window.chrome.systemIndicator.setIcon(Zh(a))},$h=function(a){switch(a.a){case 2:return"offline_working";case 4:case 9:case 8:return a.c?a.g?"available_missed":"available":"offline";case 6:return"offline_unknown";default:return"offline"}},Zh=function(a,b){var c=!b&&Xg()?"_mac_":"_",d=$h(a),e=window.chrome.runtime.getURL("images_4/presence/"+d+c+"19.png"),c=window.chrome.runtime.getURL("images_4/presence/"+ d+c+"38.png");return{path:{19:e,38:c}}};_.U.prototype.C=function(){var a=_.S.a();a.la();a.b("onTrayClick",[1])};
var ai=function(a,b){this.a=a;this.j=b;this.u=window.chrome.runtime.getURL("images_4/icon-128x128.png");this.l=this.h=this.w="";this.f=0;this.b=[];this.g=""},bi=function(a){this.name=a;this.title=""};ai.prototype.setTitle=function(a){a&&(this.w=a)};
var ci=function(a){return a.replace(/^(\<br\>)+/,"")},di=function(a){var b=a.w;a.h&&(b+=" "+a.h);var c=ci(a.l||7!=a.j?a.l||"":window.chrome.i18n.getMessage("CHROME_EXT_ONEONONE_PLUS_HANGOUT_DETAILS")),d=(0,_.va)(a.b,function(a){var b;if(!(b=a.title))a:{switch(a.name){case "join hangout":b=window.chrome.i18n.getMessage("QUASAR_ANSWER_BUTTON_TEXT");break a;case "ignore":b=window.chrome.i18n.getMessage("QUASAR_DECLINE_BUTTON_TEXT");break a}b=""}return{title:b}},a);return{type:"basic",iconUrl:a.u,title:b, message:c,buttons:d,priority:2}};
var ei=function(){this.b=new _.z;this.a=new _.ih(18E5);_.wb(this.a,"tick",(0,_.r)(this.c,this,this.b,0,200));_.jh(this.a)};_.q(ei,_.C);ei.prototype.v=function(){this.a.O()};var fi=function(a,b){var c=null!=b.c?b.a+b.c:null;return null!=c?_.Ma(a.b.b,c):!1};
ei.prototype.c=function(a,b,c){var d=a.ea();if(0!=d){var e=0;null!=b&&0<b&&(e=b<d?b:d);b=d;null!=c&&c<d&&(b=0<c?c:0);e>b&&(e=b);var f=[];c=a.$(!0);mh(c,function(b){f.push([b,a.get(b)])});f.sort(function(a,b){return a[1]-b[1]});if(31536E7<f[d-1][1]-f[0][1])a.clear();else{c=0;b=d-b;for(var d=d-e,e=(0,_.m)(),g=0;g<f.length;++g)if(c<b||c<d&&f[g][1]<=e)a.remove(f[g][0]),c+=1;else break}}};
var gi=function(a){_.v(this,a,"acr:bcr",null)};_.q(gi,_.u);_.x("acr:bcr",gi);var hi=function(a){_.v(this,a,"acr:srs",null)};_.q(hi,_.u);_.x("acr:srs",hi);var ii=function(a){_.v(this,a,"acr:rss",null)};_.q(ii,_.u);_.x("acr:rss",ii);var ji=function(a){_.v(this,a,"acr:rrs",null)};_.q(ji,_.u);_.x("acr:rrs",ji);var ki=function(a){_.v(this,a,"acr:rsr",null)};_.q(ki,_.u);_.x("acr:rsr",ki);_.mi=function(a){_.v(this,a,"acr:wrs",li)};_.q(_.mi,_.u);var li=[1];_.x("acr:wrs",_.mi); var ni=function(a){_.v(this,a,0,null)};_.q(ni,_.u);ni.prototype.T=function(){return _.w(this,2)};ni.prototype.ja=function(){return _.w(this,11)};
var ri;_.pi=function(a){_.v(this,a,"acq:rs",oi)};_.q(_.pi,_.u);var oi=[3];_.x("acq:rs",_.pi);var qi=function(a){_.v(this,a,0,null)};_.q(qi,_.u);qi.prototype.getState=function(){return _.w(this,6)};_.Ch=function(a){_.v(this,a,0,null)};_.q(_.Ch,_.u);_.Ch.prototype.ka=function(){return _.ed(this,qi,1)};ri=function(a,b){_.dd(a,1,b)};_.si=function(a){_.v(this,a,0,null)};_.q(_.si,_.u);_.si.prototype.T=function(){return _.w(this,1)};var ti=function(a,b){_.K(a,1,b)}; _.si.prototype.ka=function(){return _.ed(this,qi,2)};var ui=function(a,b){_.dd(a,2,b)};_.si.prototype.ja=function(){return _.w(this,3)};var vi=function(a,b){_.K(a,3,b)};
var wi,Ai,zi;wi=function(a){this.c=a;this.a={};this.b=a.get(_.Pg)};_.xi=function(a,b){return(null!=a?a:"null")+"-"+(null!=b?b:"null")};
Ai=function(a,b){_.O(a.reload,6E4,a);var c=[],d={},e=a.c.get(_.Ng),f=_.oh(b,ni,1)||[];(0,_.ta)(f,function(a){c.push(_.w(a,1));var b=_.xi(a.T(),a.ja());d[b]=a});var g=c.length;c.push("viewer");yi(e,c,(0,_.r)(function(a){for(var c=[],e=0;e<f.length;e++){var E=a[e];if(E){var Y=f[e],R=new _.si;vi(R,Y.ja());ti(R,Y.T());ui(R,zi(E));c.push(R)}}ph(c,function(a,b){var c=b.ka(),c=_.w(c,2),d;d=a.ka();d=_.w(d,2);return c-d});(0,_.ta)(c,function(a,b){var c=_.xi(a.T(),a.ja());_.K(d[c],3,b)});a=a[g];e=new _.pi;
a&&(E=new _.Ch,ri(E,zi(a)),_.dd(e,2,E));nh(e,3,c);nh(b,1,f);_.dd(e,1,b);this.b.set("ReloadState",e.H);_.S.a().b("eventReloadStateSaved",[])},a))};zi=function(a){var b=new qi;_.K(b,1,a.top);_.K(b,2,a.left);_.K(b,3,a.width);_.K(b,4,a.height);_.K(b,5,a.focused);_.K(b,6,a.state);_.K(b,7,a.alwaysOnTop);return b};wi.prototype.read=function(){var a=this.l;this.l=null;_.S.a().b("eventReloadStateRead",[a&&a.H||null])};wi.prototype.reload=function(){window.chrome.runtime.reload()};
_.V=function(a){this.a=new wi(a);this.b=a;window.chrome.runtime.onUpdateAvailable.addListener((0,_.r)(this.l,this))};_.ga("ace.core.ExtensionLibrary",_.V);_.V.prototype.l=function(){_.S.a().b("eventReloadClient",[]);_.O(this.a.reload,864E5+288E5*Math.random(),this.a)};_.V.prototype.gc=function(a,b,c,d){a=_.S.b(b);null!=a&&_.n(d)&&d&&(d=a.j,null!=d&&null!=d.id&&(window.chrome.tabs.update(d.id,{selected:!0}),c&&window.chrome.tabs.get(d.id,function(a){_.Ug(a.windowId)})))};_.V.prototype.selectTab=_.V.prototype.gc;
_.V.prototype.$b=function(a,b,c){c?bh(b,"width=500,height=400"):window.chrome.tabs.create({url:b,selected:!0},function(a){null!=a?_.O(function(){window.chrome.tabs.get(a.id,function(a){_.Ug(a.windowId)})},2E3):bh(b)})};_.V.prototype.openUrl=_.V.prototype.$b;_.V.prototype.Gb=function(a,b){this.c=this.b.get(_.Ng);this.c.focus(b)};_.V.prototype.focusMoleByFrameId=_.V.prototype.Gb;_.V.prototype.la=function(){_.S.a().la()};_.V.prototype.showApplication=_.V.prototype.la;
_.V.prototype.fc=function(a,b){var c=new _.mi(b);Ai(this.a,c)};_.V.prototype.saveReloadState=_.V.prototype.fc;_.V.prototype.ac=function(){this.a.read()};_.V.prototype.readReloadState=_.V.prototype.ac;_.V.prototype.dc=function(){this.a.reload()};_.V.prototype.reloadExtension=_.V.prototype.dc;_.V.prototype.Ca=function(){_.S.a().Ca()};_.V.prototype.onHostReady=_.V.prototype.Ca;
var Bi=function(a,b){if(a)this.focused=a.focused,this.alwaysOnTop=a.alwaysOnTop,this.top=a.top,this.left=a.left,this.width=a.width,this.height=a.height,this.state=a.state;else if(b){this.focused=b.contentWindow.document.hasFocus();this.alwaysOnTop=b.isAlwaysOnTop();var c=b.getBounds();this.top=c.top;this.left=c.left;this.width=c.width;this.height=c.height;this.state=b.isMinimized()?"minimized":"normal"}else this.alwaysOnTop=this.focused=!1,this.height=this.width=this.left=this.top=0,this.state=""}; Bi.prototype.isMinimized=function(){return"minimized"==this.state};
var Ci=function(a,b,c){this.a=c||new Bi;c||(this.a.alwaysOnTop=Rg(a.get(_.Og).a))};Ci.prototype.getProperties=function(){return this.a};var Ei=function(a,b,c){(b=b.g)?Di(a.get(_.Ng),b,function(b){c(new Ci(a,0,b))}):c(new Ci(a))};_.X=function(a){_.C.call(this);this.j=a;this.a=new _.z;this.h=new _.z;this.b=new ei;_.F(this,this.b);this.g=(0,_.r)(this.Ob,this);window.chrome.notifications.onClosed.addListener(this.g);this.c=(0,_.r)(this.rb,this);window.chrome.notifications.onClicked.addListener(this.c);this.f=(0,_.r)(this.Nb,this);window.chrome.notifications.onButtonClicked.addListener(this.f)};_.q(_.X,_.C);_.ga("ace.core.NotificationManager",_.X);
_.X.prototype.v=function(){_.ta(this.a.G(),_.D);this.a.clear();window.chrome.notifications.onClosed.removeListener(this.g);window.chrome.notifications.onClicked.removeListener(this.c);window.chrome.notifications.onButtonClicked.removeListener(this.f);_.X.B.v.call(this)};
_.X.prototype.cc=function(a,b){var c;if(b&&b.Content){c=[b.Id.ServiceUrl,b.Id.ServiceId].join(";");0==c.indexOf("bc")?c=new ai(c,2):0==c.indexOf("hangout")?(c=new ai(c,7),c.b.push(new bi("join hangout")),c.b.push(new bi("ignore"))):c=void 0;c.setTitle(b.Content.TitleText);c.h=b.Content.SubtitleText;c.l=b.Content.BodyText;c.c=b.Content.BodyTextId;var d=0;b.Content.EndTimeMs&&(d=b.Content.EndTimeMs,(0,window.isNaN)(d)||!(0,window.isFinite)(d))&&(d=0);d=d||(0,_.m)()+1E4;c.f=d;if(b.Content.ServiceIcon){var d=
c,e=b.Content.ServiceIcon;e&&(0==e.indexOf("images_4/")&&(e=window.chrome.runtime.getURL(e)),d.u=e)}b.Content.FrameId&&(c.g=b.Content.FrameId)}else c=null;c&&(_.S.a().b("eventReportImpression",[193]),fi(this.b,c)||(d=this.b,e=null!=c.c?c.a+c.c:null,null!=e&&!fi(d,c)&&d.b.set(e,(0,_.m)()+18E5),Fi(this,c)))};_.X.prototype.registerNotification=_.X.prototype.cc;
var Fi=function(a,b){2==b.j||b.g?Ei(a.j,b,function(c){c=c.getProperties();c.focused||c.alwaysOnTop||Gi(a,b)}):Gi(a,b)},Gi=function(a,b){var c=b.a,d=b.f-(0,_.m)();0>=d?a.bb(c):(a.a.set(c,b),window.chrome.notifications.create(c,di(b),function(){_.S.a().b("eventReportImpression",[192])}),_.Fd(a.h.get(c,null)),b.f!=Number.MAX_VALUE&&a.h.set(c,_.O((0,_.r)(a.bb,a,c),d)),_.S.a().b("eventReportImpression",[194]))};_.X.prototype.pa=function(){(0,_.ta)((0,_.ua)(this.a.G(),Sg),this.ia,this)};
_.X.prototype.cleanAllNotifications=_.X.prototype.pa;_.X.prototype.Ab=function(a,b){var c=this.a.get(b);c&&this.ia(c)};_.X.prototype.cleanANotification=_.X.prototype.Ab;_.h=_.X.prototype;_.h.ia=function(a){a=a.a;window.chrome.notifications.clear(a,_.na);this.a.remove(a)};_.h.Ob=function(a,b){b&&this.a.get(a)&&(this.a.remove(a),Hi(a,"toastEventOnClose"))};_.h.rb=function(a){var b=this.a.get(a);b&&(Hi(a,"toastEventOnBody"),this.ia(b))};
_.h.Nb=function(a,b){var c=this.a.get(a);c&&(Hi(a,"toastEventOnButton",c.b[b].name),this.ia(c))};_.h.bb=function(a){var b=this.a.get(a);b&&(Hi(a,"toastEventOnTimeout"),this.ia(b))};var Hi=function(a,b,c){var d=_.S;(d=d&&d.a())&&!d.L&&_.S.a().b(b,[a,c,"",!1])};
var Ii=function(){_.C.call(this);this.a=new lh};_.q(Ii,_.C);Ii.prototype.Z=function(a){var b,c=Array.prototype.slice.call(arguments);(0,_.ta)(this.a.G(),function(a){b=a.apply(null,c)});return b};Ii.prototype.addListener=function(a){this.a.a.set(Zg(a),a)};Ii.prototype.removeListener=function(a){this.a.remove(a)};Ii.prototype.v=function(){this.a.clear();Ii.B.v.call(this)};
var Ji=function(a){return(a=a.exec(_.Ha))?a[1]:""};(function(){if(_.Gd)return Ji(/Firefox\/([0-9.]+)/);if(_.B||_.Qa||_.Pa)return _.Xa;if(_.Kd)return Ji(/Chrome\/([0-9.]+)/);if(_.Ld&&!(_.Dd()||_.y("iPad")||_.y("iPod")))return Ji(/Version\/([0-9.]+)/);if(_.Hd||_.Id){var a;if(a=/Version\/(\S+).*Mobile\/(\S+)/.exec(_.Ha))return a[1]+"."+a[2]}else if(_.Jd)return(a=Ji(/Android\s+([0-9.]+)/))?a:Ji(/Version\/([0-9.]+)/);return""})();
var Mi=function(){_.C.call(this);this.b=[];this.j=new Ii;_.F(this,this.j);this.g=new Ii;_.F(this,this.g);this.onClosed=new Ii;this.h=!1;this.c=null;this.u=(0,_.r)(this.K,this);Ki.addListener(this.u);this.w=(0,_.r)(this.J,this);Li.addListener(this.w)};_.q(Mi,_.C);Mi.prototype.v=function(){Th(this)||void 0!=this.a&&window.chrome.windows.remove(this.a);Ni(this);this.u&&(Ki.removeListener(this.u),Li.removeListener(this.w));_.D(this.onClosed);Mi.B.v.call(this)};
var Ki=window.chrome.windows&&window.chrome.windows.onRemoved,Li=window.chrome.windows&&window.chrome.windows.onFocusChanged;Mi.prototype.create=function(a){window.chrome.windows.create(a,(0,_.r)(function(a){this.L?window.chrome.windows.remove(a.id):(this.a=a.id,Oi(this))},this))};
var Oi=function(a){if(null!=a.b&&Sh(a))if(Th(a))Ni(a);else{for(;a.b.length&&!Th(a);)a.b.shift()(a);a.b=null}},Sh=function(a){return!(!_.ka(a.a)||!a.f)},Fh=function(a,b){Th(a)?Ni(a):null==a.b?b(a):a.b.push(b)},Th=function(a){return!(!a.f||!a.f.closed)};Mi.prototype.K=function(){Th(this)&&Ni(this)};var Ni=function(a){if(!a.h){var b=a.onClosed;a.onClosed=new Ii;_.O((0,_.r)(function(){this.h||(this.h=!0,b.Z(this));_.D(b)},a))}};
Mi.prototype.J=function(a){if(a!=this.a){if(null===this.c||this.c)this.c&&(this.c=!1),this.g.Z(this)}else this.c=!0,this.j.Z(this)};var Ih=function(a){var b;b=a.a?a.f:null;return!b||Th(a)?null:b};_.h=Mi.prototype;_.h.isMinimized=function(){return this.D.isMinimized()};_.h.isMaximized=function(){return this.D.isMaximized()};_.h.minimize=function(){Fh(this,(0,_.r)(function(){window.chrome.windows.update(this.a,{state:"minimized"})},this))};
_.h.focus=function(){Fh(this,(0,_.r)(function(){window.chrome.windows.update(this.a,{focused:!0})},this))};_.h.drawAttention=function(a){Fh(this,(0,_.r)(function(){window.chrome.windows.update(this.a,{drawAttention:a})},this))};_.h.getProperties=function(a){Fh(this,_.ha(Pi,[this],function(b){a(b[0])}))}; var Pi=function(a,b){window.chrome.windows.getAll(function(c){var d={};(0,_.ta)(c,function(a){d[a.id]=a});var e=[];(0,_.ta)(a,function(a){var b;a&&Sh(a)&&!Th(a)&&(b=d[a.a]);var c;b&&(c=new Bi(b));e.push(c)});b(e)})};
var Qi=function(){Mi.call(this)};_.q(Qi,Mi);Qi.prototype.setTitle=function(a){Fh(this,(0,_.r)(function(){Ih(this).document.title=a},this))};
var Si=function(a,b){a.C=b;Fh(a,(0,_.r)(function(){Ri(this)},a))},Ti=function(a,b){a.I=b;Fh(a,(0,_.r)(function(){Ri(this)},a))},Ri=function(a){var b=Ih(a).document,c=b.querySelector("HEAD"),d=c.querySelectorAll("link[rel='shortcut icon']"),e=ch("icon-24x24.png");a=[a.C||e,a.I];for(var e=_.sc()?2:1,f="",g=0;g<e;++g)if(a[g]&&a!=f){var f=a[g],k=d[g];k||(k=b.createElement("LINK"),c.appendChild(k));k.rel="shortcut icon";var p=a[g];k.type=Wg(p,".ico")?"image/x-icon":Wg(p,".gif")?"image/gif":"image/png"; k.href=a[g]}};
var Wi,Xi;_.Vi=function(a){this.a={};if(a)for(var b=0;b<a.length;b++)this.a[_.Ui(a[b])]=null;for(var c in Object.prototype);};Wi={};_.Ui=function(a){return a in Wi||32==String(a).charCodeAt(0)?" "+a:a};Xi=function(a){return 32==a.charCodeAt(0)?a.substr(1):a};_.h=_.Vi.prototype;_.h.clear=function(){this.a={}};_.h.clone=function(){var a=new _.Vi,b;for(b in this.a)a.a[b]=null;return a};_.h.contains=function(a){return _.Ui(a)in this.a};
_.h.forEach=function(a,b){for(var c in this.a)a.call(b,Xi(c),void 0,this)};_.h.ea=Object.keys?function(){return Object.keys(this.a).length}:function(){var a=0,b;for(b in this.a)a++;return a};_.h.G=Object.keys?function(){return Object.keys(this.a).map(Xi,this)}:function(){var a=[],b;for(b in this.a)a.push(Xi(b));return a};_.h.aa=function(){for(var a in this.a)return!1;return!0};_.h.remove=function(a){a=_.Ui(a);return a in this.a?(delete this.a[a],!0):!1};_.h.$=function(){return $g(this.G())};
_.Z=function(a){_.C.call(this);this.f=a;this.a={};this.c={};this.b=new _.Vi;_.ga("__onPanelLoad",(0,_.r)(this.A,this));this.h=a.get(_.Jg);a=new _.H(this);_.F(this,a);a.listen(_.S,"onStatusChange",this.j)};_.q(_.Z,_.C);_.ga("ace.core.PanelsManager",_.Z);_.Z.prototype.v=function(){for(var a in this.a)this.ta(this.a[a]);_.Z.B.v.call(this)};
_.Z.prototype.isMaximized=function(a,b){var c=function(a){a=a?!a.isMinimized():null;_.S.a().b("eventIsMinimizedResponse",[b,a])},d=this.a[b];d?d.getProperties(c):c(void 0)};_.Z.prototype.isMaximized=_.Z.prototype.isMaximized;
_.Z.prototype.Yb=function(a,b,c,d,e,f,g,k,p,A){a="panel.html?"+b;d=d||window.chrome.i18n.getMessage("CHROME_EXT_SHORT_NAME");b=Bh(this,b,k||b,a,d,e,g);Fh(b,(0,_.r)(this.g,this,c));c=new _.Ff(280,420);p||A?(p=p||null,e=A||null,A=this.f.get(_.Kg).a,p=_.xi(p,e),(e=A.a[p])&&delete A.a[p],A=e?e.ka():null):A=null;f=Dh(this,c,!!f,A);Eh(this,b.id,f)};_.Z.prototype.openPanel=_.Z.prototype.Yb;
_.Z.prototype.openDialog=function(a,b,c,d,e,f,g){a="dialog.html?"+b;d=d||window.chrome.i18n.getMessage("CHROME_EXT_SHORT_NAME");b=Bh(this,b,b,a,d);Fh(b,(0,_.r)(this.g,this,c));c=Dh(this,new _.Ff(f,g),e,null);c.cb=!0;Eh(this,b.id,c);return b};_.Z.prototype.openDialog=_.Z.prototype.openDialog;_.Z.prototype.Zb=function(a,b,c,d,e,f,g){d=d||window.chrome.i18n.getMessage("CHROME_EXT_SHORT_NAME");a=Bh(this,b,b,c,d);e=Dh(this,new _.Ff(f,g),e,null);e.cb=!0;Eh(this,a.id,e);return a};
_.Z.prototype.openSimplePopup=_.Z.prototype.Zb;var Bh=function(a,b,c,d,e,f,g){a.a[b]&&a.ta(a.a[b]);var k=new Qi;k.id=b;k.key=c;k.url=d;k.setTitle(e);Si(k,f);Ti(k,g);a.a[b]=k;a.c[c]=b;return k};_.Z.prototype.g=function(a,b){b.A=new sh(a,Ih(b).document);_.F(b,b.A)};
var Dh=function(a,b,c,d){b={focus:c,ha:null,width:b.width,height:b.height,minimize:!1};if(d){b.top=_.w(d,1);b.left=_.w(d,2);c=_.w(d,3);var e=_.w(d,4);_.w(d,7)?(b.width=Math.max(b.width,c),b.height=Math.max(b.height,e)):(b.width=c,b.height=e);"minimized"==d.getState()&&(b.minimize=!0);b.ha=_.w(d,7);b.focus=_.w(d,5)}b.ha="boolean"==typeof b.ha?b.ha:Rg(a.f.get(_.Og).a);return b},Eh=function(a,b,c){var d=a.a[b];d.onClosed.addListener((0,_.r)(a.ta,a));d.j.addListener((0,_.r)(a.w,a));d.g.addListener((0,_.r)(a.u,
a));c.minimize&&d.minimize();b="panel";c.ha||(b=Yg()?"popup":"detached_panel");c.cb&&(b="popup");var e={type:b,url:d.url,focused:c.focus,width:c.width,height:c.height};if(b=null!=c.top&&null!=c.left)e.top=c.top,e.left=c.left;b||c.ha?d.create(e):yi(a,Object.keys(a.c),(0,_.r)(function(a){var b=window.screen,c;c=new _.Ff(260,460);var p=new _.Ff(280,420);c=new _.Ff(Math.max(c.width,p.width),Math.max(c.height,p.height));for(var A=b.availWidth,E=b.availHeight-50,p=b.availTop+E%c.height,b=b.availLeft+A%
c.width,A=Math.floor(A/c.width),Y=Math.floor(E/c.height),E=Array(A*Y),R=0;R<a.length;R++){var W=a[R];if(W){for(var Oa=[W.left,W.left+W.width-1],W=[W.top,W.top+W.height-1],aa=0;2>aa;aa++)Oa[aa]=Math.floor(Math.max(0,Oa[aa]-b)/c.width),W[aa]=Math.floor(Math.max(0,W[aa]-p)/c.height);for(aa=Oa[0];aa<=Oa[1];aa++)for(var Fa=W[0];Fa<=W[1];Fa++)aa<A&&Fa<Y&&(E[aa+Fa*A]=1)}}a=E.length-1;for(R=E.length-1;0<=R;R--)if(!E[R]){a=R;break}E=a%A*c.width;e.top=p+Math.floor(a/A)*c.height+(c.height-e.height);e.left=b+
E+(c.width-e.width);d.create(e)},a))};_.Z.prototype.ya=function(a,b){var c=this.a[b];c&&_.D(c)};_.Z.prototype.closePanel=_.Z.prototype.ya;_.Z.prototype.xa=function(){for(var a in this.a)0==this.a[a].url.indexOf("panel.html")&&this.ya(0,a)};_.Z.prototype.closeAllPanels=_.Z.prototype.xa;_.Z.prototype.setTitle=function(a,b,c){(a=this.a[b])&&a.setTitle(c)};_.Z.prototype.setTitle=_.Z.prototype.setTitle;_.Z.prototype.drawAttention=function(a,b,c){this.a[b]&&this.a[b].drawAttention(c)};
_.Z.prototype.drawAttention=_.Z.prototype.drawAttention;_.Z.prototype.focus=function(a){if(this.a[a]){var b=this.a[a];b.getProperties((0,_.r)(function(a){if(a&&(a=Ih(b),0==a.outerWidth&&0==a.outerHeight)){this.ta(b);return}b.focus()},this))}};_.Z.prototype.jc=function(a,b,c){this.a[b]&&Si(this.a[b],c)};_.Z.prototype.setPresence=_.Z.prototype.jc;_.Z.prototype.hc=function(a,b,c){this.a[b]&&Ti(this.a[b],c)};_.Z.prototype.setAvatar=_.Z.prototype.hc;
_.Z.prototype.ra=function(a,b,c){for(var d in this.a)(b||this.b.contains(d))&&this.eb(0,d,b,c);b||this.b.clear()};_.Z.prototype.minimizeAllPanelsIfTopmost=_.Z.prototype.ra;
_.Z.prototype.eb=function(a,b,c,d){var e=this.a[b];e&&e.getProperties((0,_.r)(function(a){if(a&&a.alwaysOnTop&&!this.L)if(c){var g;(g=!d)||(g=new _.dh(a.left,a.top,a.width,a.height),g=g.left<=d.left+d.width&&d.left<=g.left+g.width&&g.top<=d.top+d.height&&d.top<=g.top+g.height);g&&!a.isMinimized()&&(e.minimize(),this.b.a[_.Ui(b)]=null)}else window.chrome.windows.update(e.a,{state:"normal"}),this.b.remove(b)},this))};_.Z.prototype.minimizePanelIfTopmost=_.Z.prototype.eb;
_.Z.prototype.A=function(a){var b=this.a[a.location.search.substring(1)];b&&(b.f=a,Oi(b))};var Di=function(a,b,c){a=a.a[a.c[b]];!a||Th(a)?c(void 0):a.getProperties(c)},yi=function(a,b,c){var d=[];(0,_.ta)(b,(0,_.r)(function(a){d.push(this.a[this.c[a]])},a));Pi(d,c)};_.Z.prototype.ta=function(a){this.a[a.id]==a&&(this.b.remove(a.id),delete this.c[a.key],delete this.a[a.id],_.D(a))};_.Z.prototype.w=function(a){this.a[a.id]==a&&this.b.remove(a.id)}; _.Z.prototype.u=function(a){this.a[a.id]==a&&_.S.a().b("eventBlurred",[a.id])};_.Z.prototype.j=function(){3==this.h.a&&this.xa()};

}catch(e){_._DumpException(e)}
try{
var Yi=function(a,b){a.c.get(_.Ig).va(0,b)},Zi=function(a){var b=a.b.get("ReloadState");_.ma(b)&&"acq:rs"==b[0]&&(a.b.remove("ReloadState"),b=new _.pi(b),a.l=_.ed(b,_.mi,1),a.a={},_.oh(b,_.si,3)&&(0,_.ta)(_.oh(b,_.si,3),function(a){var b=_.xi(a.T(),a.ja());this.a[b]=a},a),_.ed(b,_.Ch,2)&&Yi(a,b))},$i=function(a){var b=a.a;a.a=a.g;a.g=b;b=a.l;a.l=a.f;a.f=b},aj={a:/^https?:\/\/.*.google.com(:[0-9]+)?\/hangouts\/_\/.*/},bj=function(a){var b=[];null!=a&&(b=a.split("_;_"));if(2>b.length){a=2-b.length;
for(var c=0;c<a;++c)b.push("")}return b},cj=function(a){_.C.call(this);this.f=a;this.a=new _.Vi;this.b=(0,_.r)(this.j,this);this.c=(0,_.r)(this.u,this);this.g=(0,_.r)(this.h,this);window.chrome.tabs.onCreated.addListener(this.b);window.chrome.tabs.onUpdated.addListener(this.c);window.chrome.tabs.onRemoved.addListener(this.g)};_.q(cj,_.C);
cj.prototype.v=function(){window.chrome.tabs.onCreated.removeListener(this.b);window.chrome.tabs.onUpdated.removeListener(this.c);window.chrome.tabs.onRemoved.removeListener(this.g);delete this.b;delete this.c;delete this.g;cj.B.v.call(this)};cj.prototype.j=function(a){a.url&&dj(this,a.id,a.windowId,a.url)};cj.prototype.u=function(a,b,c){b.url&&dj(this,a,c.windowId,b.url)};cj.prototype.h=function(a){a=a.toString();this.a.contains(a)&&(this.a.remove(a),this.a.aa()&&this.f.ra(0,!1))};
var dj=function(a,b,c,d){b=b.toString();if(!a.a.contains(b))for(var e in aj)if(aj[e].test(d)){a.a.a[_.Ui(b)]=null;window.chrome.windows.get(c,(0,_.r)(function(a){a&&!this.L&&this.f.ra(0,!0,new _.dh(a.left,a.top,a.width,a.height))},a));_.Ug(c);break}},ej=function(){_.I.call(this);this.c=new _.H(this);_.F(this,this.c);this.a=new _.ih;_.F(this,this.a);this.g=(0,_.r)(this.h,this);this.f=(0,_.r)(this.b,this);window.chrome.idle.setDetectionInterval(300);this.b();window.chrome.idle.onStateChanged.addListener(this.f);
this.a.setInterval(2E4);this.c.listen(this.a,"tick",this.b);_.jh(this.a)};_.q(ej,_.I);ej.prototype.v=function(){window.chrome.idle.onStateChanged.removeListener(this.f);ej.B.v.call(this)};ej.prototype.h=function(a){var b=_.S;switch(a){case "idle":case "locked":b.a().b("onIdleStateIdle",["i"]);break;case "active":b.a().b("onIdleStateActive",["a"])}};ej.prototype.b=function(){window.chrome.idle.queryState(300,this.g)};var fj=function(a,b){_.hb.call(this,a);this.message=b};_.q(fj,_.hb);
var gj=function(a){_.C.call(this);this.a=a;this.b=a.name;this.c=!0;this.j=null;_.n(a.sender)&&null!=a.sender.tab&&(this.j=a.sender.tab);this.f=null;this.g=(0,_.r)(this.sb,this);this.h=(0,_.r)(this.Wa,this)};_.q(gj,_.C);_.h=gj.prototype;_.h.v=function(){gj.B.v.call(this);this.Wa()};_.h.fa=function(){return bj(this.b)[1]};_.h.sendMessage=function(a){if(null==a||null==a.message||!this.a||!this.c)return!1;a=a.message();this.a.postMessage(a);return!0};
_.h.sb=function(a){var b=this.f;a=_.tc(new _.J,a);if(null!=a&&null!=a.a)try{switch(a.f){case "e":var c=b.g.c(_.Lg);if(null!=c)a:try{var d;switch(a.h){case "dataChannelManager":d=_.Ig;break;case "desktopManager":d=_.Jg;break;case "extensionLibrary":d=_.Kg;break;case "notificationManager":d=_.Mg;break;case "panelsManager":d=_.Ng;break;case "settingsManager":d=_.Og;break;case "viewAreaManager":d=_.Qg;break;default:break a}var e=a.c;if(null!=e){var f=c.a.get(d),g=[].concat(a.b),k=g.shift();if(_.ja(f[k])){b=
{};b.source=a.a;b.sourceType=a.l;b.callbackId=e;g.unshift(b);var p=f[k].apply(f,g);if("delayedResponseCode"!=p){var A=_.S.b(a.a);$i(a);_.wc(a,p);hj(A,a)}}}}catch(hh){var E=_.S.b(a.a);if(null!=E&&E.c){var Y=a.c;$i(a);_.vc(a,"onError");_.wc(a,[Y,hh]);E.sendMessage(a)}}break;case "p":case "c":switch(a.j){case "u":var R=b.b(a.target());hj(R,a);break;case "m":var e=[],W=bj(a.target()),Oa;for(Oa in b.c)W[0]==bj(b.b(Oa).b)[0]&&e.push(b.b(Oa));ij(e,a);break;case "b":for(var aa in b.c){var Fa=b.b(aa);null!=
Fa&&Fa.c&&(_.bd(a,Fa.b),Fa.sendMessage(a))}break;default:throw"Unknown RouteType.";}break;default:throw"Unknown TargetType.";}}catch(hh){}};_.h.Wa=function(){if(this.a){var a=this.f,b=this.b;a.b(b)&&(delete a.c[b],a=a.a(),"viewer"==bj(b)[0]&&a.b("eventViewerClosed",[]))}this.a&&(this.a.onMessage.removeListener(this.g),this.a.onDisconnect.removeListener(this.h),delete this.a);delete this.g;delete this.h;delete this.j;delete this.f;delete this.c};
var jj=function(a){_.I.call(this);this.a=a;this.c=null;this.f=(0,_.r)(this.Qb,this);this.g=(0,_.r)(this.Vb,this);this.a.a(_.Pg,_.Cc.fa());a=new _.vh(this.a);this.a.a(_.Og,a);a=new _.V(this.a);this.a.a(_.Kg,a);a=new _.X(this.a);this.a.a(_.Mg,a);this.c=new _.U(this.a);this.a.a(_.Jg,this.c);a=new _.Z(this.a);this.a.a(_.Ng,a);var b=new _.T(this.a);this.a.a(_.Ig,b);window.chrome.browserAction.onClicked.addListener((0,_.r)(this.ib,this));window.chrome.runtime.onMessageExternal.addListener((0,_.r)(this.Tb,
this));window.chrome.runtime.onConnectExternal.addListener((0,_.r)(this.Pb,this));window.chrome.hangoutsPrivate&&window.chrome.hangoutsPrivate.onHangoutRequested&&window.chrome.hangoutsPrivate.onHangoutRequested.addListener((0,_.r)(this.Sb,this));a.ya(0,"viewer");a=new cj(a);this.a.a(_.Qg,a);this.h=new ej;_.F(this,this.h);this.a.a(_.Lg,this)};_.q(jj,_.I);jj.prototype.b=function(a,b){var c;c=kj(a,b);c=JSON.stringify(c.message());lj(_.S,"onSendHostMessage",kj("onSendHostMessage",c))};
var kj=function(a,b){var c=new _.J("p");_.vc(c,a);_.wc(c,b);_.uc(c,"","e");return c};_.h=jj.prototype;_.h.Sb=function(a){var b=this.c.h()&&4==this.c.a&&(this.c.f||"")||"";!b||b!==a.from||1>a.to.length||lj(_.S,"onOpenConversation",kj("onOpenConversation",a.to[0].id))};_.h.ib=function(){var a=this.a.get(_.Ig);a.j||_.Rh(a);this.la()};_.h.Tb=function(a,b,c){"icjglmbkgdgdgdigllcokdabceikdppi"==b.id&&(this.ib(),c(a))};
_.h.Vb=function(a,b){var c=this.c.h()&&(this.c.f||"")||"";switch(a.eventType){case "getCentralJid":b.postMessage({jid:c});break;case "ocbek":case "ocfp":case "showChat":case "po":if(!c)break;this.b("eoc",[a.eventType,a.jid]);break;case "mmm":var c=this.a.get(_.Qg),d=_.t(a.jid)?JSON.parse(a.jid):[];if(!b.sender.tab)break;var e=b.sender.tab;if(d.length){var f;4==d.length&&(f=new _.dh(d[0],d[1],d[2],d[3]));c.a.a[_.Ui(e.id.toString())]=null;c.f.ra(0,!0,f)}else c.h(e.id)}};
_.h.Pb=function(a){a.onMessage.addListener(this.g);a.onDisconnect.addListener(this.f)};_.h.Qb=function(a){a.onMessage.removeListener(this.g);a.onDisconnect.removeListener(this.f)};_.h.Da=function(){this.a.get(_.Ig).Da();this.a.get(_.Jg).ca(0,1)};_.h.la=function(){this.a.get(_.Ig).va()};_.h.Ca=function(){lj(_.S,"h_icr",kj("h_icr",[window.chrome.runtime.id]))};var mj=function(a){_.I.call(this);this.g=a;this.c={}};_.q(mj,_.I);mj.prototype.a=function(){return this.g.get(_.Lg)};
var nj=function(){window.chrome.runtime.onConnect.addListener(function(a){var b=_.S,c=a.name;a=new gj(a);a.f=b;a.a.onMessage.addListener(a.g);a.a.onDisconnect.addListener(a.h);b.c[""+c]=a});window.chrome.runtime.onMessage.addListener(function(a){var b=_.S;a=_.tc(new _.J,a);if(null!=a)switch(b=b.a(),a.c){case "changeDesktop":b.c.ca(0,a.b[0])}})};mj.prototype.b=function(a){return null!=a?this.c[a]:null};mj.prototype.f=function(a){var b=[],c;for(c in this.c)bj(this.b(c).b)[0]==a&&b.push(c);return b};
var hj=function(a,b){null!=a&&a.c&&(_.bd(b,a.b),a.sendMessage(b))},ij=function(a,b){for(var c=0;c<a.length;c++){var d=a[c];null!=d&&d.c&&(_.bd(b,d.b),d.sendMessage(b))}};mj.prototype.h=function(){_.L(this,new fj("onStatusChange",new _.J))};
var lj=function(a,b,c){var d=_.S.f("quasar");if(null!=b&&null!=c&&null!=d&&!(1>d.length)){c.j="u";_.vc(c,b);b=[];for(var e=0;e<d.length;e++)a.b(d[e])&&b.push(a.b(d[e]));ij(b,c)}},oj,pj=function(){var a=new _.Rc;oj=a;var b=new mj(a);null==_.S&&null!=b&&(_.S=b);b=new jj(a);nj();var c=!1,d=a.get(_.Pg);null==d.a.get("has_installed")&&(d.set("has_installed",!0),c=!0);if((a=a.get(_.Og).a.a.get("StartOnBrowserLaunch"))&&a.Y&&a.F()||null!=d.a.get("ReloadState"))a=c,c=b.a.get(_.Ig),_.Rh(c),a?c.va():(b=b.a.get(_.Kg), Zi(b.a))};window.addEventListener("load",function(){_.Cc.fa().U(pj)},!1);window.addEventListener("beforeunload",function(){_.S.a().a.get(_.Mg).pa();_.D(oj);oj=void 0},!1);

}catch(e){_._DumpException(e)}
}).call(this,this.default_extension);
// Google Inc.
