"use strict";this.default_settings=this.default_settings||{};(function(_){var window=this;
try{
_.ba=_.ba||{};_.l=this;_.ca="closure_uid_"+(1E9*Math.random()>>>0);_.m=Date.now||function(){return+new Date};
}catch(e){_._DumpException(e)}
try{
var da,ea,fa;_.n=function(a){return void 0!==a};da=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};ea=function(a,b,c){return a.call.apply(a.bind,arguments)};
fa=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};_.q=function(a,b){function c(){}c.prototype=b.prototype;a.B=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.qc=function(a,c,f){for(var g=Array(arguments.length-2),k=2;k<arguments.length;k++)g[k-2]=arguments[k];return b.prototype[c].apply(a,g)}};
_.ga=function(a,b){var c=a.split("."),d=_.l;c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&_.n(b)?d[e]=b:d[e]?d=d[e]:d=d[e]={}};_.ha=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}};_.r=function(a,b,c){_.r=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ea:da;return _.r.apply(null,arguments)};
_.ia=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};_.ja=function(a){return"function"==fa(a)};_.ka=function(a){return"number"==typeof a};_.t=function(a){return"string"==typeof a};_.la=function(a){var b=fa(a);return"array"==b||"object"==b&&"number"==typeof a.length};_.ma=function(a){return"array"==fa(a)};_.na=function(){};_.oa=function(a,b){for(var c=a.split("."),d=b||_.l,e;e=c.shift();)if(null!=d[e])d=d[e];else return null;return d}; _.pa=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,_.pa);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))};_.q(_.pa,Error);_.pa.prototype.name="CustomError";
var qa=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},ra=function(a,b){return a<b?-1:a>b?1:0};_.sa=Array.prototype.indexOf?function(a,b,c){return Array.prototype.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(_.t(a))return _.t(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};_.ta=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.t(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)};
_.ua=Array.prototype.filter?function(a,b,c){return Array.prototype.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,g=_.t(a)?a.split(""):a,k=0;k<d;k++)if(k in g){var p=g[k];b.call(c,p,k,a)&&(e[f++]=p)}return e};_.va=Array.prototype.map?function(a,b,c){return Array.prototype.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=_.t(a)?a.split(""):a,g=0;g<d;g++)g in f&&(e[g]=b.call(c,f[g],g,a));return e};
_.wa=Array.prototype.some?function(a,b,c){return Array.prototype.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.t(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return!0;return!1};_.xa=function(a,b){var c=(0,_.sa)(a,b),d;(d=0<=c)&&Array.prototype.splice.call(a,c,1);return d};
_.ya=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;var Aa;_.za=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)};Aa=function(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b};_.Ba=function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b};var Da;_.u=function(){};_.v=function(a,b,c,d){a.a=null;b||(b=c?[c]:[]);a.A=c?String(c):void 0;a.c=0===c?-1:0;a.H=b;a:{if(a.H.length&&(b=a.H.length-1,(c=a.H[b])&&"object"==typeof c&&!_.ma(c))){a.l=b-a.c;a.b=c;break a}a.l=Number.MAX_VALUE}if(d)for(b=0;b<d.length;b++)c=d[b],c<a.l?(c+=a.c,a.H[c]=a.H[c]||_.Ca):a.b[c]=a.b[c]||_.Ca};_.Ca=[];_.w=function(a,b){if(b<a.l){var c=b+a.c,d=a.H[c];return d===_.Ca?a.H[c]=[]:d}d=a.b[b];return d===_.Ca?a.b[b]=[]:d};_.u.prototype.toString=function(){return this.H.toString()}; _.x=function(a,b){Da[a]=b;b.messageId=a};Da={};
_.Ea="StopIteration"in _.l?_.l.StopIteration:{message:"StopIteration",stack:""};_.Ga=function(){};_.Ga.prototype.next=function(){throw _.Ea;};_.Ga.prototype.$=function(){return this};a:{var Ia=_.l.navigator;if(Ia){var Ja=Ia.userAgent;if(Ja){_.Ha=Ja;break a}}_.Ha=""}_.y=function(a){return-1!=_.Ha.indexOf(a)};_.Ka=function(){return _.y("Opera")||_.y("OPR")};_.z=function(a,b){this.b={};this.a=[];this.l=this.c=0;var c=arguments.length;if(1<c){if(c%2)throw Error("f");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a){a instanceof _.z?(c=a.M(),d=a.G()):(c=_.Ba(a),d=Aa(a));for(var e=0;e<c.length;e++)this.set(c[e],d[e])}};_.h=_.z.prototype;_.h.ea=function(){return this.c};_.h.G=function(){La(this);for(var a=[],b=0;b<this.a.length;b++)a.push(this.b[this.a[b]]);return a};_.h.M=function(){La(this);return this.a.concat()};
_.h.aa=function(){return 0==this.c};_.h.clear=function(){this.b={};this.l=this.c=this.a.length=0};_.h.remove=function(a){return _.Ma(this.b,a)?(delete this.b[a],this.c--,this.l++,this.a.length>2*this.c&&La(this),!0):!1};var La=function(a){if(a.c!=a.a.length){for(var b=0,c=0;b<a.a.length;){var d=a.a[b];_.Ma(a.b,d)&&(a.a[c++]=d);b++}a.a.length=c}if(a.c!=a.a.length){for(var e={},c=b=0;b<a.a.length;)d=a.a[b],_.Ma(e,d)||(a.a[c++]=d,e[d]=1),b++;a.a.length=c}};_.h=_.z.prototype;
_.h.get=function(a,b){return _.Ma(this.b,a)?this.b[a]:b};_.h.set=function(a,b){_.Ma(this.b,a)||(this.c++,this.a.push(a),this.l++);this.b[a]=b};_.h.forEach=function(a,b){for(var c=this.M(),d=0;d<c.length;d++){var e=c[d],f=this.get(e);a.call(b,f,e,this)}};_.h.clone=function(){return new _.z(this)};_.h.$=function(a){La(this);var b=0,c=this.l,d=this,e=new _.Ga;e.next=function(){if(c!=d.l)throw Error("g");if(b>=d.a.length)throw _.Ea;var e=d.a[b++];return a?e:d.b[e]};return e}; _.Ma=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
_.Na=function(a){if(a.G&&"function"==typeof a.G)return a.G();if(_.t(a))return a.split("");if(_.la(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return Aa(a)};var Ta,Va,Wa,Ya,$a,ab;_.Pa=_.Ka();_.B=_.y("Trident")||_.y("MSIE");_.Qa=_.y("Edge");_.Ra=_.y("Gecko")&&!(-1!=_.Ha.toLowerCase().indexOf("webkit")&&!_.y("Edge"))&&!(_.y("Trident")||_.y("MSIE"))&&!_.y("Edge");_.Sa=-1!=_.Ha.toLowerCase().indexOf("webkit")&&!_.y("Edge");Ta=_.l.navigator||null;_.Ua=Ta&&Ta.platform||"";Va=function(){var a=_.Ha;if(_.Ra)return/rv\:([^\);]+)(\)|;)/.exec(a);if(_.Qa)return/Edge\/([\d\.]+)/.exec(a);if(_.B)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(_.Sa)return/WebKit\/(\S+)/.exec(a)};
Wa=function(){var a=_.l.document;return a?a.documentMode:void 0};_.Xa=function(){if(_.Pa&&_.l.opera){var a;var b=_.l.opera.version;try{a=b()}catch(c){a=b}return a}a="";(b=Va())&&(a=b?b[1]:"");return _.B&&(b=Wa(),b>(0,window.parseFloat)(a))?String(b):a}();Ya={};
_.Za=function(a){var b;if(!(b=Ya[a])){b=0;for(var c=qa(String(_.Xa)).split("."),d=qa(String(a)).split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var g=c[f]||"",k=d[f]||"",p=RegExp("(\\d*)(\\D*)","g"),A=RegExp("(\\d*)(\\D*)","g");do{var E=p.exec(g)||["","",""],Y=A.exec(k)||["","",""];if(0==E[0].length&&0==Y[0].length)break;b=ra(0==E[1].length?0:(0,window.parseInt)(E[1],10),0==Y[1].length?0:(0,window.parseInt)(Y[1],10))||ra(0==E[2].length,0==Y[2].length)||ra(E[2],Y[2])}while(0==b)}b=Ya[a]= 0<=b}return b};$a=_.l.document;ab=$a&&_.B?Wa()||("CSS1Compat"==$a.compatMode?(0,window.parseInt)(_.Xa,10):5):void 0;
_.C=function(){this.L=this.L;this.l=this.l};_.C.prototype.L=!1;_.C.prototype.O=function(){this.L||(this.L=!0,this.v())};_.F=function(a,b){_.bb(a,_.ha(_.D,b))};_.bb=function(a,b){a.L?b.call(void 0):(a.l||(a.l=[]),a.l.push(_.n(void 0)?(0,_.r)(b,void 0):b))};_.C.prototype.v=function(){if(this.l)for(;this.l.length;)this.l.shift()()};_.D=function(a){a&&"function"==typeof a.O&&a.O()};
_.cb=!_.B||9<=ab;!_.Ra&&!_.B||_.B&&9<=ab||_.Ra&&_.Za("1.9.1");_.B&&_.Za("9");var db=function(a){db[" "](a);return a};db[" "]=_.na;_.eb=function(a,b){try{return db(a[b]),!0}catch(c){}return!1};var fb=!_.B||9<=ab,gb=_.B&&!_.Za("9");!_.Sa||_.Za("528");_.Ra&&_.Za("1.9b")||_.B&&_.Za("8")||_.Pa&&_.Za("9.5")||_.Sa&&_.Za("528");_.Ra&&!_.Za("8")||_.B&&_.Za("9");_.hb=function(a,b){this.type=a;this.a=this.target=b;this.hb=!0};_.hb.prototype.b=function(){this.hb=!1};var ib=function(a,b){_.hb.call(this,a?a.type:"");this.a=this.target=null;this.clientY=this.clientX=0;this.c=this.state=null;a&&this.U(a,b)};_.q(ib,_.hb);
ib.prototype.U=function(a,b){this.type=a.type;var c=a.changedTouches?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.a=b;var d=a.relatedTarget;d&&_.Ra&&_.eb(d,"nodeName");null===c?(this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:a.pageY):(this.clientX=void 0!==c.clientX?c.clientX:c.pageX,this.clientY=void 0!==c.clientY?c.clientY:c.pageY);this.state=a.state;this.c=a;a.defaultPrevented&&this.b()}; ib.prototype.b=function(){ib.B.b.call(this);var a=this.c;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,gb)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};
var jb,lb;jb="closure_listenable_"+(1E6*Math.random()|0);_.kb=function(a){return!(!a||!a[jb])};lb=0;var mb=function(a,b,c,d,e){this.listener=a;this.proxy=null;this.src=b;this.type=c;this.oa=!!d;this.qa=e;this.key=++lb;this.removed=this.na=!1},nb=function(a){a.removed=!0;a.listener=null;a.proxy=null;a.src=null;a.qa=null};var ob;ob=function(a){this.src=a;this.a={};this.b=0};_.qb=function(a,b,c,d,e,f){var g=b.toString();b=a.a[g];b||(b=a.a[g]=[],a.b++);var k=pb(b,c,e,f);-1<k?(a=b[k],d||(a.na=!1)):(a=new mb(c,a.src,g,!!e,f),a.na=d,b.push(a));return a};ob.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.a))return!1;var e=this.a[a];b=pb(e,b,c,d);return-1<b?(nb(e[b]),Array.prototype.splice.call(e,b,1),0==e.length&&(delete this.a[a],this.b--),!0):!1};
var rb=function(a,b){var c=b.type;c in a.a&&_.xa(a.a[c],b)&&(nb(b),0==a.a[c].length&&(delete a.a[c],a.b--))};ob.prototype.removeAll=function(a){a=a&&a.toString();var b=0,c;for(c in this.a)if(!a||c==a){for(var d=this.a[c],e=0;e<d.length;e++)++b,nb(d[e]);delete this.a[c];this.b--}return b};var sb=function(a,b,c,d,e){a=a.a[b.toString()];b=-1;a&&(b=pb(a,c,d,e));return-1<b?a[b]:null},pb=function(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.removed&&f.listener==b&&f.oa==!!c&&f.qa==d)return e}return-1};
var tb,ub,vb,Ab,Db,Eb,Bb,Gb,Fb,Cb,zb,Hb;tb="closure_lm_"+(1E6*Math.random()|0);ub={};vb=0;_.wb=function(a,b,c,d,e){if(_.ma(b)){for(var f=0;f<b.length;f++)_.wb(a,b[f],c,d,e);return null}c=_.xb(c);return _.kb(a)?a.listen(b,c,d,e):_.yb(a,b,c,!1,d,e)};
_.yb=function(a,b,c,d,e,f){if(!b)throw Error("j");var g=!!e,k=zb(a);k||(a[tb]=k=new ob(a));c=_.qb(k,b,c,d,e,f);if(c.proxy)return c;d=Ab();c.proxy=d;d.src=a;d.listener=c;if(a.addEventListener)a.addEventListener(b.toString(),d,g);else if(a.attachEvent)a.attachEvent(Bb(b.toString()),d);else throw Error("k");vb++;return c};Ab=function(){var a=Cb,b=fb?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b};
Db=function(a,b,c,d,e){if(_.ma(b))for(var f=0;f<b.length;f++)Db(a,b[f],c,d,e);else c=_.xb(c),_.kb(a)?a.Ea(b,c,d,e):a&&(a=zb(a))&&(b=sb(a,b,c,!!d,e))&&Eb(b)};Eb=function(a){if(!_.ka(a)&&a&&!a.removed){var b=a.src;if(_.kb(b))rb(b.S,a);else{var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.oa):b.detachEvent&&b.detachEvent(Bb(c),d);vb--;(c=zb(b))?(rb(c,a),0==c.b&&(c.src=null,b[tb]=null)):nb(a)}}};Bb=function(a){return a in ub?ub[a]:ub[a]="on"+a};
Gb=function(a,b,c,d){var e=!0;if(a=zb(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.oa==c&&!f.removed&&(f=Fb(f,d),e=e&&!1!==f)}return e};Fb=function(a,b){var c=a.listener,d=a.qa||a.src;a.na&&Eb(a);return c.call(d,b)};
Cb=function(a,b){if(a.removed)return!0;if(!fb){var c=b||_.oa("window.event"),d=new ib(c,this),e=!0;if(!(0>c.keyCode||void 0!=c.returnValue)){a:{var f=!1;if(0==c.keyCode)try{c.keyCode=-1;break a}catch(p){f=!0}if(f||void 0==c.returnValue)c.returnValue=!0}c=[];for(f=d.a;f;f=f.parentNode)c.push(f);for(var f=a.type,g=c.length-1;0<=g;g--){d.a=c[g];var k=Gb(c[g],f,!0,d),e=e&&k}for(g=0;g<c.length;g++)d.a=c[g],k=Gb(c[g],f,!1,d),e=e&&k}return e}return Fb(a,new ib(b,this))}; zb=function(a){a=a[tb];return a instanceof ob?a:null};Hb="__closure_events_fn_"+(1E9*Math.random()>>>0);_.xb=function(a){if(_.ja(a))return a;a[Hb]||(a[Hb]=function(b){return a.handleEvent(b)});return a[Hb]};
_.Ib=function(a){_.v(this,a,"h_cc",null)};_.q(_.Ib,_.u);_.x("h_cc",_.Ib);_.Ib.prototype.T=function(){return _.w(this,19)};_.G=function(a){this.a=a};_.G.prototype.toString=function(){return this.a};_.H=function(a){_.C.call(this);this.I=a;this.f={}};_.q(_.H,_.C);var Jb=[];_.H.prototype.listen=function(a,b,c,d){return _.Kb(this,a,b,c,d)};_.Kb=function(a,b,c,d,e,f){_.ma(c)||(c&&(Jb[0]=c.toString()),c=Jb);for(var g=0;g<c.length;g++){var k=_.wb(b,c[g],d||a.handleEvent,e||!1,f||a.I||a);if(!k)break;a.f[k.key]=k}return a};
_.H.prototype.Ea=function(a,b,c,d,e){if(_.ma(b))for(var f=0;f<b.length;f++)this.Ea(a,b[f],c,d,e);else c=c||this.handleEvent,e=e||this.I||this,c=_.xb(c),d=!!d,b=_.kb(a)?sb(a.S,String(b),c,d,e):a?(a=zb(a))?sb(a,b,c,d,e):null:null,b&&(Eb(b),delete this.f[b.key]);return this};_.H.prototype.removeAll=function(){_.za(this.f,function(a,b){this.f.hasOwnProperty(b)&&Eb(a)},this);this.f={}};_.H.prototype.v=function(){_.H.B.v.call(this);this.removeAll()}; _.H.prototype.handleEvent=function(){throw Error("l");};
var Lb=function(a,b,c){this.l=c;this.c=a;this.f=b;this.b=0;this.a=null};Lb.prototype.get=function(){var a;0<this.b?(this.b--,a=this.a,this.a=a.next,a.next=null):a=this.c();return a};var Mb=function(a,b){a.f(b);a.b<a.l&&(a.b++,b.next=a.a,a.a=b)};var Nb,Ob,Pb;Nb=function(a){_.l.setTimeout(function(){throw a;},0)};_.Qb=function(a,b){var c=a;b&&(c=(0,_.r)(a,b));!_.ja(_.l.setImmediate)||_.l.Window&&_.l.Window.prototype&&!_.y("Edge")&&_.l.Window.prototype.setImmediate==_.l.setImmediate?(Ob||(Ob=Pb()),Ob(c)):_.l.setImmediate(c)};
Pb=function(){var a=_.l.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&!_.y("Presto")&&(a=function(){var a=window.document.createElement("IFRAME");a.style.display="none";a.src="";window.document.documentElement.appendChild(a);var b=a.contentWindow,a=b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d="file:"==b.location.protocol?"*":b.location.protocol+"//"+b.location.host,a=(0,_.r)(function(a){if(("*"==
d||a.origin==d)&&a.data==c)this.port1.onmessage()},this);b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});if("undefined"!==typeof a&&!_.y("Trident")&&!_.y("MSIE")){var b=new a,c={},d=c;b.port1.onmessage=function(){if(_.n(c.next)){c=c.next;var a=c.Ya;c.Ya=null;a()}};return function(a){d.next={Ya:a};d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof window.document&&"onreadystatechange"in window.document.createElement("SCRIPT")?function(a){var b= window.document.createElement("SCRIPT");b.onreadystatechange=function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};window.document.documentElement.appendChild(b)}:function(a){_.l.setTimeout(a,0)}};
var Rb=function(){this.b=this.a=null},Tb=new Lb(function(){return new Sb},function(a){a.reset()},100);Rb.prototype.remove=function(){var a=null;this.a&&(a=this.a,this.a=this.a.next,this.a||(this.b=null),a.next=null);return a};var Sb=function(){this.next=this.b=this.a=null};Sb.prototype.set=function(a,b){this.a=a;this.b=b;this.next=null};Sb.prototype.reset=function(){this.next=this.b=this.a=null};
var Yb=function(a,b){Ub||Vb();Wb||(Ub(),Wb=!0);var c=Xb,d=Tb.get();d.set(a,b);c.b?c.b.next=d:c.a=d;c.b=d},Ub,Vb=function(){if(_.l.Promise&&_.l.Promise.resolve){var a=_.l.Promise.resolve(void 0);Ub=function(){a.then(Zb)}}else Ub=function(){_.Qb(Zb)}},Wb=!1,Xb=new Rb,Zb=function(){for(var a=null;a=Xb.remove();){try{a.a.call(a.b)}catch(b){Nb(b)}Mb(Tb,a)}Wb=!1};
_.I=function(){_.C.call(this);this.S=new ob(this);this.K=this;this.C=null};_.q(_.I,_.C);_.I.prototype[jb]=!0;_.h=_.I.prototype;_.h.addEventListener=function(a,b,c,d){_.wb(this,a,b,c,d)};_.h.removeEventListener=function(a,b,c,d){Db(this,a,b,c,d)};_.h.v=function(){_.I.B.v.call(this);this.S&&this.S.removeAll(void 0);this.C=null};_.h.listen=function(a,b,c,d){return _.qb(this.S,String(a),b,!1,c,d)};_.h.Ea=function(a,b,c,d){return this.S.remove(String(a),b,c,d)}; _.h.Z=function(a,b,c){a=this.S.a[String(a)];if(!a)return!0;a=a.concat();for(var d=!0,e=0;e<a.length;++e){var f=a[e];if(f&&!f.removed&&f.oa==b){var g=f.listener,k=f.qa||f.src;f.na&&rb(this.S,f);d=!1!==g.call(k,c)&&d}}return d&&0!=c.hb};
var $b=function(a){a.prototype.then=a.prototype.then;a.prototype.$goog_Thenable=!0},ac=function(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};var cc=function(a,b){this.a=0;this.h=void 0;this.c=this.b=this.l=null;this.f=this.g=!1;if(a!=_.na)try{var c=this;a.call(b,function(a){bc(c,2,a)},function(a){bc(c,3,a)})}catch(d){bc(this,3,d)}},dc=function(){this.next=this.c=this.b=this.l=this.a=null;this.f=!1},ec,fc;dc.prototype.reset=function(){this.c=this.b=this.l=this.a=null;this.f=!1};ec=new Lb(function(){return new dc},function(a){a.reset()},100);fc=function(a,b,c){var d=ec.get();d.l=a;d.b=b;d.c=c;return d};
_.hc=function(){var a,b=new cc(function(b){a=b});return new gc(b,a)};cc.prototype.then=function(a,b,c){return ic(this,_.ja(a)?a:null,_.ja(b)?b:null,c)};$b(cc);
var kc=function(a,b){a.b||2!=a.a&&3!=a.a||jc(a);a.c?a.c.next=b:a.b=b;a.c=b},ic=function(a,b,c,d){var e=fc(null,null,null);e.a=new cc(function(a,g){e.l=b?function(c){try{var e=b.call(d,c);a(e)}catch(A){g(A)}}:a;e.b=c?function(b){try{var e=c.call(d,b);!_.n(e)&&"undefined"!=typeof lc&&b instanceof lc?g(b):a(e)}catch(A){g(A)}}:g});e.a.l=a;kc(a,e);return e.a};cc.prototype.u=function(a){this.a=0;bc(this,2,a)};cc.prototype.w=function(a){this.a=0;bc(this,3,a)};
var bc=function(a,b,c){if(0==a.a){a==c&&(b=3,c=new TypeError("Promise cannot resolve to itself"));a.a=1;var d;a:{var e=c,f=a.u,g=a.w;if(e instanceof cc)kc(e,fc(f||_.na,g||null,a)),d=!0;else if(ac(e))e.then(f,g,a),d=!0;else{if(_.ia(e))try{var k=e.then;if(_.ja(k)){mc(e,k,f,g,a);d=!0;break a}}catch(p){g.call(a,p);d=!0;break a}d=!1}}d||(a.h=c,a.a=b,a.l=null,jc(a),3!=b||"undefined"!=typeof lc&&c instanceof lc||nc(a,c))}},mc=function(a,b,c,d,e){var f=!1,g=function(a){f||(f=!0,c.call(e,a))},k=function(a){f||
(f=!0,d.call(e,a))};try{b.call(a,g,k)}catch(p){k(p)}},jc=function(a){a.g||(a.g=!0,Yb(a.j,a))},oc=function(a){var b=null;a.b&&(b=a.b,a.b=b.next,b.next=null);a.b||(a.c=null);return b};cc.prototype.j=function(){for(var a=null;a=oc(this);){var b=this.a,c=this.h;if(3==b&&a.b&&!a.f)for(var d=void 0,d=this;d&&d.f;d=d.l)d.f=!1;if(a.a)a.a.l=null,pc(a,b,c);else try{a.f?a.l.call(a.c):pc(a,b,c)}catch(e){qc.call(null,e)}Mb(ec,a)}this.g=!1}; var pc=function(a,b,c){2==b?a.l.call(a.c,c):a.b&&a.b.call(a.c,c)},nc=function(a,b){a.f=!0;Yb(function(){a.f&&qc.call(null,b)})},qc=Nb,lc=function(a){_.pa.call(this,a)};_.q(lc,_.pa);lc.prototype.name="cancel";var gc=function(a,b){this.b=a;this.a=b};
_.rc=function(a,b){for(var c=[],d=0;d<arguments.length;d++)c.push(arguments[d]||"");return c.join("_;_")};_.sc=function(){return 0<=window.navigator.userAgent.indexOf("CrOS")};_.J=function(a,b){this.f=a||"e";this.l=null!=a&&"p"==a?"e":"p";this.a=this.g=null;this.j=b||"u";this.c=this.h=null;this.b=[]};_.J.prototype.message=function(){var a={};a.i=this.c;a.m=this.b;a.r=this.j;a.o=this.h;a.s=this.a;a.st=this.l;a.d=this.g;a.dt=this.f;return a};_.J.prototype.message=_.J.prototype.message;
_.tc=function(a,b){for(var c in b)switch(c){case "r":a.j=b[c];break;case "i":a.c=b[c];break;case "m":a.b=b[c];break;case "o":a.h=b[c];break;case "s":a.a=b[c];break;case "d":a.g=b[c];break;case "st":a.l=b[c];break;case "dt":a.f=b[c]}return a};_.uc=function(a,b,c){null!=b&&(a.a=b,null!=c&&(a.l=c))};_.vc=function(a,b){null!=b&&(a.c=b)};_.wc=function(a,b){"object"==typeof b?a.b=b:a.b=[b]};_.J.prototype.target=function(){return this.g};
_.xc=function(a,b,c,d,e){_.C.call(this);this.b=a;this.ma=b;this.a=typeof b;this.Ba=c?c:!1;this.Y=!0;this.Aa=d?d:!1;this.wa=e?e:!1};_.q(_.xc,_.C);_.h=_.xc.prototype;_.h.v=function(){_.xc.B.v.call(this);this.b="";this.ma=null;this.a=""};_.h.id=function(){return this.b};_.h.type=function(){return this.a};_.h.F=function(){return this.ma};_.h.setEnabled=function(a){this.Y=a};
_.zc=function(a){_.C.call(this);this.a=new _.z;this.b=["https://hangouts.google.com","","https://autopush.hangouts.sandbox.google.com?jsmode=du"];a&&_.yc(this,a)};_.q(_.zc,_.C);_.Ac=!_.sc();_.zc.prototype.v=function(){_.zc.B.v.call(this);for(var a=this.a.M(),b=0;b<a.length;++b)_.D(this.a.get(a[b]));delete this.a};_.zc.prototype.getItem=function(a){return _.Ma(this.a.b,a)?this.a.get(a):null};_.zc.prototype.setItem=function(a){this.a.set(a.id(),a)}; _.yc=function(a,b){for(var c in b){var d=b[c],e=null;_.Ma(a.a.b,c)?(e=a.a.get(c),e.ma=d.value,d.changed&&(e.wa=d.changed)):(e=new _.xc(c,d.value,d.multiple,d.inverse,d.changed),e.setEnabled(!d.disabled));a.a.set(c,e)}};
_.Cc=function(){this.c=new _.z;this.a=null;this.b=!1;this.a=new Bc;this.b=!0;this.U()};_.Cc.fa=function(){return _.Cc.a?_.Cc.a:_.Cc.a=new _.Cc};_.h=_.Cc.prototype;_.h.U=function(a){var b=a||_.na;this.b?b():window.chrome.storage.local.get((0,_.r)(function(a){if(!this.b){for(var d in a)this.c.set(d,a[d]);this.b=!0}b()},this))};_.h.get=function(a){return this.a.get(a)};_.h.set=function(a,b){var c=_.hc();this.a.set(a,b);c.a(void 0);return c.b};_.h.remove=function(a){this.a.remove(a)};_.h.clear=function(){this.a.clear()};
var Bc=function(){this.a=window.localStorage};Bc.prototype.clear=function(){this.a.clear()};Bc.prototype.get=function(a){a=this.a.getItem(a);if(a){var b=JSON.parse(a);a=b.data;if("jspb"==b.type){b=Da[a[0]];if(!b)throw Error("d`"+a[0]);a=new b(a)}}else a=null;return a};Bc.prototype.set=function(a,b){var c=null;b instanceof _.u&&(b=b.H,c="jspb");var d={};d.data=b;d.timestamp=(0,_.m)();c&&(d.type=c);c=JSON.stringify(d);try{this.a.setItem(a,c)}catch(e){}};Bc.prototype.remove=function(a){try{this.a.removeItem(a)}catch(b){}};
/*
 Portions of this code are from MochiKit, received by
 The Closure Authors under the MIT license. All other code is Copyright
 2005-2009 The Closure Authors. All Rights Reserved.
*/
var Dc=function(a,b){this.l=[];this.D=b||null;this.a=this.b=!1;this.c=void 0;this.u=this.w=this.g=!1;this.f=0;this.h=null;this.A=0};Dc.prototype.j=function(a,b){this.g=!1;this.b=!0;this.c=b;this.a=!a;Ec(this)};Dc.prototype.C=function(a){if(this.b){if(!this.u)throw new Fc;this.u=!1}this.b=!0;this.c=a;this.a=!1;Ec(this)};var Gc=function(a,b,c){a.l.push([b,c,void 0]);a.b&&Ec(a)};
Dc.prototype.then=function(a,b,c){var d,e,f=new cc(function(a,b){d=a;e=b});Gc(this,d,function(a){e(a)});return f.then(a,b,c)};$b(Dc);
var Hc=function(a){return(0,_.wa)(a.l,function(a){return _.ja(a[1])})},Ec=function(a){if(a.f&&a.b&&Hc(a)){var b=a.f,c=Ic[b];c&&(_.l.clearTimeout(c.a),delete Ic[b]);a.f=0}a.h&&(a.h.A--,delete a.h);for(var b=a.c,d=c=!1;a.l.length&&!a.g;){var e=a.l.shift(),f=e[0],g=e[1],e=e[2];if(f=a.a?g:f)try{var k=f.call(e||a.D,b);_.n(k)&&(a.a=a.a&&(k==b||k instanceof Error),a.c=b=k);if(ac(b)||"function"===typeof _.l.Promise&&b instanceof _.l.Promise)d=!0,a.g=!0}catch(p){b=p,a.a=!0,Hc(a)||(c=!0)}}a.c=b;d&&(k=(0,_.r)(a.j,
a,!0),d=(0,_.r)(a.j,a,!1),b instanceof Dc?(Gc(b,k,d),b.w=!0):b.then(k,d));c&&(b=new Jc(b),Ic[b.a]=b,a.f=b.a)},Fc=function(){_.pa.call(this)};_.q(Fc,_.pa);Fc.prototype.message="Deferred has already fired";Fc.prototype.name="AlreadyCalledError";var Jc=function(a){this.a=_.l.setTimeout((0,_.r)(this.c,this),0);this.b=a};Jc.prototype.c=function(){delete Ic[this.a];throw this.b;};var Ic={};

}catch(e){_._DumpException(e)}
try{
var Mc;_.Kc=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);else if(_.la(a)||_.t(a))(0,_.ta)(a,b,void 0);else{var c;if(a.M&&"function"==typeof a.M)c=a.M();else if(a.G&&"function"==typeof a.G)c=void 0;else if(_.la(a)||_.t(a)){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=_.Ba(a);for(var d=_.Na(a),e=d.length,f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}};_.Lc=function(a){a&&a.parentNode&&a.parentNode.removeChild(a)}; Mc=function(a,b){for(var c=_.t(a)?a.split(""):a,d=a.length-1;0<=d;--d)d in c&&b.call(void 0,c[d],d,a)};
var Nc=function(a,b){this.c=a;this.b=b;this.constructor.Xa||(this.constructor.Xa={});this.constructor.Xa[this.toString()]=this};Nc.prototype.toString=function(){this.a||(this.a=this.c.a+":"+this.b);return this.a};var Oc=function(a,b){Nc.call(this,a,b)};_.q(Oc,Nc);var Pc=function(a){this.a=a};new Pc("lib");_.Rc=function(a){_.C.call(this);this.b={};this.u={};this.w={};this.f={};this.A={};this.D={};this.C=a?a.g():new _.I;this.K=!a;this.h=null;a?(this.h=a,this.w=a.w,this.f=a.f,this.u=a.u,this.A=a.A):(0,_.m)();a=Qc(this);this!=a&&(a.j?a.j.push(this):a.j=[this])};_.q(_.Rc,_.C);var Qc=function(a){for(;a.h;)a=a.h;return a};_.Rc.prototype.get=function(a){var b=this.c(a);if(null==b)throw new Sc(a);return b};
_.Rc.prototype.c=function(a){for(var b=this;b;b=b.h){if(b.L)throw Error("n");if(b.b[a])return b.b[a][0];if(b.D[a])break}if(b=this.w[a]){b=b(this);if(null==b)throw Error("o`"+a);this.a(a,b);return b}return null};_.Rc.prototype.a=function(a,b,c){if(this.L)c||_.D(b);else{this.b[a]=[b,!c];b=Tc(this,this,a);for(c=0;c<b.length;c++)b[c].C(null);delete this.u[a]}};_.Rc.prototype.I=function(){var a=_.Uc;if(!this.b[a])throw Error("p`"+a);var b=this.b[a];delete this.b[a];b[1]&&_.D(b[0])};
var Tc=function(a,b,c){var d=[],e=a.f[c];e&&(Mc(e,function(a){var c;a:{for(c=a.tb;c;){if(c==b){c=!0;break a}c=c.h}c=!1}c&&(d.push(a.d),_.xa(e,a))}),0==e.length&&delete a.f[c]);return d},Vc=function(a,b){a.f&&_.Kc(a.f,function(a,d,e){Mc(a,function(d){d.tb==b&&_.xa(a,d)});0==a.length&&delete e[d]})};
_.Rc.prototype.v=function(){if(Qc(this)==this){var a=this.j;if(a)for(;a.length;)a[0].O()}else for(var a=Qc(this).j,b=0;b<a.length;b++)if(a[b]==this){a.splice(b,1);break}for(var c in this.b)a=this.b[c],a[1]&&"undefined"!=typeof a[0].O&&a[0].O();this.b=null;this.K&&this.C.O();Vc(this,this);this.f=null;_.D(this.J);this.D=this.J=null;_.Rc.B.v.call(this)};_.Rc.prototype.g=function(){return this.C};var Sc=function(a){_.pa.call(this);this.id=a;this.message='Service for "'+a+'" is not registered'}; _.q(Sc,_.pa);var Wc=new Pc("fva");new Oc(Wc,1);

}catch(e){_._DumpException(e)}
try{
_.Qd=function(){return window.chrome.runtime.getURL("feedbackdialog.html")};
}catch(e){_._DumpException(e)}
try{
_.Gg=function(a){for(var b=a.a.M(),c={},d=0;d<b.length;d++){var e=b[d],f=a.a.get(e);c[e]={value:f.F(),type:f.type(),multiple:f.Ba,disabled:!f.Y,inverse:f.Aa,changed:f.wa}}return c};_.Hg=function(a,b){return _.t(b)?a.getElementById(b):b};_.Q=function(a){return _.Hg(window.document,a)};_.Ig=new _.G("a");_.Jg=new _.G("b");_.Kg=new _.G("c");_.Lg=new _.G("d");_.Mg=new _.G("e");_.Ng=new _.G("f");_.Og=new _.G("g");_.Pg=new _.G("h");_.Uc=new _.G("i");_.Qg=new _.G("j");

}catch(e){_._DumpException(e)}
try{
var sj=function(a,b){for(var c=a.split("%s"),d="",e=Array.prototype.slice.call(arguments,1);e.length&&1<c.length;)d+=c.shift()+e.shift();return d+c.join("%s")},tj=function(a){_.C.call(this);this.f=_.rc("setting",""+(0,_.m)());this.c=null;this.b=new _.H;_.F(this,this.b);this.a=new _.z;this.g=a.get(_.Pg);this.b.listen(window,"unload",this.O)};_.q(tj,_.C);_.ga("ace.ui.SettingsDialog",tj);_.ga("ace.ui.SettingsDialog",tj);
tj.prototype.U=function(){window.document.title=window.chrome.i18n.getMessage("CHROME_EXT_SHORT_NAME");this.c=window.chrome.runtime.connect({name:this.f});var a=this;this.c.onMessage.addListener(function(b){switch(_.tc(new _.J,b).c){case "focus":uj(a);a.sendMessage("extensionLibrary",["selectTab",a.f,!0,!0]);window.focus();break;case "close":a.h()}});this.a.set("StartOnBrowserLaunch",["BrowserStartup",1]);this.a.set("StopOnBrowserClose",["Shutdown",1]);this.a.set("TopMost",["TopMost",1]);this.a.set("TrayIcon",
["TrayIcon",1]);_.Lc(_.Q("fieldsetDestPage"));vj("legendApp",window.chrome.i18n.getMessage("QUASAR_LEGEND_STARTUP_SHUTDOWN"));vj("legendNotice",window.chrome.i18n.getMessage("QUASAR_LEGEND_NOTIFICATIONS"));wj(this,"StartOnBrowserLaunch",window.chrome.i18n.getMessage("CHROME_EXT_RUN_AT_BROWSER_START"));wj(this,"StopOnBrowserClose",window.chrome.i18n.getMessage("CHROME_EXT_RUN_AFTER_BROWSER_CLOSE"));wj(this,"TrayIcon",window.chrome.i18n.getMessage("QUASAR_LABEL_TRAY_ICON"));_.Ac?wj(this,"TopMost",window.chrome.i18n.getMessage("CHROME_EXT_NEW_WINDOWS_TOPMOST")):
xj(this,"TopMost");_.sc()&&xj(this,"TrayIcon");uj(this);var b=_.Q("feedbackLink");b.innerText=window.chrome.i18n.getMessage("CHROME_EXT_MENUTEXT_FEEDBACK");b.href=_.Qd();b=_.Q("helpLink");b.innerText=window.chrome.i18n.getMessage("QUASAR_HELP");b.href=sj("https://support.google.com/hangouts?p=help&hl=%s",window.chrome.i18n.getMessage("@@ui_locale"));this.u=_.Q("buttonSave");this.u.innerText=window.chrome.i18n.getMessage("QUASAR_BUTTON_SAVE");this.b.listen(this.u,"click",(0,_.r)(this.w,this),!1);this.j=
_.Q("buttonCancel");this.j.innerText=window.chrome.i18n.getMessage("QUASAR_BUTTON_CANCEL");this.b.listen(this.j,"click",(0,_.r)(this.h,this),!1)};tj.prototype.init=tj.prototype.U;
var yj=function(a,b,c){var d=[];b=b+a.a.get(c)[0];a=a.a.get(c)[1];if(1<a)for(c=0;c<a;c++)d.push(_.Q(b+c));else d.push(_.Q(b));return d},uj=function(a){for(var b=new _.zc(a.g.get("settings")),c=a.a.M(),d=0;d<c.length;d++){var e=b.getItem(c[d]);if(e){var f=yj(a,"field",c[d]);if(e.Ba){var g=e.F();0<=g&&f[g]&&(f[g].checked=!0)}else f[0]&&("boolean"==e.a?e.Aa?f[0].checked=!e.F():f[0].checked=e.F():f[0].value=e.F());if(!e.Y)for(e=yj(a,"label",c[d]),g=0;g<e.length;g++)e[g]&&(e[g].disabled=!0),f[g]&&(f[g].disabled=
!0)}}},vj=function(a,b){var c=_.Q(a);c&&(c.innerText=b)},wj=function(a,b,c){var d=a.a.get(b)[0];a=a.a.get(b)[1];if(1<a)for(b=0;b<a;b++){var e=_.Q("label"+d+b);e&&c&&(e.innerText=c[b])}else(e=_.Q("label"+d))&&c&&(e.innerText=c)},xj=function(a,b){var c=a.a.get(b)[0],d=_.Q("field"+c);(d=(c=(c=_.Q("label"+c)||d)&&c.parentNode)&&c.parentNode)&&d.removeChild(c)};
tj.prototype.w=function(){for(var a=new _.zc(this.g.get("settings")),b=this.a.M(),c=0;c<b.length;c++){var d=a.getItem(b[c]);if(d){var e=yj(this,"field",b[c]),f=d.F();if(d.Ba){for(var g=-1,k=0;k<e.length;k++)if(e[k]&&e[k].checked){g=k;break}-1==g&&(g=0);d.ma=g}else e[0]&&(d.ma="boolean"==d.a?d.Aa?!e[0].checked:e[0].checked:e[0].value);f!=d.F()&&(d.wa=!0,a.setItem(d))}}this.g.set("settings",_.Gg(a));this.h()};
tj.prototype.h=function(){this.sendMessage("settingsManager",["updateSettingsFromStorage"]);window.close()};tj.prototype.sendMessage=function(a,b,c){c=c?c:""+(0,_.m)();var d=new _.J;_.uc(d,this.f,"p");null!=a&&(d.h=a);_.vc(d,c);_.wc(d,b);this.c&&this.c.postMessage(d.message())};
window.addEventListener("load",function(){_.Cc.fa().U(function(){var a=new _.Rc;a.a(_.Pg,_.Cc.fa());(new tj(a)).U()})},!1);
}catch(e){_._DumpException(e)}
}).call(this,this.default_settings);
// Google Inc.
